### ISSUE TITLE
Dokumenten-Feld nur in Größe 12 anschaulich

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1001]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/157

**Acceptance Criteria**

- [ ] Benutzung von Dokumenten-Feld in Bezug auf Gruppierung ist in DigiWF-Doku beschrieben

**Comment by lmoesle** [comment]
Den Fehler kann ich nachstellen (siehe https://github.com/it-at-m/digiwf-core/pull/133/files).
Wenn man in einem Object Properties definiert (Json Schema) und zum Anzeigen des Felds eine eigene Componente erstellt tritt der Fehler auf. Wenn man keine Properties definiert funktioniert es.

![multifile-input-grid-bug.png](https://images.zenhubusercontent.com/622f4d4cf7a5f47ea3c5213c/ad1be5c6-449d-4679-8a6e-739f68d984c3)

Wo der Fehler auftritt und wie ich ihn lösen kann habe ich noch nicht gefunden. Ich mache jetzt erstmal wo anders weiter.

**Comment by LenaB34** [comment]
Keine hohe Prio - Wird auf Ready zurückgeschoben

**Comment by dominikhorn93** [comment]
Die Library kann das leider nicht.
Man kann den Titel "fIles" verstecken, es landet aber immer in 2 Reihen, da bei verschiedenen Objekte (durch properties gegeben) ein Umbruch gemacht wird.

**Comment by lmoesle** [comment]
@dominikhorn93 kannst du die Info bitte auch noch ins Modellierungshandbuch aufnehmen? Für die User ist das glaube ich ganz gut zu wissen, dass custom fields (wie das file input) immer die volle Breite verwenden.

**Comment by LenaB34** [comment]
Thema fließt in die Formulardokumentation ein.

**Comment by darenegade** [comment]
Die Doku dazu fehlt immernoch
