### ISSUE TITLE
Upgrade RHEL7 server

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1025]
RHEL7 is only supported till 30.06.2024. Before that all servers need to be updated to RHEL8 oder 9.
The list of the three affected servers is in the internal issue.

See internal issue https://git.muenchen.de/ccse/km8-intern/-/issues/300

Alternative is to switch to PostgreSQL till then with #581

## Acceptance criteria
- All DigiWF servers are at least at version RHEL8

## Server
- [x] digiwfdbk001 (digiwf-test, -demo)
- [x] digiwfdbp001

**Comment by darenegade** [comment]
Ziel sollte eigentlich sein, dass wir bis Juni auf Postgres umgestiegen sind: #581

**Comment by darenegade** [comment]
RHEL 7 kann auch noch etwas verlängert werden: "Zwar wird es für RHEL 7 voraussichtlich für eine Übergangszeit ebenfalls wieder Extended Support geben, dennoch ist unbedingt auch hier die Migration zeitnah einzuplanen und anzugehen. Aufgrund größerer Standardisierung und technischer Übereinstimmungen sollte die Migration in den meisten Fällen deutlich einfacher sein als die von RHEL 6 auf höhere Versionen."

Wenn die Migration auf Postgres also nicht ganz geschafft wird, dann ist das kein Problem

**Comment by darenegade** [comment]
DB Server mit Oracle 19c und RHEL9 können ab Anfang Q2/24 bestellt werden. Bis dahin blocked

**Comment by markostreich** [comment]
Tests von Oracle 19c auf RHEL9 sind abgeschlossen. Momentan hängt es nur noch am Ticket in SNow, das in der Vorbereitung ist. Es ist mit einer zeitnahen Fertigstellung zu rechnen. Einen genauen Zeitpunkt habe ich aber nicht.

(Oracle 23c ist aktuell noch nicht im Test.)

**Comment by markostreich** [comment]
Ich fange mit test und demo an (digiwfdbk001) und nehme die Erfahrungen mit für die Produktion.

**Comment by markostreich** [comment]
**Erstmal zurückgestellt**: Doris Kais hat angeregt, digiwfdbk005 als separaten Container mit auf den neu bestellten DB-Server zu holen. Ich habe dem zugestimmt. Da das quasi produktiv ist, probieren wir es am Freitag, 6.9. um 13 Uhr aus.

**Comment by markostreich** [comment]
Daten von von test und demo sind auf die neue DB umgezogen. Bisheriger Cname wird weiter verwendet -> keine Anpassung im Ops-Repo.

- [x] Abbau der alten DB ist im Gange.

**Comment by markostreich** [comment]
prod DB ist bestellt: **RITM0813317**

**Comment by markostreich** [comment]
Daten von prod sind auf die neue DB umgezogen. Bisheriger Cname wird weiter verwendet.
Abbau ist im Gange.

**Comment by markostreich** [comment]
Abbau erledigt.
