### ISSUE TITLE
app_message_name not unique

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1068]
In the camunda-connector the `app_message_name` is used to map the message to the correlating process step and parse the payload back into the process.
Problem here is that the attribute is not unique with `genericEvent` in the [element templates](https://git.muenchen.de/digitalisierung/bpm-modeler/-/blob/develop/frontend/src/components/ElementTemplates.ts?ref_type=heads#L2301) which can lead to a error when a process runs two integrations calls in parallel. In real use cases that is very unrealistic but it would be a good idea to fix that anyway.

It may also make sense to use `app_type_name` and `app_integration_name` (see #958) instead of `app_message_name` for the resolution.

## Possible solutions
1. make `app_message_name` unique
2. use `app_type_name` and `app_integration_name`

## Acceptance criteria

- [ ] The mapping from a integration response to a process step is always unique

**Comment by simonhir** [comment]
@lmoesle was meinst du dazu?

**Comment by lmoesle** [comment]
Die Integrationen werden in einer Call Activity aufgerufen. Da wird dann ein eigener Subprozess erstellt für das Streaming Template, an den auch die Message der Integration korreliert wird. Also müsste der Prozess schon unique sein.

**Comment by simonhir** [comment]
Is no bug. See above comment
