### ISSUE TITLE
Multi-File-Input Dateianzahl konfigurierbar

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1128]
**Is your feature request related to a problem? Please describe.**

Aktuell ist die Dateianzahl beim Mulit-File-Input auf 10 fest beschränkt. Dies ist sehr unflexibel in beide Richtungen, da es vorkommen kann, dass fachlich weniger Dateien sinnvoll sind oder ein Limit von 15, 20, 30 notwendig ist.

**Describe the solution you'd like**

Das Limit soll per X-Property im JSON-Schema einstellbar sein. Und CoCreation soll der Wert gesetzt werden können.
Für die Rückwärtskompatibilität muss der der Komponente der Wert 10 gesetzt werden, wenn die Property leer/n.v. ist.

In dem Zusammenhang kann auch gleich #224 gelöst werden: 

* Dateigröße insgesamt soll validiert werden (Soll auch konfigurierbar sein, aber einen Default in der Komp. haben, damit wir rückwärtskompatibel sind)

**Describe alternatives you've considered**

Aufteilen auf mehrere Inputs -> Nicht immer möglich, da beispielsweise die Dateien auch von extern kommen können. z.B. CIT

**Acceptance Criteria**

- [x] DateiLimit bei Multi-File-Input ist über JSON-Schema konfigurierbar
- [x] Gesamtgröße aller Dateien ist über JSON-Schema konfigurierbar
- [x] Accept von Files kann gesetzt werden

**Additional context**

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/421

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/364

**Comment by darenegade** [comment]
Das Thema blockiert den EOZF Release (16.01.) und muss daher priorisiert behandelt werden

**Comment by darenegade** [comment]
Schätzung wird Montag nachgeholt

**Comment by LenaB34** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1128?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @simonhir @StephanStrehlerCGI @zambrovski

**Comment by darenegade** [comment]
@lehju Hier ist das interne Ticket zu dem `accept`

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/364

**Comment by darenegade** [comment]
Doku: Es wurde im Daily abgestimmt, dass wenn man hier eh schon dran ist, auch gleich das Accept Problem lösen könnte
