### ISSUE TITLE
Suche von E-Akte um Fachdatum erweitern

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1149]
**Is your feature request related to a problem? Please describe.**

Mit der neuen DMS Schnittstelle von Fabasoft ist es nun möglich nicht nur im Titel per Text zu suchen, sondern man kann auch ein Fachdatum (Metadaten) angeben und dies als Filter benutzen. Dies ermöglicht die eindeutige Identifizierung einer Akte durch einen fachlichen Schlüssel.

**Describe the solution you'd like**

Erweiterung der E-Akte Suchen Schnittstelle die zwei optionalen Parameter zur Suche auf den Fachdaten

Validierung eins zu eins, wie die E-Akte API bzw. direkt über die DMS-API validieren und Fehler weiterreichen

* Anpassung der DMS-Int. 
* Anpassung der Element-Templates
    * ET muss nicht validieren, dass beide Parameter gesetzt sind 
* Doku

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] DMS Schnittstelle ermöglicht Suche nach Akten über Metadaten
- [x] Funktion ist dokumentiert
- [x] ET stehen in der CoCreation zur Verfügung

**Additional context**

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/395

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1149?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI

**Comment by markostreich** [comment]
@lehju Führe bitte das Review durch.

https://github.com/it-at-m/digiwf-core/pull/1242
https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/62
