### ISSUE TITLE
Prozesse mit externen Links

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1150]
**Is your feature request related to a problem? Please describe.**

Prozesse laufen in der Regel nicht losgelöst, sondern bewegen sich mit allen Integrationen innerhalb einer Vielzahl von Systemen. Beispielsweise gehören zu vielen Prozessen zugehörige E-Akten oder Tickets in der Kontakthistorie (Zammad).

Als User möchte ich über User-Tasks oder Vorgänge auf relevante externe Systeme per Deep-Link navigieren können, um nicht selber in den externen Systemen die zugehörigen Teile suchen zu müssen.

**Describe the solution you'd like**

* Es sollen Listen von Links definiert werden können
* Es werden Typen von Links definiert
    * Für den Start: EAkte (MUCS, KVR, DiPa), Zammad, URL
    * Im Backend werden die Links per Konfiguration aufgeöst (Enrichment)
         * Dies soll per Port erfolgen, damit zukünftig das Enrichment erweitert werden kann 
* UI
    * Es gibt eine neue Component, die die Task-Variable nimmt und entsprechend anzeigt
    * Für den ersten Wurf werden nur Links angezeigt und keine weiteren Infos
* Prozess
    * Es wird eine neue Task-Variable eingeführt `app_task_external_links`
    * Dies Variable wird durch den Prozess für den Task gesetzt
    * Die Variable hat ein Liste von Links mit Typ und Wert       

**Describe alternatives you've considered**

**Acceptance Criteria**

- [ ] Aus einem User-Task oder Vorgang komme ich direkt auf externe Systeme
- [ ] Welche ext. Links am Task angezeigt werden, kann der Prozess bestimmen

**Additional context**

**Comment by dominikhorn93** [comment]
<img width="868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09fc72adcd1a1fd578fffabd8eb782c102799798/Bildschirmfoto%202024-01-15%20um%2011.40.20.png" alt="Bildschirmfoto 2024-01-15 um 11.40.20.png" />

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1150?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @markostreich @StephanStrehlerCGI @zambrovski
