### ISSUE TITLE
Deployment-Proxy Initialisierung

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1156]
**Is your feature request related to a problem? Please describe.**

Als User der neuen CoCreation möchte ich aus der IDE heraus auf den Processes-* Umgebungen ein Deployment aller Artefakte ausführen können, um meine erstellten Prozesse zu testen.

**Describe the solution you'd like**

* Entwicklung in it-at-m/digiwf-cocreation
* Deployment-Service
   * Für Nutzer gibt es zwei Proxies - K und P, Für Entwicklung gibt es noch einen Dev und Test in K
        * Produktion wird in diesem Ticket nicht abgedeckt - Neues Ticket  
   * Nutzung von Miranum-Deployment-Starter
   * Deployment soll über REST und EAI-Routen auf direkt auf den DigiWF-Engines erfolgen
   * Authentifizierung über SA - Mit Rechte für Deploy
* Receiver-Starter in Engine integrieren
* ~~Ops~~
    *  ~~Neue Deployments für Dev/Test/Demo~~
    *  ~~EAI-Routen einrichten~~
        * ~~Für den Start reicht hier die DigiWF-Demo~~
        * ~~Für andere Umgebungen wird noch ein Ticket angelegt~~
    *  ~~SSO Config (SA)~~

**Describe alternatives you've considered**

**Acceptance Criteria**

- [ ] Deployment von allen Artefakten (bpmn, dmn, form, config) ist lokal über den Deployment Proxy (mit Postman oder Swagger-UI) möglich

**Additional context**

**Comment by lmoesle** [comment]
FYI Für die Miranum-IDE haben wir schon vorgefertigte Spring Boot Starter erstellt, die wir in digiwf einbauen könnten. Ich habe dazu auch schon mal eine Doku geschrieben https://github.com/Miragon/miranum-ide/tree/main/spring-boot-apps/miranum-deployment

Mir fallen da noch ein paar Punkte ein, über die wir bei dieser Story sprechen sollten:
- Wollen wir in Zukunft Deployments über REST machen?
  - Die aktuellen async Deployments haben das Problem, dass man dem User kein Feedback geben kann, ob das Deployment erfolgreich war oder nicht
- Sollen Deployments aus der bisherigen CoCreation auch über den Deployment-Proxy laufen?
  - Für uns Entwickler wäre es denke ich einfacher, wenn alle Deployments über den Proxy laufen. Dann könnten wir einiges an legacy Code aus der Engine entfernen
- Aktuell gibt es noch kein VS-Code Plugin für Deployments. Testen könnte man das über die CLI https://www.npmjs.com/package/@miragon/miranum-cli

**Comment by lmoesle** [comment]
Beispiel für den Miranum-Deployment Proxy: https://github.com/Miragon/miranum-platform/tree/main/services/deployment-service

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1156?planning-poker) with Zenhub @dominikhorn93 @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1156?planning-poker) with Zenhub @darenegade

**Comment by lmoesle** [comment]
Ich habe den Ops Part aus dem Issue hier entfernt und dafür ein extra Ticket angelegt (#1331). Das macht es für mich einfacher und übersichtlicher.

Aus diesem Grund habe ich auch oben das Ticket angepasst.
