### ISSUE TITLE
Modellierungs-Doku DMS-Integration

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1174]
**Is your feature request related to a problem? Please describe.**

Als Prozessdesigner benötige ich eine fachliche Dokumentation der DMS-Bausteine, um zu wissen, wie ich diese in meinem Prozess verwende.

**Describe the solution you'd like**

Doku für neue DMS hier erstellen:

https://digiwf.oss.muenchen.de/modeling/integrations/catalog/

* Beschreibung der UseCases analog zu CoSys mit Beispielen

**Describe alternatives you've considered**

Keine Doku -> Prozessdesigner traurig

**Acceptance Criteria**

- [x] Doku für alle DMS Funktionen vorhanden

**Additional context**

**Comment by simonhir** [comment]
Es wäre wahrscheinlich auch interessant zu erwähnen welche Werte direkt durch gereicht werden, damit dann auch die Syntax für z.B. den `searchString` einfach aus der [Fabasoft Doku](https://confluence.muenchen.de/display/LE/Fabasoft+Schnittstellen+Spezifikationen) nachvollziehen kann.

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1174?planning-poker) with Zenhub @darenegade @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI @dominikhorn93
