### ISSUE TITLE
Englische Labels bei Objekt-Listen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1202]
**Describe the bug**

Für Objekt-Listen sind nicht alle Übersetzungstexte richtig gesetzt, sodass teilweise englische Labels auftauchen. Das verwirrt etwas und ist inkonsistent

**To Reproduce**

See internal Issue

**Expected behavior**

Alle Labels auf Deutsch

**Screenshots**
See internal

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/390

**Comment by markostreich** [comment]
https://github.com/it-at-m/vuetify-jsonschema-form/pull/11

**Comment by markostreich** [comment]
Ich übersetze noch weitere Labels.

**Comment by markostreich** [comment]
Bitte das Review durchführen: https://github.com/it-at-m/vuetify-jsonschema-form/pull/11

**Comment by simonhir** [comment]
Ist approved, muss dann nur noch in die [Tasklist im digiwf-core](https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-apps/packages/apps/digiwf-tasklist/package.json#L18) eingebaut werden, wenn das released wurde.
