### ISSUE TITLE
Veraltete Node Version 16

### ISSUE THREAD

**Issue by hupling** [it-at-m/digiwf-core#1206]
warum werden auch verschiedene Versionen verwendet.

beispiel mit node 16
https://github.com/it-at-m/digiwf-core/blob/dev/.github/workflows/build-apps.yaml#L20

beispiel mit node 18
https://github.com/it-at-m/digiwf-core/blob/dev/.github/workflows/build-docs.yaml#L25

**Comment by darenegade** [comment]
Duplikat zu #753
