### ISSUE TITLE
Set multi-file-input as mandatory field doesnt work

### ISSUE THREAD

**Issue by lehju** [it-at-m/digiwf-core#1209]
**Describe the bug**
Setting the multi-file input as mandatory field is not possible.

**To Reproduce**
1. Create files field and set as required
2. The form can be sent although the field is empty

**Expected behavior**
The form should inform me that I have not uploaded a document and that it is a mandatory field. I should also not be able to complete the form.

**Acceptance Criteria**
- [x] Multi-file-input can be set as mandatory field

**Additional context**
- https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/427

**Comment by darenegade** [comment]
@lehju Bitte als Hotfix ausbringen
