### ISSUE TITLE
Camunda Process Monitoring

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1229]
**Is your feature request related to a problem? Please describe.**

As provider of the digiwf platform i want to know if after a release all processes work fine. For that it would be great to have a overview of started/running/completed and failed process instances.
As a process developer i want to know if a release (digiwf or process definition) broke one of my processes and be notified if incidents are increasing.

**Describe the solution you'd like**

Graphical overview of started/running/completed/failed process instances (complete cluster and per process). A good solution for that would be grafana and using the camunda provided prometheus endpoint.
Also there should be the possibility for notifications if incidents are increasing fast or 100% is failing. (Also possible with grafana)

* Prometheus Metrics are broken since SB3
    * Maybe missing Deps or Security
* Grafana is already deployed but doesn't get any data  
* Configure Alerting in Grafana

**Describe alternatives you've considered**

There are no real alternatives. Other monitoring solutions like appd would only detect failures calling integrations not logical or internal script errors. These monitoring tools would be more of a extension for deeper insight.

**Acceptance Criteria**

- [ ] Failing process instances are monitored and could be viewed graphically
- [ ] Alerts are sent if failing instances increase (a good threshold logic needs to be found)

**Additional context**

- https://camunda.com/blog/2022/10/monitoring-camunda-platform-7-with-prometheus/
- https://git.muenchen.de/openshift/openshift-configs/-/wikis/Grafana
- https://git.muenchen.de/openshift/openshift-configs/-/wikis/Prometheus-Application-Monitoring

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1229?planning-poker) with Zenhub @darenegade @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1229?planning-poker) with Zenhub @dominikhorn93

**Comment by dominikhorn93** [comment]
auf der demo Umgebung funktioniert noch alles: https://grafana-route-digiwf-demo-capmanaged.apps.capk.muenchen.de/d/rjaygWhnk/camunda-dashboard?orgId=1 

Es liegt hier vermutlich daran, dass es von der alten REST-API gezogen wurde und die nur noch in den Optimize Umgebungen läuft.

**Comment by darenegade** [comment]
Entscheidungs-Doku: Das Dashboard wird auch nur auf vollwertigen Umgebungen inklusive Optimize benötigt. Daher muss hier nichts gefixed werden, nur Doku angepasst mit den Links.

Dashboardanpassung und Alert ist weiterhin Teil des Tickets

**Comment by zambrovski** [comment]
Wir messen aber deutlich zu wenig. Ich werde weitere Monitore ergänzen und dann schauen wir weiter.

**Comment by darenegade** [comment]
@simonhir schaut noch, ob das auf den Umgebungen alles läuft. Dann wird das hier geschlossen

**Comment by simonhir** [comment]
Funktioniert, weiter Analyse und Anpassungen im Rahmen von #1251
