### ISSUE TITLE
Suche nach einer E-Akte kann mehrere Treffer liefern

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1248]
**Is your feature request related to a problem? Please describe.**

Als Benutzer von DigiWF möchte ich als Suchergebnis der Suche nach einer E-Akte eine Liste zurückerhalten, wenn es mehrere Treffer gibt.

**Describe the solution you'd like**

Erweiterung der DMS-Integration um die Rückgabe einer Trefferliste.

* Anpassung der DMS-Integration
    * Es soll die Liste durchgegeben werden 
* Anpassung der/des Show cases und Example
    * Erstes Element nehmen in Prozess 
* Dokumentation

**Describe alternatives you've considered**

**Acceptance Criteria**

- [ ] Erweiterung DMS-Integration um Rückgabe einer Trefferliste
- [ ] Anpassugs Show Cases und Examples
- [ ] Dokumentation

**Additional context**

Liste wurde damals in #662 schon gefordert
Ticket schließt an #1149

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1248?planning-poker) with Zenhub @darenegade @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI
