### ISSUE TITLE
Remove s3 postgres

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1264]
Currently the S3-integration has a PostgreSQL db for cleaning up files. This function is directly supported from S3 via lifetime.
Therefore the separate db functionality should be removed and be replaced by the S3 lifetime.

The lifetime can i.e. be set via S3-Browser

## Acceptance criteria

- [x] The S3-integration does not use a database anymore
- [x] The S3-integration passes the HexagonalArchitectureTest (needs to be added)

## Alternative solution for cleanup

- New method for tagging folders with (deprecation) label
- Configure S3 lifecycle to cleanup files having the deprecation label
- Tagging could be triggered through engine process end event

## References
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html#intro-lifecycle-rules-actions

**Comment by markostreich** [comment]
Bitte prüfen, ob die DB irgendwo für direkte Abfragen genutzt wird. Das wäre noch ein Hinderungsgrund für den Abbau.
Usecase wäre: Ordner-Abfrage (evtl. im Kontext Erstellen der Presigned-URL)

**Comment by markostreich** [comment]
Bitte diese Properties im ops-Repo entfernen/korrigieren:
```
  IO_MUENCHENDIGITAL_DIGIWF_S3_CRONJOB_CLEANUP_EXPIREDFOLDERS: "0 15 10 15 * ?"
  IO_MUENCHENDIGITAL_DIGIWF_S3_CRONJOB_CLEANUP_UNUSEDFOLDERS: "0 15 10 16 * ?"
```
Wird in #1706 offen gelassen.

**Comment by markostreich** [comment]
Das gibt es in application-itest.yaml und application-test.yaml vom digiwf-s3-integration-service.
```
io.muenchendigital.digiwf.s3:
  cleanupcronjob: "0 15 10 15 * ?"
```
Sieht so aus, als ob das nicht mehr genutzt wird. Kann wohl auch weg.
