### ISSUE TITLE
The digiwf-engine crashes on startup if forms (json schema) have too long keys

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#1311]
**Describe the bug**

The digiwf-engine crashes on startup if forms (json schema) have too long keys.

With https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/resources/db/migration/oracle/V8__JsonSchema.sql the json schema key has to a maximum of 36 characters.

**To Reproduce**

1. Start the engine and use a oracle db

**Expected behavior**

The behaviour should be the same as in environments with prostgres dbs

**Comment by lmoesle** [comment]
We disable auto deployment of forms and configs in digiwf-test stage. We should raise the character length in the oracle db migrations accordingly to postgres migrations

**Comment by simonhir** [comment]
Solution: new migration to change the length for the key for oracle to 255 be equal to PostgreSQL
