### ISSUE TITLE
Github CI Maven Release fails

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1328]
The github ci step `Perform maven release` fails for workflow `release-services/release-services` with following error message:

```
[INFO] --- gpg:3.1.0:sign (sign-artifacts) @ digiwf-core ---
[INFO] Signing 1 file with default secret key.
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```
https://github.com/it-at-m/digiwf-core/actions/runs/7972103934/job/21763386328

## Workaround
Run release without `Maven release`. Problem here is that the packages are not deployed to maven central.

## Acceptance criteria
- The ci runs successful with the step `Perform maven release` and the packages are correctly sent to Nexus Package Manager (Sonatype)

## Reference
- https://github.com/actions/setup-java/issues/447#issuecomment-1399235325

**Comment by lmoesle** [comment]
Den gleichen Fehler habe ich auch im digiwf-cocreation Repo. Vermutlich tritt das bei jedem it-at-m Repo auf, dass in maven central releasen möchte.

**Comment by zambrovski** [comment]
Der Schlüssel ist tatsächlich abgelaufen:

```
Run gpg --list-keys
/home/runner/.gnupg/pubring.kbx
-------------------------------
pub   rsa3072 2022-02-17 [SC] [expired: 2024-02-17]
xxx
uid           [ expired] Claus Straube <claus.straube@muenchen.de>
/home/runner/.gnupg/pubring.kbx
```
