### ISSUE TITLE
Fehler beim Dateiupload in Processesdemo

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1366]
**Describe the bug**
Beim Dateiupload kommt es zu folgendem Fehler im digiwf-engine-service:
```
de.muenchen.oss.digiwf.shared.exception.IllegalResourceAccessException: No access to defined property
	at de.muenchen.oss.digiwf.process.definition.domain.service.ServiceStartFileService.checkWriteAccess(ServiceStartFileService.java:97)
	at de.muenchen.oss.digiwf.process.definition.domain.service.ServiceStartFileService.getPresignedUrl(ServiceStartFileService.java:58)
	at de.muenchen.oss.digiwf.process.definition.api.resource.ServiceStartFileRestController.getPresignedUrlForFileUpload(ServiceStartFileRestController.java:81)
```

**To Reproduce**
1. Starte einen Vorgang mit Dateiupload.
2. Drücke auf das Upload-Symbol und wähle eine Datei aus.

Der Browser meldet '403 Forbidden'. In Kibana ist obiger Stacktrace geloggt.

**Expected behavior**
Der Dateiupload funktioniert auf der Umgebung fehlerfrei.

**Comment by lmoesle** [comment]
> In den Inputparameter S3 Pfade für Schreibrechtigungen (app_file_paths) und S3 Pfade für Leseberechtigungen (app_file_paths_readonly) müssen im Usertask der/die Ordner angegeben werden, auf die der User zugreifen darf. Wird ein Datei-Upload-Feld bei Prozessstart verwendet, müssen die beiden Parameter als Prozessconfig gesetzt werden. Ordnernamen können als Semicolon separierte Liste angegeben werden (z.B. ordner1;ordner2).

@markostreich Man muss 2 Berechtigungen als Input Variablen im Usertask definieren https://digiwf.oss.muenchen.de/modeling/forms/fields/#dateien

**Comment by darenegade** [comment]
Darüber bin ich auch schon gestolpert, da es nicht ganz so intuitiv ist. Aber ja, das ist kein Bug, sondern eher ein Verständnis Problem
