### ISSUE TITLE
ElementTemplate 'Cosys: Dokument erstellen V02' fehlt im ausgerollten Modeller

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1368]
**Describe the bug**
Obwohl das ElementTemplate 'Cosys: Dokument erstellen V02' Teil der ausgerollten Modeller-Version 1.3.2 ist, wird es im Modeller nicht angezeigt.

**To Reproduce**
1. Go to '[Modellverwaltung Testumgebung](https://digiwf-co-creation-test.apps.capk.muenchen.de/repository/#/)'
2. Erstelle ein BPMN Diagramm
3. Füge eine Call Activity ein.
4. Klicke auf die Auswahl des Element Templates

=> ElementTemplate 'Cosys: Dokument erstellen V02' wird nicht angeboten.

**Expected behavior**
ElementTemplate 'Cosys: Dokument erstellen V02' sollte in der Auswahl der Element Templates im Modeller auswählbar sein.

**Screenshots**
<img width="614" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8c570a62bb8317b75d976deb0fc776815abe640/grafik.png" alt="grafik.png" />

**Additional context**
Dass Version 1.3.2 des Modellers in allen Umgebungen ausgerollt ist, wurde schon geprüft.

**Comment by simonhir** [comment]
Dürfte noch nie gegangen sein
https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/70
