### ISSUE TITLE
Zentrale Liste der Schnittstellen und Ansprechpartner

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1374]
**Is your feature request related to a problem? Please describe.**

Als DigiWF-Entwickler möchte ich auf eine Übersicht sämtlicher Schnittstellen von DigiWF zugreifen können, die auch die Ansprechpartner enthält, damit ich weiß an wen ich mich für Absprachen oder bei Problemen in der Entwicklung wenden kann. Soweit bekannt wird auch eine Vertretung angegeben.

**Describe the solution you'd like**

Die Liste wird an einer zentralen nicht öffentlichen aber für alle Teammitglieder erreichbaren Stelle abgelegt.
a) im Betriebshandbuch (Zugriffsmöglichkeit prüfen) oder
b) in Confluence

**Describe alternatives you've considered**

**Acceptance Criteria**

- [ ] Eine Liste mit allen Schnittstellen liegt vor.
- [ ] Soweit möglich sind pro Schnittstelle zwei Ansprechpartner genannt.
- [ ] Erreichbarkeit durch die externen Projektmitglieder ist geprüft.

**Additional context**

**Comment by simonhir** [comment]
Wird mit #1381 erledigt
