### ISSUE TITLE
Init Zammad Integration Ops

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#1377]
Ops Ticket for Zammad Integration.

**Comment by simonhir** [comment]
Topics für Engine->Ticket-Integration: https://git.muenchen.de/openshift/kafka/-/merge_requests/23

**Comment by simonhir** [comment]
Ops-MR: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/362
Anpassung SSO-Clients für SSO test und prod noch offen: REQ0669767
