### ISSUE TITLE
Monitoring der Pods in den Umgebungen

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1379]
**Is your feature request related to a problem? Please describe.**

Als Entwickler im DigiWF-Projekt möchte ich über den Zustand der Pods nach einem Deployment informiert werden. Dafür wird das Monitoring der Dev- und weiterer Umgbeungen ausgebaut.

**Describe the solution you'd like**

Das Monitoring mit Grafana wird ausgebaut, sodass Entwickler nach regelmäßigen Releases schnell informiert werden, falls ein Deployment nicht mehr funktioniert. Die Lösung wird auf alle Umgebungen ausgeweitet.
Für die Alarmierung wird ein sinvolles Threshold gewählt: z. B. wird erst alarmiert, wenn ein Pod für 5 Minuten nicht startet.

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] Es liegt ein Monitoring vor, das nicht mehr funktionierende Deployments erkennt.
- [x] Entwickler werden (E-Mail oder WebEx) über defekte Deployments informiert.
- [x] Definition der Alerts und des Deshboards wird über das Ops-Repo ausgerollt.
- [x] Die Lösung wird auf allen Umgebungen ausgerollt.

**Additional context**

**Comment by markostreich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1379?planning-poker) with Zenhub @darenegade @lehju @simonhir

**Comment by simonhir** [comment]
Evtl kann auch direkt das Beispiel https://github.com/it-at-m/digiwf-cocreation/blob/47238746bd7e5ee90d26773f18ebaf37a9075ba5/digiwf-cocreation-deployment-service/README.md genutzt werden

**Comment by simonhir** [comment]
Ops-Mr: https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/422
