### ISSUE TITLE
Auto Deployment auf Dev & Test

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#138]
Mit externen Imagestreams und Deployment-Triggern können wir das Deployment von SNAPSHOT Versionen auf Test und Dev automatisieren:

https://git.muenchen.de/ccse/cicd/sps/-/issues/420#note_520914

**Comment by Sbivvds241** [comment]
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/86
