### ISSUE TITLE
Betriebshandbuch aufräumen

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1381]
**Is your feature request related to a problem? Please describe.**

Das interne Betriebshandbuch hat viele veraltetet und doppelte Informationen, was dazu führt, das das Betriebshandbuch fast keinen Nutzen hat.

**Describe the solution you'd like**

Das Betriebshandbuch muss aufgeräumt werden. Dabei ist besonders auf folgende Punkte zu achten:
- Doppelte Informationen zusammenfassen
- Veraltete Informationen entfernen oder aktualisieren
- Übersichtliche Struktur
- Informationen, welche in der öffentlichen Dokumentation bereits erklärt sind, entfernen und verlinken

**Describe alternatives you've considered**

Keine Alternative

**Acceptance Criteria**

- [x] Alle Informationen sind nur einmalig vorhanden
- [x] Veraltete Informationen sind entfernt oder aktualisiert
- [x] Die Struktur ist einfach verständliche
- [x] Informationen sind nur im Betriebshandbuch oder der öffentlichen Dokumentation
~~- [ ] Relevante Informationen aus der öffentlichen Dokumentation sind verlinkt~~ (nichts entsprechendes gefunden)
- [x] Schnittstellen sind aktualisiert mit Bezeichnung und aktuellen Ansprechpartnern
- [x] Todos abarbeiten (bis auf offene Testfälle)
 - [x] Anbindungen pro Umgebung refaktorisieren

**Additional context**

- https://wiki.muenchen.de/betriebshandbuch/wiki/DigiWF

**Comment by markostreich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1381?planning-poker) with Zenhub @darenegade @lehju @simonhir

**Comment by darenegade** [comment]
@markostreich @simonhir 

@simonhir und ich sind das Handbuch durchgegangen und eigentlich müssten nur noch die ToDos erledigt werden. Dann passt es

**Comment by simonhir** [comment]
## Bearbeitet:

- Systemüberblick -> Infrastruktur: Neuerstellt
- Systemüberblick -> Schnittstellen: Refactoring
- Regelbetrieb -> Monitoring/Alerting: Aufräumen erster Absatz
- Wartung -> Updates- und Releasewechsel -> Vorarbeiten: Change-Workflow ergänzt

**Comment by darenegade** [comment]
@simonhir Brauchst du hier noch Review bzw. kann/soll ich helfen, um das abzuschließen? (Weil in Review)

**Comment by simonhir** [comment]
@darenegade wäre super, wenn du einmal drüber schaust genau.
Bzw. falls du das im Rahmen der TODOs schon gemacht hast passt auch.
Dann gerne einfach schließen, wenn es passt.

**Comment by darenegade** [comment]
@simonhir Ich find es jetzt echt gut und aufgeräumt👍
