### ISSUE TITLE
Service Readme umsetzen

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1382]
**Is your feature request related to a problem? Please describe.**

Die in #1383 erstellten Readme-Templates müssen für alle Service erstellt werden, damit diese direkt im Code dokumentiert sind.
Dabei ist darauf zu achten, dass Informationen sinnvoll in die Readme ~~oder die öffentliche Dokumentation~~ verteilt und verlinkt sind.

**Describe the solution you'd like**

Readme für alle Services anlegen. Positioniert sollen diese immer im übergeordneten Ordner und nicht direkt im `service`-Paket werden.
Bei Integrationen ist besonders darauf zu achten, dass technische Informationen aus https://digiwf.oss.muenchen.de/integrations/ in die Readme verschoben ~~und Modellierungs-Informationen in die Modellierungs-Doku mit dem ebenfalls erstellen Templates verschoben~~ werden.

**Describe alternatives you've considered**

- Dokumentation wie aktuell weiter führen: Problem: gemischte technische und Modellierungs-Doku

**Acceptance Criteria**

- [ ] Für jeden Service im digiwf-core existiert eine README nach dem Template
~~- [ ] Der separate Punkt "Integrationen" in der öffentlichen Dokumentation existiert nicht mehr~~
~~- [ ] Für alle Integrationen existiert im Modellierungs-Teil der öffentlichen Dokumentation ein Eintrag entsprechend des zugehörigen Templates~~
- [ ] Die öffentliche Integrations-Dokumentation verweis für technische Informationen nur noch auf die entsprechende README

**Additional context**

**Comment by markostreich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1382?planning-poker) with Zenhub @darenegade @lehju @simonhir

**Comment by markostreich** [comment]
### Integrationen
- [x] address-integration
- [x] alw-integration
- [x] cosys-integration
- [x] dms-integration
- [ ] email-integration
- [ ] example-integration
- [ ] okewo-integration
- [ ] openai-integration
- [ ] s3-integration
- [ ] ticket-integration

**Comment by markostreich** [comment]
Das Ticket wird wegen Abbruch des Projektes geschlossen.

Die Integrationen werden/wurden im RefArch-Projekt dokumentiert, soweit sie dorthin übernommen werden.
