### ISSUE TITLE
Template Readme und Modellierung

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1383]
**Is your feature request related to a problem? Please describe.**

Als Entwickler möchte ich eine einheitliche Readme für alle Komponenten für einen schnellen Überblick über die Beschreibung der Komponente und ihre Parameter nutzen können, um mich schneller zurecht zu finden.
Als Prozessdesigner möchte ich übersichtlich einsehen, welche Funktionen von welchen Integrationen zur Verfügung stehen und wie diese korrekt integriert werden können.

**Describe the solution you'd like**

Für eine Integration wird eine Readme beispielhaft erstellt, die an Blaupause für alle weiteren Komponenten (Integrationnen und Services) genutzt werden kann.
Die Readme enthalt eine Beschreibung der Komponente und der Konfigurationsparameter.
Bei Integrationen ist besonders darauf zu achten, dass technische Informationen aus https://digiwf.oss.muenchen.de/integrations/ in die Readme verschoben und Modellierungs-Informationen in die Modellierungs-Doku mit dem ebenfalls erstellen Templates verschoben werden.

README-Vorlage: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-rest-service/README.md

**Describe alternatives you've considered**

Es wird ein separates Template mit Beispielinhalten erstellt.

**Acceptance Criteria**

- [ ] Eine Dokumentation liegt an einer Komponente vor.
- [ ]  Für die Integration existiert im Modellierungs-Teil der öffentlichen Dokumentation ein Eintrag entsprechend des zugehörigen Templates

**Additional context**

**Comment by simonhir** [comment]
Evtl kann auch direkt das Beispiel https://github.com/it-at-m/digiwf-cocreation/blob/47238746bd7e5ee90d26773f18ebaf37a9075ba5/digiwf-cocreation-deployment-service/README.md genutzt werden

**Comment by markostreich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1383?planning-poker) with Zenhub @darenegade @lehju @simonhir

**Comment by simonhir** [comment]
Only service README is updated. Existing integration docs in open source documentation stay at is except move of configuration in README.
