### ISSUE TITLE
Überarbeitung Testdokumentation

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1395]
**Is your feature request related to a problem? Please describe.**

Aktuell enthält die [Test-Dokumentation](https://confluence.muenchen.de/display/MPdZ/Cypress+Test-Dokumentation) viele doppelte Tests, welche bereits im Rahmen von anderen Tests abgedeckt sind. Außerdem ist die Reihenfolge der Tests nicht sehr sinnvoll.

**Describe the solution you'd like**

Überarbeitung der Testdokumentation:
- Verschieben in das Betriebshandbuch in verringerter Form (Stichpunktartig)
  - Nach Automatisierung der Testfälle mit Cypress werden diese aus dem Betriebshandbuch entfernt
- Sortierung nach Priorität der Funktionalität bzw. Aussagekraft des Testfalls
- Entfernen von doppelten Tests, welche bereits in anderen Testfällen enthalten sind

**Describe alternatives you've considered**

Keine Alternative

**Acceptance Criteria**

- [x] Die Testdokumentation wurde in das Betriebshandbuch verschoben
- [x] Funktionen werden (wenn möglich) nur einmalig getestet
- [x] Die Reihenfolge der Testfälle entspricht ihrer Aussagekraft bzw. Priorität

**Additional context**

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1395?planning-poker) with Zenhub @lehju @simonhir
