### ISSUE TITLE
Überarbeitung Testautomatisierung

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1396]
**Is your feature request related to a problem? Please describe.**

Aktuell laufen die Cypress Tests in der [internen CI](https://git.muenchen.de/digitalisierung/digiwf-core/-/pipelines/304600) nicht zuverlässig und einige der Tests haben keine wirkliche Priorität.
Eine Neupriorisierung der Tests findet mit #1395 statt.
Im Rahmen dieses Issues sollen die aktuellen Tests stabilisiert oder ersetzt werden.

**Describe the solution you'd like**

- Implementierung des höchst priorisierten Tests aus der Testdokumentation
  - Implementierte Testfälle bzw. Schritte werden aus der Testdokumentation entfernt
- Stabilisierung bzw. ausbauen der existierenden Tests
    - Unnötige/instabile Tests auch gerne erstmal löschen/deaktivieren 
- Aufräumen der CSS-Queries:
  - Aufwendige bzw. "unsaubere" Queries ersetzen durch hinzufügen neuer CSS-Attribute im Frontend
     - Als data-attribute, siehe https://docs.cypress.io/guides/references/best-practices#Selecting-Elements 

**Describe alternatives you've considered**

Keine Alternative

**Acceptance Criteria**

- [x] Die GitLab-CI für die Cypress Tests läuft stabil erfolgreich
- [x] Der höchst priorisierte Testfall aus der Test-Dokumentation ist in Cypress implementiert
- [x] Es werden nur sinnvolle CSS-Queries verwendet
- [x] Es wird über fehlschlagende Pipelines informiert
- [x] Tickets für andere Testfälle sind erstellt

**Additional context**

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1396?planning-poker) with Zenhub @lehju @simonhir
