### ISSUE TITLE
Disable cookies for clients and public routes

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1397]
**Describe the bug**

When using the `/clients` or `/public` gateway routes you still get cookies set which is not required for both.

**To Reproduce**

- Call a `/clients`-Route (i.e. `/clients/digitalwf-backend-service/rest`) or `/public`-Route
- You get a `Set-Cookie`-header back with the auth and/or csrf cookie contained

**Expected behavior**

You can call both routes as before but there is no csrf or auth cookie set

**Screenshots**

<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9qQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--241318380beec3d06da56396acfdbe56d5a6fed2/image.png" alt="image.png" />

**Additional context**
- Internal docs: https://git.muenchen.de/ccse/refarch-security/-/wikis/vorgaben/kommunikation#2-aufrufe-aus-anderen-anwendungen-immer-%C3%BCber-das-api-gateway

**Comment by darenegade** [comment]
Das scheint aktuell nicht umsetzbar:

https://github.com/spring-projects/spring-security/issues/6552

https://stackoverflow.com/questions/56056404/disable-websession-creation-when-using-spring-security-with-spring-webflux/67005365#67005365

**Comment by simonhir** [comment]
Will be done within https://github.com/it-at-m/refarch/issues/135
