### ISSUE TITLE
S3 Upload add Header Consistency-Control: strong-global

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1407]
**Is your feature request related to a problem? Please describe.**

Als Sachbearbeiter möchte ich, dass ich in einem mir zugewiesenen Vorgang auf zugehörige Dateien, die im S3-Storage gespeichert sind, jederzeit, vollständig zugreifen kann.
Es ist im S3-Storage der LHM vorgekommen, dass sich S3-Nodes nach 2 Tagen noch nicht synchronisiert hatten (Amazon garantiert eine vollständige Synchronisiation nur innerhalb von **15 Tagen**), weswegen es vorkommen kann, dass Dateien in UserTasks nicht angezeigt werden bzw. nach einem Reload andere als vorher angezeigt werden.
Laut Kollegen vom S3-Team kann man eine schnellere Synchronisation forcieren, indem man beim Upload den Http-Header `Consistency-Control: strong-global` mitschickt.
Allerdings ist die Wirksamkeit dieser Lösung für uns schwer überprüfbar.

**Describe the solution you'd like**

Einbau des Http-Headers `Consistency-Control: strong-global` in den Dateiupload.

**Describe alternatives you've considered**

a) Vielleicht ist es möglich einzurichten, dass der Node, auf den Hochgeladen wird, der ist, von dem später abgefragt wird.
b) Sachbearbeiter warten im zweifel mehrere Tage, bevor sie eine neue Aufgabe mit Dateinen vom S3 bearbeiten.

**Acceptance Criteria**

- [ ] Http-Header `Consistency-Control: strong-global` ist in den Dateiupload eingebaut und wird mit versandt.
- [ ] Dateien sind im Vorgang jederzeit und vollständig verfügbar.

**Additional context**

Test auf dem S3-Storage mit WinSCP. Bereits die übergeordneten Ordner ließen sich vor der vollständigen Synchronisiation nicht permanent abrufen:
<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bfa5bdaecd83c9707b9448e3e70422e9da831f5/Ordner_1.JPG" alt="Ordner_1.JPG" />
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbfa872d5b3900cb41a840ecc4e2c090f583a0dd/Ordner_2.JPG" alt="Ordner_2.JPG" />

**Comment by darenegade** [comment]
https://aws.amazon.com/de/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

https://aws.amazon.com/de/s3/consistency/

Für MinIO: https://blog.min.io/strict-consistency-hard-requirement-for-primary-storage/

Hier noch ein Hinweis von zur Umsetzung:
https://github.com/minio/minio/blob/master/docs/distributed/README.md#consistency-guarantees

**Comment by darenegade** [comment]
@markostreich hab Refinement mal entfernt, da aktuell noch unklar, ob Lösung wirklich so richtig
