### ISSUE TITLE
Report connector topic doesn't exist

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1415]
**Describe the bug**

Currently when a message is tried to send via the connector to a non existing topic the connector tries to create the topic which it isn't allowed to. That leads to a huge amount of logs and in the process it's not visible that the message couldn't be send.
Locally the topic is created and the message is sent to a dead topic.

**To Reproduce**
- Send a message to a non existing topic

**Expected behavior**
- The error is displayed in the process instance

**Acceptance criteria**

- [x] Connector throws exception if target topic doesn't exist instead of trying to create it
- [ ] ~~The exception is visible in the process~~
- [x] The message-lib is configured to not try to create non existing topics

**Additional context**

**Comment by simonhir** [comment]
With https://github.com/it-at-m/digiwf-core/pull/1418/files#diff-acfef207e0ed523421020b3a06d25ee8bc75557a21ec2e5beba5281427e521c8R56-R57 each exception is reported back to the process.
Only thing here is to check the behavior when a topic doesn't exist.

**Comment by darenegade** [comment]
I would assume that the behavior can be adjusted via a configuration

**Comment by darenegade** [comment]
> spring.cloud.stream.kafka.binder.autoCreateTopics

Default is `true`

https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka-binder/config-options.html
