### ISSUE TITLE
Konzept: Legacy Schema Migration

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#142]
**Is your feature request related to a problem? Please describe.**
Der Umbau des Taskmanagement ist eine Chance Alt-Lasten loszuwerden. Dies betrifft z.B. das alte JSON schema

**Describe the solution you'd like**
Wir brauchen ein Migrationskonzept für die Umstellung des alten Schemas auf das Neue, idealerweise ohne manuelle Tätigkeiten durch die Prozessowner. Dazu müsste man beide Schemas vergleichen und ein Konzept zur Migration entwickeln

**Describe alternatives you've considered**
Manuelle Umstellung der Prozesse durch Prozessowner

**Additional context**
Die Umstellung des Taskmanagement erfolgt bis Ende März. Bis dahin wird dies benötigt, damit die Umstellung reibungslos verläuft

**Comment by darenegade** [comment]
@dominikhorn93 Kannst du dir das Thema vielleicht mal anschauen? Ich hab die Befürchtung, dass wir hier nicht bis März warten können

**Comment by dominikhorn93** [comment]
Fehlende Felder:
- BaseAlwDocumentInput
- BaseDocumentInput

Als Test können die Soz / Kvr Formulare genommen werden.
Es sollte noch evaluiert werden ob wir eine manuelle Migration oder eine automatische machen.

**Comment by dominikhorn93** [comment]
Wie werden Daten mit den "alten" Formularen in der Engine gespeichert?
Ist die Speicherung mit der neuen Formulartechnologie kompatibel?

**Comment by LenaB34** [comment]
Dokumentation & ein Thema zum Test stehen noch aus.

**Comment by darenegade** [comment]
Es gibt hier konkret ein internes Ticket dazu, dass die Migration schon fordert: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/263

**Comment by dominikhorn93** [comment]
![image.png](https://images.zenhubusercontent.com/6220ff5903760220e5b648bb/3e7523b9-a64d-4f45-8761-5e2a9f9fa73c)

**Comment by darenegade** [comment]
@dominikhorn93 FYI: Für eine kurze Zeit ist ein Parallelbetrieb geplant. Je nach Prozesslaufzeit könnte man so auch mit Altlasten eventuell umgehen.

**Comment by dominikhorn93** [comment]
Aufgaben:
- Fehlende Formularfelder in neuer Version bereitstellen
- Adminprozess für "Objekt 2 Json" Migrationen bereitstellen (ProzessKey + Variablennamen)
- "Usertask abbrechen" als Funktion bereitstellen
- Migrationsanleitung für "Statusdokument generieren" bereitstellen
- Mapping Funktionen auf JSON migrieren
  - SaveSchriftstueckeEndListener
  - KvrDmsFunctions
  - DmsUtils löschen, wurden nie verwendet

@darenegade ist heute noch ein bisschen etwas hochgekommen, das wir einplanen müssen. Zu dem Parallelbetrieb hab ich ein paar Fragen.
Für die Dinge die schon gehen, würde ich den Migrationsguide fertig schreiben.
Für alles andere lasse ich dann tbd. drin.

**Comment by dominikhorn93** [comment]
Die Aufgaben legen wir dann am besten gemeinsam an.

**Comment by darenegade** [comment]
@dominikhorn93 macht eine Story auf für das Doing bzw. die Test-Migration der Spontanmeldung
Das Konzept ist Done
