### ISSUE TITLE
DMS Integration supports domain specific S3 storages

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#1441]
**Is your feature request related to a problem? Please describe.**

The dms integration is not supporting domain specific s3 storages.

**Describe the solution you'd like**

Add domain specfic s3 storage support to the dms integration in [S3Adapter](https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-dms-integration/digiwf-dms-integration-core/src/main/java/de/muenchen/oss/digiwf/dms/integration/adapter/out/s3/S3Adapter.java).
The domain specfic s3 storage is usually configured with the process config.

**Acceptance Criteria**

- [ ] dms integration supports domain specific s3 storages

**Additional context**

It's also possible to create a S3Adapter Lib and use it in dms integration https://github.com/it-at-m/digiwf-core/issues/1442

**Comment by simonhir** [comment]
Should be done within #1442

**Comment by darenegade** [comment]
Duplikat zu #735
