### ISSUE TITLE
Move duplicate s3 logic to client libs

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#1442]
**Is your feature request related to a problem? Please describe.**

In the past we created presigned urls asynchronously with the s3 integration and passed them to the integration.
With the dms and zammad integration we changed that concept: The integrations now get the filepath in s3 storage and the integrations synchronously create presigned urls.

With the new concept we create for each integration new S3Adapters with very similar functionalities.

**Describe the solution you'd like**

The duplicate s3 logic should be correctly moved to the corresponding client libs.
This includes following logic:
- Filetype validation
- Domain specific s3 storage

**Acceptance Criteria**

- [x] Support Filetype validation/filtering via s3 client lib
- [x] Support direct get of domain specific s3 via process config client lib
- [x] The key for the domain specific s3 in the process config is only defined in the library

**References**
- i.e. split up https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-ticket-integration/digiwf-ticket-integration-core/src/main/java/de/muenchen/oss/digiwf/ticket/integration/adapter/out/s3/S3Adapter.java

**Comment by markostreich** [comment]
MR für das Ops-Repo https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/447

**Comment by markostreich** [comment]
Leider gibt es noch einen Fehler in der Engine entdeckt. Die `S3Configuration` wird nicht rechtzeitig getriggert, sodass die Default-Implementierung startet und die Engine keine domain spezifischen S3 URLs zurückgibt.
