### ISSUE TITLE
Prüfung der Gesamtgröße bei der Verarbeitung von Dateien in Integrationen

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1457]
**Is your feature request related to a problem? Please describe.**

Als Administrator und als Prozessdesigner möchte ich, dass Fehler, die aufgrund von zu hohen Dateigrößen auftreten, abgefangen und einer Fehlerbehandlung unterworfen werden können. Derzeit kommt es bei Überschreiten einer nicht bestimmbaren Gesamtgröße der Dateien zu einem "out of memory"-Fehler, da alle Dateien zunächst als Batch in den Heap geladen werden.

**Describe the solution you'd like**

Dateien werden erst aus dem S3 abgeholt, wenn sichergestellt ist, dass es nicht zu einem "out of memory"-Fehler kommt.

Die Gesamtgröße der Dateien wird vorher überprüft. Wenn eine konfigurierte Grenze überschritten wird, werden keine Dateien in den Heap geladen und es wird ein BpmnError ausgelöst. Dateien, die alleine schon eine konfigurierte Größe überschreiten, werden von der Integration abgelehnt, und es wird ein BpmnError ausgelöst.

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] Dateien, die eine konfigurierte Größe bereits einzeln überschreiten, werden abgelehnt und es wird ein BpmnError geworfen. Die Prüfung wird über die S3-Client-Library geregelt.
- [x] Es wird verhindert, dass ein Upload startet, wenn nicht alle Dateien die geforderte Maximalgröße unterschreiten.
- [x] Es wird verhindert, dass ein Upload startet, wenn die Gesamtgröße der Dateien eine geforderte Maximalgröße überschreitet.
- [x] Es gibt in DigiWF ein Limit, das für Datenspeicher ein Limit für Dateigrößen festsetzt. (Z. B. 100 MB) Es wird dafür eine neue Property der S3-Integration genutzt.
- ~~Parallele Message Verabeitung bei den Integrationen, die Dateien verarbeiten wird durch sequenzielle Verabeitung ersetzt. Idealerweise Einschränkung nur beim Consumer, der Dateien verarbeitet.~~

**Additional context**

Betroffene Integrationen:

- DMS-Integration
- Cosys-Integration
- Ticket-Integration

**Comment by simonhir** [comment]
Sollte man vrmtl. zusammen mit #1442 umsetzen.

**Comment by markostreich** [comment]
Evtl. TotatSize im Frontend mit setzen

**Comment by markostreich** [comment]
Die Beschreibung wurde angepasst. Die Userstory entsprach noch nicht der im Planing besprochenen Lösung.
