### ISSUE TITLE
Security lib multi realm support

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1459]
**Is your feature request related to a problem? Please describe.**

Currently the security lib does only support one client. In some scenarios external services are on different realms than DigiWF itself. Examples for this are dev, test environments and the cosys integration.

**Describe the solution you'd like**

Add support for multiple realms to digiwf-sring-security library. Update the cosys-integration to use updated security-lib also for outgoing request (Currently custom implementation is used).

**Describe alternatives you've considered**

Don't implement: integrations with other realm do not run on dev, test or custom implementation in integrations.

**Acceptance Criteria**

- [ ] Security lib supports multiple different realms
- [ ] All existing integration still work with the security lib
- [ ] DigiWF-Ops is updated if needed
- [ ] Cosys-Integration uses security lib for outgoing requests
- [ ] Zammad-Integration uses security lib for outgoing requests

**Additional context**

**Comment by darenegade** [comment]
Aus Diskussion in Zammad

> Grundsätzlich sehe ich die digiwf-security Lib eher für Vereinfachung für DigiWF interne Kommunikation. Nach außen müssen wir immer flexibel und wahrscheinlich auch individuell bleiben.

**Comment by simonhir** [comment]
Ja hast recht, dachte bei der Ticket-Integration ist das einiges an Code, aber ist gar nicht so
