### ISSUE TITLE
Es werden nicht mehr alle Vorgänge unter "Aktuelle Vorgänge" angezeigt

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#146]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/240

-------------

Eventuell ist das der gleiche Bug, wie: https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/525

**Comment by dominikhorn93** [comment]
@StephanStrehlerCGI war das auch das mit der Pagination

**Comment by LenaB34** [comment]
gleiche Bug, wie: https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/525
