### ISSUE TITLE
Cleanup integration architecture

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1463]
**Is your feature request related to a problem? Please describe.**

As a developer i want that all integrations match the in the ADRs defined architecture.

**Describe the solution you'd like**

Refactor all integrations to match defined architecture:
- Correct naming conventions for classes: `InPort, OutPort, UseCase`
- Correct concerns in core and starter packages:
  - `@Bean, @Configuration, @Component, ...` only in core application dir oder starter package
- Correct usage of Process and ErrorApi for bpmn-errors, incidents and correlation

**Acceptance Criteria**

- [x] Naming conventions for all classes are correct for all integrations
- [x] Separation of concerns within core and starter package are correct for all integrations
- [x] The Example-Integrations implements the usage of the ErrorApi and ProcessApi as out adapter

**Additional context**

- https://digiwf.oss.muenchen.de/documentation/architecture/adr/adr003-use-hexagonal-architecture.html
- https://digiwf.oss.muenchen.de/documentation/architecture/adr/adr004-hexagonal-architecture-packages.html

**Comment by markostreich** [comment]
### Integrationstests

- [x] DMS-Integration
- [x] S3-Integration
- [x] Adress-Integration (siehe nächster Kommentar)
- [x] Cosys-Integration (Fehler: siehe unten)
- [x] E-Mail-Integration
~~- [ ] EWO-Integration~~
- [x] Ticket-Integration

**Comment by markostreich** [comment]
### Fehler Adress-Integration

Wahrscheinlich konnte der Adress-Service nicht erreicht werden, aber in der Folge:

`Cannot create incident for processinstance id bfeb6ae7-f8f0-11ee-991f-0a580a8a3b86 and type header searchAddressesGermany`

**Comment by markostreich** [comment]
@simonhir cosys-integration scheint einen Fehler zu haben:
Caused by: java.lang.IllegalArgumentException: Failed to lookup function to route to based on the expression 'headers['type']' which resolved to 'createCosysDocument' function definition.

Der Gegentest auf processestest hat dagegen funktioniert.

**Comment by markostreich** [comment]
Der Fehler an der Cosys-Integration ist behoben und erfolgreich nachgetestet.

**Comment by markostreich** [comment]
Adress-Integration erfolgreich getestet.
