### ISSUE TITLE
Setup ArchUnit

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1465]
**Is your feature request related to a problem? Please describe.**

As a developer i want that the complete code complies with the ADRs. In specific i want that naming conventions, package structure is correctly used.

**Describe the solution you'd like**

- Setup ArchUnit tests
  - Need to be discussed where the tests should go
- Implement ADRs as ArchUnit tests (i.e. integrations hexagonal architecture and naming conventions)

**Describe alternatives you've considered**

- The code architecture is not checked and is not correctly implementing all ADRs

**Acceptance Criteria**

- [x] It is defined where which ArchUnit tests should go
- [x] ArchUnit verifies integration architecture, i.e.:
  - Package concerns
  - Naming conventions

**Additional context**

- https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-libs/digiwf-testing/digiwf-unit-test/src/main/java/de/muenchen/oss/digiwf/archunit

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/1465?planning-poker) with Zenhub @lehju @markostreich @simonhir
