### ISSUE TITLE
Optional Group wird nicht als Pflichtfeld markiert

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1494]
**Describe the bug**
Optional Group wird nicht als Pflichtfeld markiert

**To Reproduce**
1. Formular mit Optional Group
2.  Darstellung in Form als nicht Pflichtfeld, obwohl es Pflichtfeld ist

**Screenshot**
<img width="1095" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ozQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8dcf1d23f357024eee05458c200ea9cae272b54/image.png" alt="image.png" />

**Expected behavior**
otes Sternchen und Aria-Label bei Optional

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/450#note_765418

**Comment by markostreich** [comment]
Integrationstest erfolgreich
