### ISSUE TITLE
Maven Release ohne Services

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1504]
**Is your feature request related to a problem? Please describe.**

Als Technical Manager möchte ich nur die Artefakte im öffentlichen Maven veröffentlichen, die nicht spezifisch zur Integration in der LHM-Infrastruktur gehören, damit Releases nicht unnötig groß sind und schneller durchlaufen

**Describe the solution you'd like**

Zum Maven Release sollen keine Services mehr gehören.

**Describe alternatives you've considered**

Es werden weiter alle Services deployt.

**Acceptance Criteria**

- [x] Services sind aus dem Maven Release ausgeklammert.
- [x] DigiWF Releases funktionieren einschließlich Maven Release

**Additional context**

**Comment by simonhir** [comment]
@markostreich das sollte mit dem Wechsel auf Central Portal ja erledigt sein oder?

Siehe https://github.com/it-at-m/digiwf-core/pull/1492/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R304-R331

**Comment by markostreich** [comment]
Ja, ist erledigt.
