### ISSUE TITLE
Image in new mail template wrong ratio

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1547]
**Describe the bug**
A email sent with the new message template via the email integration shows the header image as 1:1 ratio instead of the original ratio. This bug only seems to occur in Outlook, Mailhog and OWA shows the image correct.

<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0k0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--585ca43ea48c442615d9024856c24803e1c11509/image.png" alt="image.png" />

**To Reproduce**
Send email with `email-with-logo` example process.

**Expected behavior**
The image is shown in its original ratio as in normal web browsers.

**Additional context**
- New email template introduced with #1277

**Comment by markostreich** [comment]
Integrationstest erfolgreich.
