### ISSUE TITLE
Update prod elasticsearch to 17.7

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1569]
Currently the prod elasticsearch is still on version 7.15 and this version will soon no longer be supported internally. All other elasticsearchs are already at version 7.17.

**Describe the solution you'd like**

Upgrade prod elasticsearch to 7.17.

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] All elasticsearch servers are at version 7.17
- [x] Optimize prod running without problems

**Additional context**

**Comment by markostreich** [comment]
Auftrag läuft: RITM0725013
Sollte am 26.4.24 um 15 Uhr durchgeführt werden.
