### ISSUE TITLE
Prozess-Deployment gibt im Fehlerfall keine Fehlermeldung zurück

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1581]
**Describe the bug**
Wenn ein Deployment nicht gelingt, weil z. B.  eine Prozessdefinition nicht valide ist, sollte  dem Benutzer in der CoCreation eine Fehlermeldung zurückgegeben werden. Momentan, sehen Anwender aber nur dauerhafte In-Progress-Kreisel.

**To Reproduce**
1. Erstelle eine defekte BPMN-Datei
2. Deploye sie.
3. => Dauerhafter In-Progress-Kreisel

**Expected behavior**
Dem Anwender sollen, wie früher, Fehlermeldungen angezeigt werden.

**Screenshots**

**Additional context**
Evtl. kehren die Fehlermeldungen nicht über Kafka zurück.

**Comment by darenegade** [comment]
Dup #1559
