### ISSUE TITLE
Einrichtung Checkmk bis "Mitte Juni" 2024

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1590]
**Is your feature request related to a problem? Please describe.**

Als Technical Manager für DigiWF möchte ich auch nach der Abschaltung von Nagios über Monitoring meiner DigiWF-Umgebungen verfügen können.

**!!!Abschaltung von Nagios ist "Mitte Juni" 2024!!!**

**Describe the solution you'd like**

- Nagios wird durch Checkmk ersetzt. Dafür müssen den TMs Einblicke in die Zustände der DigiWF-Server ermöglicht werden Momentan sind in Checkmk noch nicht alle Server enthalten.
- Alerts müssen in Checkmk parallel zu Nagios eingerichtet werden.

**Describe alternatives you've considered**

Keine.

**Acceptance Criteria**

- [x] Alle DigiWF-Server sind in Checkmk einsehbar. Siehe RITM0722732
- [x] Benachrichtigungen sind äquivalent zu Nagios eingerichtet. (via KM8-Webex channel)

**Additional context**

**Comment by markostreich** [comment]
Antwort IBS442:
"Die Server zum Service DigiWF sind nun für euch "KM822" sichtbar und auch eine Hostgroup "digiwf" existiert nun. Wer was in Checkmk sehen kann liegt wieder an den Kontaktgruppen. Bei einer Serverbestellung passiert das bereits automatisch, dass wir uns die OU vom Manager der Freigabegruppe holen. Hier gibt es auch schon eine Story, damit hier gleich alle OUs der Gruppenmitglieder uns mitgeteilt werden. Damit wir dann in Zukunft nicht für jeden Service eine eigene Hostgroup anlegen müssen, möchten wir eigentlich die Services als Label an die Hosts pinnen. Dauert aber leider noch. Damit kannst du dann aber auch wieder filtern etc."

**Comment by simonhir** [comment]
@markostreich eigentlich ist das durch die Benachrichtigungen im KM8-Chanel erledigt oder sollen wir das nochmal explizit für unseren Chanel einrichten?
