### ISSUE TITLE
Implement Error Handling for digiwf-verification

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#163]
**Aufgabe**

- Integration refactoren, um digiwf-message lib verwenden
- Fachliche Fehler definieren und dokumentieren (in https://digiwf.oss.muenchen.de/integrations/)
- Fachliche Fehler in der Integration werfen
- Error Handling implementieren
- Example Prozess erstellen

**Comment by darenegade** [comment]
Die Integration ist aktuell kein Teil von DigiWF, daher ins zug. Repo verschoben

**Comment by darenegade** [comment]
Verification Artifact wird entfernt
