### ISSUE TITLE
Multi-File-Input Validierung schlägt fehl bei Upload-Abbruch

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1631]
**Describe the bug**

Wenn man den Datei-Upload bei weiteren Files abbricht bei einem MFI als Pflichtfeld, dann wird die Validierung des Inputs auf "Dies ist ein Pflichtfeld" gestellt, selbst wenn bereits eine Datei hochgeladen ist. 

**To Reproduce**
1. Form erstellen mit MFI als Pflichtfeld und in Test-Prozess einbetten als Start-Form
2. Eine Datei hochladen in den MFI
3. Nochmal in das Feld Klicken und dann Datei-Auswahl abbrechen
4. Feld geht auf Fehler

**Expected behavior**
Feld zeigt keinen Fehler an wenn Validierung passen sollte

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf/digiwf-support/-/issues/459

**Comment by lehju** [comment]
Ich konnte den Fehler weder lokal noch in einer Umgebung nachstellen.

**Comment by darenegade** [comment]
@lehju Hast du es am FKZ probiert? Dort kann ich es gut nachstellen. Im internen Ticket ist gut beschrieben, wie es geht.

**Comment by lehju** [comment]
@darenegade ich konnte das Problem jetzt nachstellen. In Firefox funktioniert es wie gewünscht aber in Chrome kommt die Fehlermeldung.
