### ISSUE TITLE
Impement error handling for digiwf-cosys-integration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#165]
**Aufgabe**

- Integration refactoren, um digiwf-message lib verwenden
- Fachliche Fehler definieren und dokumentieren (in https://digiwf.oss.muenchen.de/integrations/)
- Fachliche Fehler in der Integration werfen
- Error Handling implementieren
- Example Prozess erstellen
- Bugfix: https://github.com/it-at-m/digiwf-core/issues/165#issuecomment-1452068828

**Comment by darenegade** [comment]
Eventuell kann das hier gleich mitgemacht werden:

https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/544

**Comment by lmoesle** [comment]
> Eventuell kann das hier gleich mitgemacht werden:
> 
> https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/544

Die Cosys Integration behandelt wohl keine HTTP Fehler (Status 4XX und 5XX). Für bekannte 4XX Fehler sollten Technical Errors definiert werden. Für 5XX Fehler sollte ein Incident getriggert werden (bzw. falls Cosys das HTTP Protokoll unsauber implementiert sollten hier ebenfalls Technical Errors definiert werden).

**Comment by lmoesle** [comment]
The API is generated by the OpenAPI Maven Generator:
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-cosys-integration/digiwf-cosys-integration-client/pom.xml#L99

Here is the missing errorhandling:
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-cosys-integration/digiwf-cosys-integration-client/src/main/java/io/muenchendigital/digiwf/cosys/integration/gen/api/GenerationApi.java#L162

There should be some `onStatus` Handlers before `bodyToMono(..)`

Es muss eine andere Methode verwendet werden: `generatePdfWithResponseSpec`

Siehe: https://github.com/OpenAPITools/openapi-generator/pull/12843

Comment from @darenegade in https://github.com/it-at-m/digiwf-project/issues/544

**Comment by lmoesle** [comment]
**Mögliche fachliche Fehler**

| Error Code | Error Message | Beschreibung | Handlungsempfehlung |  
|---------------------------|------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|  
| `VALIDATION_ERROR` | Fehlermeldung der auftretenden `ValidationException` | Die übergebenen Daten sind nicht valide. | Korrigieren Sie die Daten und versuchen es erneut |
| `S3_FILE_SAVE_ERROR` | tbd. | Die in Cosys erzeugte Datei kann nicht im S3 Storage gespeichert werden. Die übergebene Presigned Url ist fehlerhaft (nicht valide, abgelaufen, falsche Action). | tbd. |
| `COSYS_DOCUMENT_CREATION_FAILED` | tbd. | tbd. | tbd. |

**Comment by lmoesle** [comment]
**Technisch**

- [x] digiwf-message lib verwenden (http://localhost:8081/integrations/digiwf-mail-integration.html)
- [x] Aufräumen in der Cosys Integration (viele Standardfunktionalitäten kommen über die digiwf-message lib mit)
    - z.B. CosysIntegrationAutoconfiguration im Starter Modul
    - digiwf-spring-cloud-stream-utils durch digiwf-message lib ersetzen
- [x] Error Handling implementieren bzw. refactoren
- [x] Bugfix: https://github.com/it-at-m/digiwf-core/issues/165#issuecomment-1452068828
- [x] Doku ergänzen, um fachlichen Fehler

**Fachliche** 

- [x] Element Template mit Streaming TemplateV02 erstellen und bereitstellen
- [x] Beispielprozess erstellen (zum Testen)

Beispiel: Example Integration https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534/digiwf-integrations/digiwf-example-integration

Aktueller Code Branch epic/error-handling-and-refactoring-integrations https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534

Zum Testen kann die Example Integration: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-cosys-integration/digiwf-cosys-integration-example/src/main/java/io/muenchendigital/digiwf/cosys/integration/example/api/controller/ExampleController.java mit Postman verwendet werden
