### ISSUE TITLE
Implement error handling for s3-integration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#166]
**Aufgabe**

- [x] digiwf-spring-cloudstream-utils mit neuer digiwf-message lib ersetzen (siehe Doku custom-integration-service: https://github.com/it-at-m/digiwf-core/blob/epic/error-handling-and-refactoring-integrations-534/docs/src/integrations/guides/custom-integration-service.md)
- [x] Error Handling implementieren
- [x] Fachliche Fehler (BpmnErrors) werfen
- [x] Doku ergänzen, um fachlichen Fehler
- [x] Element Template mit Streaming TemplateV02 erstellen und bereitstellen
~~Beispielprozess erstellen~~

Beispiel: Example Integration https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534/digiwf-integrations/digiwf-example-integration

Aktueller Code Branch epic/error-handling-and-refactoring-integrations https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534

Zum Testen kann die Example Integration: https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller mit Postman verwendet werden

**Comment by lmoesle** [comment]
The s3 integrations dependencies are messed up. We should clean them up and remove unnecessary ones.

**Comment by lmoesle** [comment]
**Mögliche Fachliche Fehler**

| Error Code | Error Message | Beschreibung | Handlungsempfehlung |  
|---------------------------|------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|  
| `VALIDATION_ERROR` | Fehlermeldung der auftretenden `ValidationException` | Die übergebenen Daten sind nicht valide. | Korrigieren Sie die Daten und versuchen es erneut |
| `FILE_DOES_NOT_EXIST_ERROR` | tbd. | Die angeforderte Datei(en) existieren nicht und es können keine Presigned Urls erzeugt werden. Dieser Fall kann beim Datei (bzw. auch Ordner) lesen auftreten | tbd. |

**Comment by darenegade** [comment]
@zambrovski Das wäre auch ein gutes Thema für dich 😊

**Comment by lmoesle** [comment]
Um die S3 Integration lokal zu starten muss man:

- in der local-docker.env die ENVs `S3_BUCKETNAME`, `S3_ACCESSKEY` und `S3_SECRETKEY` setzen:
Einen S3 Bucket und Credentials muss man sich händisch in Minio anlegen. Unter http://localhost:9000 mit Minio Test1234 anmelden und da einen Bucket und Access Key anlegen (Es gibt schon ein Ticket, um das ggf. mal zu automatisieren: #276 ).
- Die S3 Integration muss man lokal aktuell noch mit den `local`.

**Comment by simonhir** [comment]
MR für Template: https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/44

**Comment by zambrovski** [comment]
Should we merge it?

**Comment by darenegade** [comment]
Yes, we can merge that and complete the remaining tests in test/demo
