### ISSUE TITLE
MFI File download broken

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1662]
**Is your feature request related to a problem? Please describe.**

Seit dem UI Refactoring ist der File-Download nicht mehr korrekt. Das File wird nicht mehr direkt heruntergeladen und erhält einen kryptischen Namen.

Der Fehler ist wohl hier passiert:
https://github.com/it-at-m/digiwf-core/commit/f9b3c4a9d3693347b19865ecf3fb73275476a5cc#diff-74e949fdaa839bba98b6509810efbdb54bdb05017462d74ef69aca6f92f54790L90

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf/digiwf-support/-/issues/461

**Comment by markostreich** [comment]
Integrationstest erfolgreich.
