### ISSUE TITLE
Delete Object(s) from S3

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1671]
**Is your feature request related to a problem? Please describe.**

If an external System, like DMS, is the main source for files, there is a need to delete Objects from the S3

**Describe the solution you'd like**

* New `Delete` function on S3 Integration
* Params: List of Path or Files; file context
* Important: Prevention of clearing S3 Storage completely has to be included

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] Its possible to delete an object or multiple objects with same path from s3 with CallActivity
- [x] feature is documented
- [x] element template is versioned (#1604) and integrated in BPM-Modeller
- [x] EL name: "S3: Dateien löschen"

**Additional context**

https://git.muenchen.de/digitalisierung/digiwf/digiwf-support/-/issues/465

https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

**Comment by darenegade** [comment]
Rückmeldung: "Das wird Mitte Juni benötigt"

Deswegen in den aktuellen Sprint verschoben. Ref kann im Daily erfolgen

**Comment by simonhir** [comment]
https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/86

**Comment by markostreich** [comment]
@simonhir 
Im Support-Ticket wurde noch ein Fehler gemeldet. Bis geprüft ist, ob es etwas mit der Umsetzung zu tun hat oder ein Problem der Prozessdefinition ist, mache ich das Ticket nochmals auf.

**Comment by simonhir** [comment]
Bug fixed with #1801
