### ISSUE TITLE
Anpassung Fabasoft-Integration (MUCS24) - Ende Juni 24

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1677]
**Is your feature request related to a problem? Please describe.**

Dieses Jahr kommt ein Update zur Fabasoft Schnittstelle. (MUCS24) Als Plattformbetreiber müssen wir uns an die neue Schnittstelle anbinden und die in DigiWF bereitgestellten Funktionen testen

**Describe the solution you'd like**

* Neue WSDL einbinden
* Änderungen prüfen
* Testen
* Ggfs. dokumentieren
* DMS-Integration und -EAI heben
* ALW-DMS-Integration mitheben und im Notfall splitten

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] MUCS24 Update verursacht keine Breaking Changes bei DigiWF

**Additional context**

* https://git.muenchen.de/digitalisierung/digiwf/digiwf-support/-/issues/466
* https://wilma.muenchen.de/workspaces/e-akte/apps/blog/e-akte-blog/view/a7f54e6f-29ba-454e-994f-bb6a0ef03d4c

**Comment by markostreich** [comment]
Ich habe die Information erhalten, dass es keine neue WSDL gibt.

**Comment by markostreich** [comment]
Unsere Anforderungen bzgl. E-Akte Rollen und Aktenplaneintrag für Schnittstellentests wurden dem E-Akte Testteam übergeben.
Zum derzeitigen Zeitpunkt wurde für uns noch nichts angelegt.

**Comment by markostreich** [comment]
Routen siehe: https://confluence.muenchen.de/pages/viewpage.action?pageId=414412189

**Comment by markostreich** [comment]
Anbindung vom Portal aus erfolgreich getestet. Die Umgebungen sind für die Tests der workflows freigegeben. (siehe Support-Ticket)
