### ISSUE TITLE
DMS Dokument anlegen - Schriftstueck COOs zurückgeben

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1704]
**Is your feature request related to a problem? Please describe.**

Als Prozessentwickler:in möchte ich beim Dokument anlegen mehrere Schriftstücke mit anlegen und anschließend das Ergebnis in einem DMS Input anzeigen können.
Da der DMS Input eine Liste von Schriftstück-COOs erwartet, kann ich dies nicht, weil ich nur die Dokument-COO habe.

**Describe the solution you'd like**

* Liste von Schriftstück-COOs soll zusätzlich als Out-Mapping bei Dokument-Anlegen zur Verfügung stehen
* DMS Integration muss Schriftstueck-COOs eventuell nachlesen

**Describe alternatives you've considered**

**Acceptance Criteria**

- [ ] Beim Dokument anlegen mit Schriftücken erhält man im Prozess auch die COOs der einzelnen Schriftsücke als JSON Array passend zum DMS-Input

**Additional context**

https://git.muenchen.de/digitalisierung/digiwf/digiwf-support/-/issues/468

**Comment by darenegade** [comment]
Das Thema sollte im Juni Sprint umgesetzt werden

**Comment by simonhir** [comment]
https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/87

**Comment by markostreich** [comment]
Für Integrationstest:
Mit MR Show Case anpassen, sodass Dokumente im DMS-Input angezeigt werden.

**Comment by markostreich** [comment]
Integrationstest erfolgreich.
