### ISSUE TITLE
Property mismatch in class CronJobConfiguration.java of digiwf-s3-integration-starter

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-core#1706]
**Describe the bug**

The `digiwf-s3-integration-starter` has an property mismatch in class `CronJobConfiguration.java`. To enable the cronjobs the propeties under `de.muenchen.oss.digiwf.s3.cronjob.cleanup` are expected. The properties under ``io.muenchendigital.digiwf.s3.cronjob.cleanup` are only used to define the cronjob intervall. 

https://github.com/it-at-m/digiwf-core/blob/fccc8eeb3b705064741f772cd3092b6393d33a11/digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-starter/src/main/java/de/muenchen/oss/digiwf/s3/integration/configuration/CronJobConfiguration.java#L15

![image](https://github.com/it-at-m/digiwf-core/assets/56300801/6a3b1ec0-9645-4d8d-a6af-8de7fa86e008)

**To Reproduce**
1. Define properties of `io.muenchendigital.digiwf.s3.cronjob.cleanup.expired-files` and `io.muenchendigital.digiwf.s3.cronjob.cleanup.unused-files`
2. Do not define properties of `de.muenchen.oss.digiwf.s3.cronjob.cleanup.expired-files` and `de.muenchen.oss.digiwf.s3.cronjob.cleanup.unused-files`
4. The cronjobs are not configurated because the `ConditionalOnProperty`-Annotation is not triggered.

**Expected behavior**

A definition of the properties under ``io.muenchendigital.digiwf.s3.cronjob.cleanup` should be sufficient .

**Screenshots**
n/a

**Comment by darenegade** [comment]
@markostreich @simonhir 

Hier sollten alle Properties umgestellt werden:

https://github.com/it-at-m/digiwf-core/blob/dev/docs/src/integrations/digiwf-s3-integration.md#konfiguration

**Comment by darenegade** [comment]
Es gibt noch einige Stellen, wo noch die alte Domain verwendet wird:

https://github.com/search?q=repo%3Ait-at-m%2Fdigiwf-core+io.muenchendigital&type=code&p=1

**Comment by darenegade** [comment]
@boal Wir werden das bei uns einplanen und umsetzen

**Comment by boal** [comment]
Beim client der s3 integration gibt es einen mismatch bei der Propertybenennung.

![image](https://github.com/it-at-m/digiwf-core/assets/56300801/5a316102-3613-479b-9a96-69832bf691d0)

versus

![image](https://github.com/it-at-m/digiwf-core/assets/56300801/4c9fe5dd-552c-4dcf-8664-0b9753ae167a)

**Comment by markostreich** [comment]
Die S3 Properties werden umbenannt, sodass sie ohne package-Namen mit `digiwf` beginnen.

**Comment by lehju** [comment]
Ops MR: https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/470
