### ISSUE TITLE
Integrations optional S3-Presign-URL

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1734]
**Is your feature request related to a problem? Please describe.**

As a process designer, I don't want to worry about S3 file handling in the process. For this reason, all integrations should access the S3 Int. directly, similar to the DMS Int.

**Describe the solution you'd like**

* Implement new function without S3 presigns for integrations
  * CoSys, Mail, Ticket
* Provide element templates
  * Lift version of ET
* Documentation
* Adapt test processes

**Describe alternatives you've considered**

* Keep S3 in Process -> Decoupling from S3 rather via adapter in integration than in BPMN processes 

**Acceptance Criteria**

- [x] Remove the need to Create S3-Presign-Urls in BPMN-Processes
- [x] Filehandling is documented 
- [x] No Breaking Change for S3 Usage

**Additional context**

**Comment by simonhir** [comment]
https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/93
https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/481
