### ISSUE TITLE
Einsparung technische Ressourcen für DigiWF

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1757]
**Is your feature request related to a problem? Please describe.**

Um Kosten zu sparen, möchte ich als Betreiber von DigiWF nur wirklich benötigte Ressourcen für Betrieb und Entwicklung bereit stellen.

**Describe the solution you'd like**

Zur Erreichung dieses Ziels werden nicht benötigte Umgebungen komplett abgebaut und in benötigten Umgebungen die Ressourcen soweit es sinnvoll ist herunterskaliert (Abschaffen redundanter Pods, Reduzieren von CPUs und Speicher).
Beim Abbau von Umgebungen muss zusätzlich der Abbau zugehöriger Datenbanken beauftragt werden.

**Describe alternatives you've considered**

**Acceptance Criteria**

_Abbau_
- [x] Abbau der Umgebung 'digiwf-lasttest'
  - [x] CAP
  - [x] Kafka
  - ~~[ ] S3~~ nicht vorhanden
  - [x] DBs: REQ0738333
  - [x] Vanity-Url
- [x] Abbau der Umgebung 'digiwf-processeshotfix'
  - [x] CAP
  - [x] Kafka
  - [x] S3
  - [x] DBs: REQ0738339, REQ0738341
  - [x] Vanity-Url
- [x] Abbau der Umgebungen 'digiwfcocreation-training' und 'digiwf-processestraining' 
  - [x] CAP
  - [x] Kafka
  - [x] S3
  - [x] DBs: REQ0738347
  - [x] Vanity-Url
~~- [ ] Reduzierung 'digiwfcocreation-dev/test' auf eine Umgebung~~ wird vorerst nicht umgesetzt
- [x] Ops-Repo ist jeweils angepasst. -> [digiwf-ops!474](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/474)
- [x] Dokumentation ist jeweils angepasst. (Ops-Repo und Betriebshandbuch)

_Ressourcen reduzieren_
- [x] digiwf-dev (CPU: 20, Speicher: 30Gi bzw. soweit sinnvoll reduzieren)
- [x] digiwf-test (CPU: 20, Speicher: 30Gi bzw. soweit sinnvoll reduzieren)
- [x] digiwf-demo (CPU: 30, Speicher: 45Gi bzw. soweit sinnvoll reduzieren)
- [x] digiwf-processestest (CPU: 30, Speicher: 45Gi bzw. soweit sinnvoll reduzieren)
- [x] digiwf-processesdemo (CPU: 30, Speiche: 45Gir bzw. soweit sinnvoll reduzieren)
- [x] digiwfcocreation-dev/test (CPU, Speicher, soweit sinnvoll, reduzieren)
- [x] digiwfcocreation-demo (CPU, Speicher, soweit sinnvoll, reduzieren)
- [x] digiwf-p (CPU: 30, Speicher: 45Gi bzw. soweit sinnvoll reduzieren)

**Additional context**

**Comment by markostreich** [comment]
Die Prozessdesigner haben dem Abbau der Umgebungen zugestimmt. Wir können es angehen.

**Comment by simonhir** [comment]
Internal CAP MR: [openshift/projects!561](https://git.muenchen.de/openshift/projects/-/merge_requests/561)
Internal Kafka MR: [openshift/kafka!25](https://git.muenchen.de/openshift/kafka/-/merge_requests/25)
