### ISSUE TITLE
RefArch Integrations

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1804]
**Is your feature request related to a problem? Please describe.**

In order to achieve better reusability, the integrations should also be able to be used outside DigiWF, for example in regular RefArch projects

**Describe the solution you'd like**

* New Github Repo 4 "RefArch-Integrations"
* Provide as Starter to be integrated in every RefArch-Backend
* Decoupling from DigiWF
  * Replace BPMN-Errors and Incidents
  * Rm custom S3-Config
* Documentation in READMEs

**Describe alternatives you've considered**

Provision as ready to be used Image or running service

**Acceptance Criteria**

- [ ] Integrations can be used for RefArch Projects

**Additional context**

**Comment by markostreich** [comment]
Wenn das Ticket startet, beginnen wir mit der S3-Integration, da sie noch von einem anderen Projekt genutzt wird.
Erstes Ziel ist das Abtrennen der Kafka-Schnittstelle, damit die Integration auch ohne Kafka verwendet werden kann.

Für weitere Integrationen wird auf die Entscheidung der Architekten gewartet, ob sie als Starter für die RefArch bereitgestellt werden sollen.

**Comment by markostreich** [comment]
Bei der Umsetzung müsste erwogen werden, ob es Sinn macht, in den UseCases und InPorts weiterhin `BpmnError` oder `IncidentError` zu werfen. Besser sollten integrationsspezifische Exceptions verwendet werden, die kein Camunda-Naming mehr haben.

**Comment by simonhir** [comment]
Is done within https://github.com/it-at-m/refarch/issues/122
