### ISSUE TITLE
Lokale Entwicklungsumgebung verbessern

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#182]
Todo

- Docker compose Setup
- Lokaler Keycloak

**Comment by lmoesle** [comment]
@StephanStrehlerCGI, @zambrovski Ich hab euch ein Ticket angelegt, damit auch im Board sichtbar wird woran ihr gerade arbeitet

**Comment by darenegade** [comment]
Epic ergänzt

**Comment by LenaB34** [comment]
Dokumentation steht noch aus. 
Termin zum parallelen Thema, Einstellung der Entwicklungsumgebung wird von Stephan eingestellt.

**Comment by zambrovski** [comment]
Das kann doch zu, oder?
