### ISSUE TITLE
VJSF 3 / JSON-Forms Test

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1835]
**Is your feature request related to a problem? Please describe.**

Es soll eine Entscheidungshilfe zwischen den Optionen VJSF-Hebung, Umstieg auf JSON-Forms oder Eigenentwicklung des Frontends bereit gestellt werden.

Maximalaufwand 2 PT

**Describe the solution you'd like**

- Projekt mit aktuellem VJSF und Vue.js aufsetzen
- Projekt mit JSON-Forms aufsetzen
- in beiden EOZF Formular einbinden
- Ergebnis: Einschätzung zu Aufwand EOZF mit einem der Frameworks umzusetzen und Einschätzung Reife der Frameworks

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] Einschätzung zu Aufwänden und Reifegrad liegt vor.

**Additional context**

**Comment by lehju** [comment]
**VJSF 3**
Die Änderungen, die für #943 und #1699 in VJSF gemacht wurden, müssen in VJSF 3 erneut angepasst werden. 
Es fehlen teilweise Aria-Label und Tabindex. Die Komponenten Array und Array mit Objekten müssen wieder komplett angepasst werden, da sie nicht mit Tabulator und Screenreader nutzbar sind.

**JSON-Forms**
Für JSON-Form müsste das Schema unterteilt werden, da es dort ein JSON Schema und ein UI Schema gibt (https://jsonforms.io/docs/#how-does-it-work). Beim Test konnte das in der Co-Creation erstellte Formular nicht direkt übernommen werden sondern musste aufgesplittet werden. Bei getesten Variante (Vue) fehlen teilweise Aria-Label und Tabindex.
