### ISSUE TITLE
Logo digiwf.oss.muenchen.de

### ISSUE THREAD

**Issue by klml** [it-at-m/digiwf-core#199]
**Is your feature request related to a problem? Please describe.**

Currently we have only the it@M logo on https://digiwf.oss.muenchen.de/

**Describe the solution you'd like**

There is a new (?) logo in our intranet workspace "DigiWF", lets us this

**Comment by lmoesle** [comment]
@klml could you please provide the image from the internal workspace and add it to the issue

**Comment by klml** [comment]
![preview-DigiWF-Logo_2 jpg-L](https://user-images.githubusercontent.com/295778/225325632-9fc551bd-3f90-4a34-8831-b63eb4d1bffa.jpg)

**Comment by lmoesle** [comment]
@klml I added the digiwf logo to our docs page (see https://digiwf.oss.muenchen.de/)
