### ISSUE TITLE
Dependabot configuration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#215]
**Is your feature request related to a problem? Please describe.**

Dependabot currently opens a lot of pull requests.

**Describe the solution you'd like**

We should configure dependabot to our needs.

**Comment by lmoesle** [comment]
- Interval: wöchentlich
- Dependabot für Java, Github Actions und docs page

**Comment by zambrovski** [comment]
Bei Java und GH Actions würde ich es gerne auf täglich belassen und kümmere mich gerne um updates.
