### ISSUE TITLE
Multi-File-Input Limits broken

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#224]
**Describe the bug**
One can Upload 19 Files as the limit of the Input is 10

Additional: It would be nice to make this configurable via form

**To Reproduce**
1. Go to Form with Multi-File-Input
2. Add 9 Files
3. Add 10 Files

**Expected behavior**
Limit is hard at 10

**Additional context**
Just blogs the function to Add
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-apps/packages/components/digiwf-multi-file-input/src/components/DwfMultiFileInput.vue#L110

**Comment by lmoesle** [comment]
> Additional: It would be nice to make this configurable via form

It's a bit confusing that the issue says the upload limit should be set to 10 and additionally make it configurable.

**Comment by darenegade** [comment]
There are two topics:

First the Bug: If we have a Limit, we should stick to it

Second: The Limit should be configurable, but that may not is Part of this Issue
