### ISSUE TITLE
Empty Fields are empty Strings

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#228]
**Describe the bug**
Empty Date-Fields are presented as empty Strings from Engine and therefor can't be saved within User-Task

**To Reproduce**
1. Create Form as User Task with Date Field
2. Start Process with empty Date and create user tast
3. Don't change data and try to complete user task

**Expected behavior**
Empty Dates should be not present or the backend should accept emtpy strings as empty dates

**Acceptance Criteria**

- [ ] Init. of Empty Fields with emtpy Strings is removed and deployed on all Envs

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/238
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/133
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/262

**Comment by lehju** [comment]
Wird in https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/227 mitbearbeitet.

**Comment by darenegade** [comment]
@dominikhorn93 erstellt Story für Wecheln zu Jackson

**Comment by dominikhorn93** [comment]
In Klärung mit Prozessmodellierer ob wir das wirklich noch brauchen.
Mit der anderen Library ist das leider auch nicht so einfach möglich.

**Comment by darenegade** [comment]
> ob wir das wirklich noch brauchen.

Was war "das" hier nochmal? Aus fachl. Sicht geht es ja hauptsächlich darum, dass man zwei bzw. drei Zustände repräsentieren muss.

1. Date gesetzt
2. Datum leer
3. Datum nicht gesetzt aber Pflichtfeld

@dominikhorn93 
Was soll mit den Prozessmodellierer nun geklärt werden? Dann könnte ich das auch übernehmen.

**Comment by dominikhorn93** [comment]
Bisher bei Clarissa um Klärung gebeten, ob die Initialisierung mit leeren Strings ausgebaut werden kann.

Diese wurde vor 2 Jahren eingebaut aufgrund:
- Modellierung im Prozess: leerer String einer Variable ist einfacher zu behandeln, als dass die Variable nicht vorhanden ist
- CoSys Dokument: leerer String ist einfacher zu behandeln, als dass die Variable nicht vorhanden ist


Auf beides sollten wir aus Plattform-Sicht die Antwort geben: Muss durch die Modellierung gelöst werden.
Bei uns entstehen sehr hohe Aufwände und Inkonsistenzen durch diesen Workarround.

Lösung:
- In CoSys kann man einen Wrapper schreiben, der damit umgehen kann
- Für Prozesse könnten wir eine Helper-Funktion bereitstellen, die mit nicht vorhanden Variablen besser umgehen kann

**Comment by dominikhorn93** [comment]
Nach Absprache mit Michael auf Ende Juli verschoben, da davor voraussichtlich keine Zeit für Testing der Prozesse ist. Dann können wir die Initialisierung der Daten entfernen und müssen den Bug hier nicht mit Workarrounds fixen.

**Comment by darenegade** [comment]
Wir haben die Freigabe den Init der Daten zu entfernen

**Comment by darenegade** [comment]
Release ist geblocked durch FKZ Prozess.

**Comment by darenegade** [comment]
Kann für den nächsten Release Ende Dez. wieder eingebaut werden: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/238#note_698214
