### ISSUE TITLE
Release docker images that work on macs with M1 Chip

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#234]
**Is your feature request related to a problem? Please describe.**

The digiwf docker images do not run on a macbook with a M1 chip.

**Describe the solution you'd like**

Adjust the release pipeline to build docker images for arm64 architectures

**Comment by lmoesle** [comment]
We should add `platforms: linux/amd64, linux/arm64/v8` to the docker/build-push-action in our `release.yml` and check if the java base image we use supports arm64 architectures

**Comment by StephanStrehlerCGI** [comment]
Wir bräuchten ein separaten Build von zusätzliche Docker images
