### ISSUE TITLE
Authorities from UserInfo missing

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#257]
With https://github.com/it-at-m/digiwf-core/pull/172 the loading of authorities from the User-Info Endpoint was accidentally removed. Therefore the deployment of Forms/Processes doesn't work as they need to be authorized with the Autority `BACKEND_DEPLOY_RESOURCE`

Internal: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/276

**Comment by dominikhorn93** [comment]
Fix ist gemacht.
Es fehlt noch ein Integrationstest.
Eventuell sollten wir lokal den keycloak auch so erweitern, dass er wie der bei der LHM tickt.

**Comment by dominikhorn93** [comment]
@zambrovski ich habe alles von der RefArch wieder mitreingenommen - inkl. Cache.
Eventuell hast du eine Idee wie das noch eleganter geht.
War heute nicht möglich zu prüfen, weil zeitkritisch...

**Comment by dominikhorn93** [comment]
Hier die PR dazu, die gemerged wird: https://github.com/it-at-m/digiwf-core/pull/256/files

**Comment by zambrovski** [comment]
Ich hab jetzt durchstudiert, was alles reingemergd ist. Die Anforderung ist nun klar (aus der RefArch), jedoch habe ich einige Kommentare und wir sollten die aus meiner Sicht auch addressieren. Dazu benötige ich allerdings einmal die Konfiguration des OAUth aus den Stages (mehr dazu im Daily).
