### ISSUE TITLE
Improve Minio dev setup

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#276]
**Is your feature request related to a problem? Please describe.**

Currently, you have to configure minio manually (web gui) by creating a new bucket, accesskey, secretkey, ... . After configuring minio you have to setup a custom env file containing your minio configs which you have to store locally.

* Goal: 
    * Auto Config Secret & Bucket in S3 Int
    * Add DigiWF-Bucket (`mc mb <some-bucket>`)

**Describe the solution you'd like**

It would be great if minio runs out of the box with litte or none configuration.

**Additional context**

- According to the docker docs (https://github.com/minio/minio/tree/master/docs/docker) it should be possible to setup custom access and secret keys
- It should be possible to run a setup a container that configures minio with the mc client (like this [stackoverflow posts](https://stackoverflow.com/a/66485256) suggests)

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/276?planning-poker) with Zenhub @darenegade @lehju @simonhir @StephanStrehlerCGI @AnHo314
