### ISSUE TITLE
Parallelbetrieb Taskliste

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#283]
Durch die Änderung der Task-UI<->Backend Schnittstelle wird ein Parallelbetrieb beider Varianten notwendig, um einen sanften Übergang hinzubekommen. 

### Migrationskonzept
1. Task-Copy
   Parallelbetrieb Engine weiter federführend. Task-Service hält Kopie. UI weiter auf Engine.
2. UI-Switch
    UI wird umgestellt auf Task-Service
3. Deaktivierung Task User in Engine
   Löschen der Assignees in der DB der Engine

### Umsetzung
Funktionen der Engine, die wir nicht rauslösen können/wollen in den Task-Service und daher über die UI auf die Engine stellen müssen:

* Prozessliste + - details
* Statusdokumente im Task
* usw.

* Button in der UI umsetzen, der die Variable steuert
* ApiGW steuert backendseitig den Switch über einen Cookie
    * Cookie wird über Konfig gesteuert auf der UI Route (CookieName: FEATURE_USE_TASK=TRUE)

Die API der UI lässt sich über einen Switch umstellen. Dieser Switch soll in der UI zur Verfügung gestellt werden. Default bei Mode 1 ist Off und bei Mode 2 ist er On

**Comment by darenegade** [comment]
Das genaue Konzept für die Umstellung soll im Ref. abgestimmt werden

**Comment by LenaB34** [comment]
Doku steht noch aus.
