### ISSUE TITLE
DigiWF-Seite nicht erreichbar - 400 bad request

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-core#312]

**Comment by Sbivvds241** [comment]
SNOW Incident INC0314885

**Comment by Sbivvds241** [comment]
![image.png](https://images.zenhubusercontent.com/63401ba6e2bfc664693abd3b/ad0312ed-b06a-4bab-abf9-87845ca30585)

**Comment by Sbivvds241** [comment]
vermutlich wird der request header zu groß wenn der User in sehr vielen AD-Gruppen ist

**Comment by darenegade** [comment]
Hier wird vermutlich ein zu großer Token erstellt, mit dem NGINX aufgrund der Header-Einschränkung auf 1KB nicht mehr umgehen mag. (zum Vergleich: Engine Backend hat 8KB)

Vermutung muss mit User verifiziert werden durch manuelle Erstellung eines Tokens.

Wenn das stimmt, dann setzen wir die Header-Size im NGINX hoch:
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size

**Comment by darenegade** [comment]
Test ist noch offen

**Comment by Sbivvds241** [comment]
https://github.com/it-at-m/digiwf-core/pull/316
