### ISSUE TITLE
Task-Listener bei Create Task

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#315]
**Is your feature request related to a problem? Please describe.**
Um die Task-User in Camunda "abschalten" zu können, müssen die User/Groups aus dem Assignment rausgenommen werden. Dies muss vor dem Anlegen/Verändern des Tasks in der DB erfolgen.

**Describe the solution you'd like**
Es soll in der Engine ein Listener auf Basis vom Polyflow-Collector erstellt/konfiguriert werden, der im Rahmen der Transaktion eines Tasks den User aus dem Task nimmt und stattdessen als Property setzt.

Properties: assignee, candidateUsers and candidateGroups

für den [Parallelbetrieb](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/283) muss dieser Listener 3 Modi konfigurierbar unterstützen:
* No (Listener ist nicht aktiv oder macht nichts mit dem Task)
* Copy (Kopiert den User auf die Prozess-Variablen, aber behält das Assignment)
* Copy&Delete ( Kopiert den User als Prozess-Variablenund löscht das Assignment am Task)

**Akzeptanzkriterien**
* Assignments können gesteuert werden anhand einer Konfiguration
* Assignments werden als Prozess-Variablen gesetzt
* Assignments werden im Mode Copy&Delete vor dem Speichern in der DB gelöscht
* Doku zum Ablauf und Verantwortlichkeiten der Komponenten als Seq.-Diagramm darstellen

**Additional context**
https://www.holunda.io/camunda-bpm-taskpool/snapshot/reference-guide/components/camunda-taskpool-collector.html#task-assignment 

https://www.holunda.io/camunda-bpm-taskpool/snapshot/reference-guide/components/camunda-taskpool-collector.html#event-collection

**Comment by darenegade** [comment]
Da das Ticket vorzeitig in den Sprint genommen wird, muss es noch nachgeschätzt werden.

**Comment by darenegade** [comment]
Update wird nicht supportet, daher rausgenommen

**Comment by zambrovski** [comment]
Was ich vergessen habe. Bei assign über die API und Auslösen des Assign listeners muss aktiv das Assign Command direkt zum Polyflow Core geschickt werden. 

Das werde ich noch bauen und einen ITEST aufbauen

**Comment by zambrovski** [comment]
Is fixed with #352
