### ISSUE TITLE
Task-Service: Cancel Tasks

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#317]
**Is your feature request related to a problem? Please describe.**
Der Task-Service muss eine Funktion bereitstellen, mit der Tasks abgebrochen werden können, damit.....

**Describe the solution you'd like**

#### Aktuelle Endpunkte an der Engine:

* /rest/task/cancel/{id}

#### Anforderungen

* Tasks können nur vom Assignee abgebrochen werden
* Engine bietet über Camunda bereits einen nativen HandleBPMNError-Endpunkt, der hier genutzt werden soll
     * Das Abbrechen eines Tasks löst in der Engine aktuell einen BPMN-Error aus mit "default_error_code". Dieser Code wird aber nicht weiter verwendet und ist nur notwendig, da ein Code angegeben werden muss
* Im Task-Service löst das Abbrechen nicht direkt aus. Dieser leitet den Aufruf weiter, wenn der User die Berechtigung hat.
    * Hierzu muss der Endpunkt im TaskService noch erstellt werden (Siehe aktueller Endpunkt in der Engine) 
    * Die Engine löste bei einem Cancel ein DeleteEvent aus, worauf der TaskService bereits jetzt schon reagiert 
* In der Engine muss ein Listener erstellt werden, der bei Tasks mit Boundry-Event eine lokale Task-Variable schreibt, dass dieser Task cancelbar ist
     * Der Listener muss vor Polyflow laufen   
* In der UI muss die Mapping-Logik angepasst werden, die anhand der Task-Variable den Cancel-Button steuert 

**Akzeptanzkriterien**
* Tasks können in der UI abgebrochen (Drei Punkte) werden und verschwinden aus der Liste
* Das Abbrechen löst im Prozess einen BPMN-Fehler aus

**Additional context**

**Comment by zambrovski** [comment]
Schritte des Implementierungsplans:

- [x] Anpassung Open API 
- [x] Erweiterung des UseCasePorts 
- [x] Implementierung des ControllerDelegates 
- [x] Test des Controller Delegates
- [x] Erweiterung des TaskEngineOutPorts
- [x] Definition der Prozessvariable 
- [x] Implementierung des Use Cases
- [x] Test des Use Cases
- [x] Implementierung eines Listeners im Polyflow-Connector
- [x] Test des Listeners
- [ ] Anpassung UIs

**Comment by darenegade** [comment]
UI: https://github.com/it-at-m/digiwf-core/pull/343
