### ISSUE TITLE
Task-Service: Alt-Schema Support

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#321]
**Is your feature request related to a problem? Please describe.**
Um weiterhin alte Schema zu supporten muss der Task-Service dies anhand der Task-Daten erkennen und damit umgehen können.

**Describe the solution you'd like**

* Neuer SchemaValidationAdapter und RemoteSchemaAdapter für das alte Schema.
* Task-Service muss hier eine Weiche einbauen, je nach Schemaversion
* Validierung und Data Enrichment bleibt in der Engine

**Describe alternatives you've considered**
Kein Support von alten Schemas -> Wurde verworfen, da Migration mit höherem Aufwand verbunden ist und so ein besserer Übergang geschaffen werden kann. Altes Schema soll trotzdem mittelfristig final abgelöst werden

**Additional context**
* Wie importieren wir die alten Schema Tasks
  * **im Importadapter wird die Funktionalität des CreateListeners implementiert**
    * **Vor dem Import** werden die Variablen gesetzt, danach wird die bestehende Import Logik genutzt 
* Wir schreiben einen Task-Create-Listener
  * schemaRef in die Prozessvariablen
  * tasktyp wird ermittelt indem geprüft wird ob der FormKey gesetzt ist
    * SCHEMA_BASED
    * VUETIFY_FORM_BASE
* Validierung und Enrichment bleibt in der Engine
* Logik zum Einschränken der Daten beim Laden eines Task wird in den neuen TaskService übernommen
* Es gibt einen Legacy-Form-Outport zum Laden des Forms im neuen TaskService
* Byte Arrays sind kein Problem - Annahme: alles nur LinkedHashMap
* Anpassung Frontend API

**Comment by darenegade** [comment]
@dominikhorn93 Hier müssen wir nochmal sprechen im Ref. was genau wo zu tun ist. Das ist mir noch nicht klar

**Comment by darenegade** [comment]
@zambrovski und @dominikhorn93 erarbeiten hier ein Konzept und beschreiben dies hier im Ticket

**Comment by zambrovski** [comment]
- [x] Create task schema Type ENUM, define variable factory to carry those ("app_task_schema_type")
- [x] Create a create task listener (for new tasks), which sets the variable "app_task_schema_type" based on the value in form key... 
- [x] Create an import service (for existing tasks), which does the same as the create task listener
- [x] Modify task-service save/complete method and react on the value of the variable.
  - [x] For value SCHEMA remain as now
  - [x] For value VUETIFY_FORM_BASE invoke a new Engine Client which invokes the endpoint of the engine to complete task
- [x] Mark old code deprecated.
- [ ] Add polyflow connector to cockpit and add cockpit to monorepo
- [x] Legacy client should be able to load task 
- [x] Load task of old type via task service
- [x] Frontend anpassen
