### ISSUE TITLE
Task-Service: PostgreSQL in Dev

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#322]
**Is your feature request related to a problem? Please describe.**

In der Dev soll auch eine Postgresql für die Engine genutzt werden

**Describe the solution you'd like**

Neues Schema anlegen lassen, auf der bestehenden Postgres von der Test-Umgebung
Doku im Betriebshandbuch anpassen

**Describe alternatives you've considered**

H2 weiter verwenden -> Dann müsste die Engine auch auf H2 laufen -> nicht gut

**Additional context**
-

**Comment by darenegade** [comment]
Bitte hier auch schauen, ob der Task-Service sauber hochfährt und Tabellen angelegt werden. DDL-Auto sollte nicht verwendet werden. Siehe #331

**Comment by simonhir** [comment]
Internes ServiceNow-Ticket für neues Schema: REQ0489688

**Comment by simonhir** [comment]
Interner MR: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/119

**Comment by simonhir** [comment]
Interne MRs für PostgreSQL Dependency
Cockpit: https://git.muenchen.de/digitalisierung/digitalisierung-cockpit/-/merge_requests/35
Engine-Rest: https://git.muenchen.de/digitalisierung/digitalwf-restapi/-/merge_requests/13
