### ISSUE TITLE
Test-Initialisierung

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#327]
Import example processes from `digiwf-core` into CoCreation to be able to deploy and edit for release testing.

https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-engine/digiwf-engine-service/src/main/resources/prozesse/example

**Comment by simonhir** [comment]
Dokument in Confluence für Testablauf
Auch Schritte wie
- Cancel Task
- Wiedervorlage

**Comment by darenegade** [comment]
@Sbivvds241 Muss noch den Cancel-Prozess fertig machen auf Demo und dazu ein Formular deployn. Idealerweise das auch für Lokal bereitstellen

Daher wieder auf InProgress

**Comment by Sbivvds241** [comment]
pr für den cancelable user task als neuen teil der example tasks
https://github.com/it-at-m/digiwf-core/pull/367
