### ISSUE TITLE
Email for user tasks is sent even if process creation fails

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#328]
Emails for new user tasks are sent to the assigned user even if the creation of the process fails.

In that specific case the creation failed because the required db table wasn't existing.

**Acceptance Criteria**

- [ ] E-Mail Notification is only sent when TaskCreation succeeded

**Comment by darenegade** [comment]
Wieder offen, wegen #1217

**Comment by lmoesle** [comment]
> Wieder offen, wegen #1217

Wie machen wir bei dem Ticket weiter? Den Fehler kann man sehr schlecht reproduzieren und der erste Bugfix hat schon nicht geklappt, weil wir das Taskmanagement geändert haben. Ich bin mir nicht sicher, ob der Fehler überhaupt noch auftritt bzw. wie wir das fixen können.
Evtl. könnten wir das Send Notifications Feature von der Engine in die Tasklist umziehen. Das wäre aber aufwendiger und sollten wir in einem extra Ticket diskutieren.

**Comment by darenegade** [comment]
Das Problem ist sogar nun noch größer geworden. Aktuell ist es so, dass man eine Benachrichtigung erhält, wenn man eine Gruppenaufgabe annimmt in der UI.

Da die Leute in der Regel die Aufgabe annehmen und fertigstellen und erst dann in die Mails später schauen, ist die Aufgabe in der Mail nicht mehr aktuell.

**Comment by markostreich** [comment]
Problem ist nur in der Dev-Umgebung aufgetreten und selten.
Im Team besprochen, dass es geschlossen wird.
