### ISSUE TITLE
Fehler bei DMS-Zugriff - ungültige Objektadresse

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-core#332]

**Comment by Sbivvds241** [comment]
Im Cockpit gibt es ca 30 Incidents mit Meldung: UNBEKANNTER FEHLER (-1): Ungültige Objektadresse ""

**Comment by darenegade** [comment]
@Sbivvds241 Gibt es hierzu ein internes Ticket? Wenn ja, bitte hier verlinken

**Comment by Sbivvds241** [comment]
https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/332

**Comment by darenegade** [comment]
Das ist ein Link auf das Ticket hier 🤣

**Comment by Sbivvds241** [comment]
meinst du digiwf-support ?
oder Service Now ?

**Comment by darenegade** [comment]
Mir geht es darum, woher dieser "Incident" kommt. Oder habt ihr das einfach im Cockpit festgestellt und dann das Ticket aufgemacht?

**Comment by darenegade** [comment]
Vielleicht ein paar Beispiele an denen man den Fehler eingrenzen kann. So weiß man hier nicht, wo man anfangen soll

**Comment by Sbivvds241** [comment]
der Incident taucht öfter auf im Cockpit
z.B. hier
https://digiwf-cockpit.muenchen.de/camunda/app/cockpit/default/#/process-instance/1d87aab6-daa6-11ed-bc63-0a580a8a424d/history?viewbox=%7B%22Definitions_16zu6fb%22:%7B%22x%22:149.32558139534882,%22y%22:-119.85116279069769,%22width%22:7358.139534883721,%22height%22:2200%7D%7D&detailsTab=incidents-tab

Michael Jacob hat uns darauf aufmerksam gemacht
Ein explizites digiwf-support issue gibt es dafür nicht

**Comment by dominikhorn93** [comment]
@darenegade es liegt daran, dass die User nicht richtig autorisiert sind im DMS.
Zudem werden dann falsche Fehlermeldungen vom DMS zurückgegeben.

Die Autorisierung, die vom Fachbereich nicht richtig gemacht wird, fällt uns schon häufig auf die Füße.
Eventuell können wir zum Abschluss mal ein Brainstorming machen, was wir hier ändern können?
Problem ist, dass es nicht unser System ist...

**Comment by darenegade** [comment]
@dominikhorn93 Kannst du den Fehler und die Ursache in Betriebshandbuch dokumentieren. Dann können wir das rausziehen, wenn es mal wieder kommt. 

Für die DMS wird an sich ja aktuell gerade eine neue API gebaut. Da kann man einfließen lassen, dass die Fehlermeldungen besser werden sollen. Wir sind hier aber erstmal raus

**Comment by dominikhorn93** [comment]
@darenegade den Eintrag sollte meiner Meinung nach @simonhir machen. Den Text würde ich wie folgt formulieren:

Es gibt bei der Verbindung mit dem DMS Incidents die auftreten können.
Deshalb sollten bei Schwierigkeiten wie folgt (priorisiert) bei der Analyse vorgegangen werden.

1. Prüfen ob der Benutzer die entsprechenden Berechtigungen hat. Häufig ist es der Fall, dass der Fachbereich die Benutzer, die bei der Übertragung als Autorisierung genommen werden, nicht richtig autorisiert hat. Dies führt zu den unterschiedlichsten Fehlermeldungen im DMS, die häufig nicht eindeutig sind wie bspw.
* Objekt nicht gefunden
* Üngültige Objektadresse
* Manchmal auch eindeutig, dass der User nicht auf das Objekt zugreifen darf
**WICHTIG:** Punkt 1. war bisher für die meisten Incidents im DMS verantwortlich. Das Fehlerbild zeigt, dass manche Instanzen durchlaufen und andere nicht - abhänig vom User der am Prozess beteiligt ist.

2. Prüfen ob sich etwas an den Credentials des technischen Users geändert hat. Ist dies der Fall, kann keine Abfrage mehr zum DMS gemacht werden. Dies ist auch der Unterschied zu Punkt 1. in dem der Fehler nur bei manchen Prozessinstanzen auftritt

3. Prüfen ob sich etwas an der URL des Loadbalancers in OpenShift geändert hat. Wie bei Punkt 2. treten die Probleme dann für alle Prozessinstanzen auf.

4. Prüfen ob die Schnittstelle sich geändert hat. Dies ist bisher noch nicht aufgetreten, kann aber durch Versionsupgrades durchaus passieren. Dieser Fehler wird schwieriger nachzustellen sein, weil sich nur manche Endpunkte geändert haben könnten und unter Umständen kein klares Fehlerbild vorliegt.

**Comment by simonhir** [comment]
Habe das ganze mal unter https://wiki.muenchen.de/betriebshandbuch/wiki/DigiWF#EAI-COSYS aufgenommen.

**Comment by darenegade** [comment]
@simonhir Passt, danke
