### ISSUE TITLE
DMS Forms: Typo in Json-Form - Textarea

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#340]
**Describe the bug**
In den DMS Formularen der Plattform gibt es einen Typo bezüglich der Textarea

**To Reproduce**
https://github.com/search?q=repo%3Ait-at-m%2Fdigiwf-core+textare%22&type=code

**Expected behavior**
"Textarea" statt "Textare"

**Additional context**
Hier sind die korrigierten Forms hinterlegt. Diese müssen auf allen Umgebungen ausgebracht werden.

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/291

**Comment by darenegade** [comment]
@Sbivvds241 Das wäre eventuell was für dich

**Comment by StephanStrehlerCGI** [comment]
MR: https://github.com/it-at-m/digiwf-core/pull/429

**Comment by darenegade** [comment]
@dominikhorn93 muss hier zusammen mit @Sbivvds241 die Files in den Umgebungen deployn. 

Imp.: Da aktuell beide Personen andere Themen bedienen

**Comment by darenegade** [comment]
@simonhir Kannst du das Thema übernehmen? Hat keine hohe Prio, sollte aber auch schnell umgesetzt sein.

Hier fehlt noch das ausbringen auf den Umgebungen

**Comment by simonhir** [comment]
Manuell deployed auf processes-* und prod
