### ISSUE TITLE
EZLDAP: Liste von Gruppen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#342]
**Describe the bug**
Aktuell wird die OU von EZLDAP in eine Singleton-Liste geschrieben. Fachlich ist eine Person organisatorisch aber Teil von mehreren Gruppen -> Team, Geschäftsbereich, Abteilung, Referat usw..

**To Reproduce**
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-task/digiwf-tasklist-service/src/main/java/io/muenchendigital/digiwf/task/service/adapter/out/user/LdapUserGroupResolverAdapter.java#L23

**Expected behavior**
Liste von Zugehörigkeiten wird ermittelt. Siehe [aktuelle Engine](https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/user/external/client/LhmLdapClient.java#L142)

Alternativ über ein "Starts-With", wenn Struktur in allen Referaten so stringent, wie bei ITM
z.B. Task zugeordnet an "ITM-KM8" und ich kann darauf zugreifen, weil ich "ITM-KM83"
oder im Sozialreferat zugeordnet zu "s-iii-mf/a" und Andrea Riedl erfüllt das mit "S-III-MF/A2"

**Additional context**
LHM für alle:
https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/user/external/client/LhmLdapClient.java#L219
Basis-Zuweisungen sollten aber konfigurativ gesetzt werden können, damit wir den OSS Task-Service nicht an die LHM binden

**Comment by darenegade** [comment]
mWn wird auch irgendwo defaultmäßig in der Engine jeder MA der Gruppe "lhm" zugeordnet. Das müsste man hier auch noch machen 

Edit: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/legacy/user/external/client/LhmLdapClient.java#L219

**Comment by darenegade** [comment]
Beispiele von der Test-Umgebung:

![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/6990b2af-105c-4579-9fc5-fe5465103adf)
![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/da7afede-a95c-42b9-80cb-f4adfe1652ad)

**Comment by darenegade** [comment]
Abstimmung mit Michael Prankl: 

Wenn uns die Datenstruktur von ezLDAP nicht ausreicht, können wir gerne einen MR dort aufmachen mit einer Erweiterung. Anforderung wäre, dass der Abteilungsbaum in einem eigenen Endpunkt abgefragt werden kann;

`GET /ldap/outree/ITM-KM21` -> Antwort `LHM, RIT, ITM-KM, ITM-KM2, ITM-KM21`

MR wäre hier zu stellen: https://git.muenchen.de/km23/einrichtungsverwaltung/ezLDAP

Wir könnten da Teile von unserem alten Code aus der Engine dort als eigenen Endpunkt einfach einfließen lassen.

**Comment by darenegade** [comment]
@Sbivvds241 Hab gesehen, dass du das Ticket genommen hast. Ist dir klar, was hier zu tun ist?

**Comment by Sbivvds241** [comment]
ich schaus mir gerade an - frag mich morgen nochmal

**Comment by lmoesle** [comment]
@darenegade Ich hab mir das Ticket durchgelesen. So wie ich das Verstanden habe muss ich in Easy Ldap einen neuen Endpunkt erstellen, über den ich den outree für eine Gruppe auslesen kann. Diesen Endpunkt rufe ich dann von der Tasklist aus auf.
Ist das soweit richtig?

**Comment by darenegade** [comment]
> Diesen Endpunkt rufe ich dann von der Tasklist aus auf. Ist das soweit richtig?

Ja genau. Michael will hierzu einen eigenen Endpunkt haben, damit der im Hintergrund stattfindende mehrfache Call gegen LDAP beim auflösen der Shortnames nur dann passiert, wenn man es auch wirklich braucht

**Comment by lmoesle** [comment]
Ich habe unseren Legacy Code in EzLdap integriert. Aktuell kann ich schon den Ou Tree für einen User auslesen.
Der nächste Schritt wäre die Logik zu refactoren und den Ou Tree auf Basis eines Ou Shortcodes auszulesen.
Damit würde ich dann am Freitag weitermachen.

Den aktuellen Stand habe ich in Gitlab commited: https://git.muenchen.de/ext.dl.moesle/ezLDAP/-/tree/feature/read-ldap-outree?ref_type=heads

**Comment by lmoesle** [comment]
PR in EzLdap ist offen: https://git.muenchen.de/km23/einrichtungsverwaltung/ezLDAP/-/merge_requests/26

Die nächsten Steps sind:
- noch Tests in EzLdap schreiben
- die neue EzLdap API in der Tasklist anbinden

**Comment by lmoesle** [comment]
PR im EzLdap Repo ist gemerged. Es fehlt jetzt nur noch die Anbindung des neuen Endpoints in der Tasklist
