### ISSUE TITLE
Maven Group-Name anpassen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#346]
Aktuell haben wir überall noch `io.muenchendigital.digiwf`

https://github.com/it-at-m/digiwf-core/blob/dev/pom.xml#L6

Dies sollten wir an allen Stellen (POM, Java-Files, ~~Konfigs,~~ usw.) ändern auf `de.muenchen.oss.digiwf`

Anschließend alles darunter veröffentlichen auf Maven

Und Konfigs überall angleichen und auf produktiven Umgebungen Keys mit neuen Pfad kopieren als Vorbereitung f. nächsten Release

Wichtig: Umstellung pro Artefakt und sep. PR in Abstimmung mit dem Team, damit dies nicht in die quere zu anderen Entwicklungen kommt.

Konfigs ausgenommen und folgt in einer eigenen Story

Achtung: Nur DigiWF-Core

**Comment by darenegade** [comment]
https://github.com/search?q=repo%3Ait-at-m%2Fdigiwf-core%20muenchendigital&type=code

**Comment by lmoesle** [comment]
In folgender Reihenfolge sollten die PRs gemerged werden:

1. Initial: https://github.com/it-at-m/digiwf-core/pull/543
2. Die einzelnen Maven Module (beliebige Reihenfolge):
  - [x] Connector: https://github.com/it-at-m/digiwf-core/pull/554
  - [x] Engine: https://github.com/it-at-m/digiwf-core/pull/551
  - [x] Gateway: https://github.com/it-at-m/digiwf-core/pull/552
  - [x] Integrations: https://github.com/it-at-m/digiwf-core/pull/553
  - [x] Libs: https://github.com/it-at-m/digiwf-core/pull/550
  - [x] Process: https://github.com/it-at-m/digiwf-core/pull/549
  - [x] Schema Registry: https://github.com/it-at-m/digiwf-core/pull/548
  - [x] Task: https://github.com/it-at-m/digiwf-core/pull/547
3. Coverage (nach den anderen mergen): https://github.com/it-at-m/digiwf-core/pull/546
4. Das Java package Struktur renaming (beliebige Reihenfolge):
  - [x] Connector: https://github.com/it-at-m/digiwf-core/pull/561
  - [x] Engine: https://github.com/it-at-m/digiwf-core/pull/562
  - [x] Gateway: https://github.com/it-at-m/digiwf-core/pull/563
  - [x] Integrations: https://github.com/it-at-m/digiwf-core/pull/565
  - [x] Libs: https://github.com/it-at-m/digiwf-core/pull/564
  - [x] Process: https://github.com/it-at-m/digiwf-core/pull/558
  - [x] Schema Registry: https://github.com/it-at-m/digiwf-core/pull/559
  - [x] Task: https://github.com/it-at-m/digiwf-core/pull/560
5. Abschluss: https://github.com/it-at-m/digiwf-core/pull/557
  - [x] Hier nochmal überprüfen, ob die alte Gruppe in einem Artefakt verwendet wird
