### ISSUE TITLE
Kopierte Daten werden in Inputs nicht gespeichert

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#348]
**Describe the bug**
Wenn ein Pflichfeld mit einem Wert aus der Zwischenablage befüllt wird, werden die Daten nicht übernommen

Das Problem hier hängt wahrscheinlich wieder an dem Blur-Event:
https://github.com/it-at-m/vuetify-jsonschema-form/pull/3

**To Reproduce**
1. Antrag mit Pflichfeld (z.B. Fahrtkostenzuschuss) erstellen
2. Wert in Pflichfeld reinkopieren
3. Prozess starten
4. Wert fehlt in Prozess-Variablen

**Expected behavior**
Kopierte Daten werden übernommen.

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/292

**Comment by StephanStrehlerCGI** [comment]
Bug konnte nicht reproduziert werden. Rückfrage mit Nutzern wurde gehalten. Nutzer können es auch nicht mehr reproduzieren. 
Daher wird der Bug geschlossen.
