### ISSUE TITLE
digiwf-ops configuration inconsistent

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#351]
The config maps and environment variables are not equal for all digiwf environments. (i.e. not present, other names, ...)
This can lead inconsistent misbehavior between different stages.

Probably something like Helm should be used to avoid this in the feature.

## Acceptance criteria
- [ ] In the apps directory are only env vars defined that are never overwritten
- [ ] All environments define the same vars for each service (except prod for kafka topics)
- [x] Only used services are defined (old services are removed)
- [x] Only directly reachable services should have routes
- [x] A quick evaluation of helm was done -> separate ticket if better choice than kustomize
    - Timeboxing 1h - Goal: Get a feeling how big the change would be

**Comment by darenegade** [comment]
@simonhir Can u be a bit more specific about the inconsistencies or provide some links.

Currently we're using kustomize. I don't know if helm really helps with that problem without getting too complex

**Comment by simonhir** [comment]
Some example i found just today:
- https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/clusters/k/digiwf-demo/digiwf-email-integration/service-config.yaml#L7 (Wrong values copied from other env)
- https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/clusters/k/digiwf-dev/digiwf-engine/service-config.yaml vs https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/clusters/k/digiwf-processesdemo/digiwf-engine-rest/service-config.yaml (Different Env Values between Envs)

Especially the second example comes up nearly every time i look over some service-configs.

What i think would help with helm or oc process that the config is theoretically static and only the values are changed and set via environment specific configs.

**Comment by darenegade** [comment]
> https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/clusters/k/digiwf-dev/digiwf-engine/service-config.yaml vs https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/clusters/k/digiwf-processesdemo/digiwf-engine-rest/service-config.yaml (Different Env Values between Envs)

engine != engine-rest

**Comment by simonhir** [comment]
Sorry that is the result when listening to a meeting and looking up something at the same time ...

@zambrovski can you remember the inconsistent file we talked about earlier today? Couldn't find it again.
Or was that just between the different branches?

**Comment by darenegade** [comment]
Maybe this is a bigger scope if we consider to move to helm charts

**Comment by darenegade** [comment]
One example i currently struggling with

https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/apps/digiwf-gateway/service-config.yaml#L10

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/351?planning-poker) with Zenhub @darenegade @lehju @simonhir @StephanStrehlerCGI
