### ISSUE TITLE
Cosys Integration/Camunda Connector in Dev- und Test-Umgebung fehlerhaft

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#356]
Die Cosys-Integration schlägt in der Dev und Test-Umgebung beim Senden der Antwort-Message am `camunda-connector-service` fehl.
Unter Demo funktioniert das Ganze ohne Probleme.

Teilweise scheint die Cosys-Integration auf anderen Umgebungen wie P und Processes auch nicht spezifisch den Camunda-Connector zu verwenden.

Im speziellen tritt der Fehler beim Ausführen der Example-Prozesse Cosys-Integration bzw. S3-Integration auf. Hier bleibt der Create-Cosys-Document hängen.

**Comment by darenegade** [comment]
Wurde erledigt mit release Juni
