### ISSUE TITLE
TaskService save current task state not working

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#363]
Saving the current state of a task (the values of the form) via the menu item "Aufgabe zwischenspeichern" the values are sent to the backend but not stored.

## To reproduce
- Start a process to get a user task (i.e. example-usertask)
- Open the task
- Fill in some values in the form
- Save the state via "Aufgabe zwischenspeichern"
- Reload the page

--> All values are lost

**Comment by lmoesle** [comment]
Wie wir heute morgen schon gesehen haben liegt es an der `validateAndSerialize` Methode im `JsonSchemaValidationAdapter`. Es wird immer eine leere Liste zurückgegeben, weswegen keine Variablen in der Engine gesetzt werden.
Codestelle: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-task/digiwf-tasklist-service/src/main/java/io/muenchendigital/digiwf/task/service/adapter/out/schema/JsonSchemaValidationAdapter.java#L23-L36

Viel mehr habe ich bisher noch nicht herausgefunden, ich habe aber das Camunda Cockpit hinzugefügt, damit wir anständig Prozess debuggen können (siehe #387).
