### ISSUE TITLE
TL-10: Gruppen-Aufgabe zur Bearbeitung auswählen | Cypress

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#378]
Umsetzung von Testfall als Cypress Test

https://confluence.muenchen.de/display/MPdZ/Test-Dokumentation#TestDokumentation-TL-10:Gruppen-AufgabezurBearbeitungausw%C3%A4hlen

## Akzeptanzkriterien
* Testfall komplett automatisiert
* Test läuft lokal & in der [Pipe](https://git.muenchen.de/digitalisierung/digiwf-core/-/pipelines)

**Comment by simonhir** [comment]
Testfälle werden mit #1395 überarbeitet und bei Bedarf neu erstellt
