### ISSUE TITLE
TL-12: Formularfelder: All input fields task | Cypress

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#380]
Umsetzung von Testfall als Cypress Test

https://confluence.muenchen.de/display/MPdZ/Test-Dokumentation#TestDokumentation-TL-12:Formularfelder:Allinputfieldstask

## Akzeptanzkriterien
* Testfall komplett automatisiert
* Test läuft lokal & in der [Pipe](https://git.muenchen.de/digitalisierung/digiwf-core/-/pipelines)

**Comment by simonhir** [comment]
Testfälle werden mit #1395 überarbeitet und bei Bedarf neu erstellt
