### ISSUE TITLE
User-Tasks: Haken Wiedervorlage funktioniert nicht richtig

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#386]
**Describe the bug**
Wiedervorlage-Filter funktioniert falsch

**To Reproduce**
Siehe: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/293

**Expected behavior**
FollowUp-Tickets werden nur angezeigt, wenn Haken gesetzt

**Comment by StephanStrehlerCGI** [comment]
MR: https://github.com/it-at-m/digiwf-core/pull/433
