### ISSUE TITLE
Tasklist: DigiWF Classic Switch funktioniert nicht

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#391]
**Describe the bug**
Der Feature-Toggle Switch in der UI verändert das Verhalten nicht. Umstellung kann nur erfolgen, wenn man den Feature-Toggle im local Storage 

**To Reproduce**
1. Go to TaskList
2. Switch in der UI deaktivieren
3. UI geht trotzdem auf Engine

**Expected behavior**
Switch kann genutzt werden, zwischen Engine und Task-Service hin und herzuschalten

**Screenshots**
![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/d4da0b79-8860-40b4-bdbd-4e179b060076)

**Comment by simonhir** [comment]
Button funktioniert noch nicht zuverlässig bzw. wird teilweise falsch angezeigt
