### ISSUE TITLE
Tasklist: S3 Service sollte Methode PUT unterstützen

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#398]
Der S3 Service in der Tasklist sollte auch die Methode PUT unterstützen. Siehe PR Feedback: https://github.com/it-at-m/digiwf-core/pull/396

**Comment by darenegade** [comment]
Imp. da es bei Lukas liegt

**Comment by lmoesle** [comment]
Zusätzliche Anforderung:

- Multifile-Input unterstützt das Überschreiben von Dateien

Aufgaben:

- [ ] Multifile Input Component unterstützt PUT presigned urls
- [ ] Multifile Input Component refactoring

**Comment by lmoesle** [comment]
imho wäre es sinnvoll mit dem Ticket noch zu warten bis der Feature Toggle im Frontend ausgebaut ist, da dadurch der Implementierungsaufwand erheblich sinkt. Aktuell unterstützt nur die neue Tasklist API das Überschreiben von Dateien und für die Legacy Version müsste man einen Workaround bauen.

**Comment by darenegade** [comment]
Die alte API ist deaktiviert und wird nicht mehr genutzt. Sie wird zeitnah ausgebaut. Ich sehe nicht, warum wir das für das Legacy einbauen oder einen Workaround schreiben sollten

**Comment by lmoesle** [comment]
> Die alte API ist deaktiviert und wird nicht mehr genutzt. Sie wird zeitnah ausgebaut. Ich sehe nicht, warum wir das für das Legacy einbauen oder einen Workaround schreiben sollten

Genau, deswegen fände ich es sinnvoll noch zu warten bis die API ausgebaut ist, dann wird die Implementierung im Frontend einfacher

**Comment by darenegade** [comment]
Ich verstehe noch nicht, warum die Impl. dann einfacher wird. Du musst das doch in die Custom-Comp. einbauen. Das meiste ist Copy/Paste und der Engine Teil bleibt einfach leer mit `throw Error`.

Aber wenn wir können das ganze auch auslagern in ein eigenes Ticket. Dann bitte Ticket erstellen und auf "New" packen und dieses Ticket dann abschließen
