### ISSUE TITLE
Cockpit in der Engine

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#402]
**Is your feature request related to a problem? Please describe.**
Das sep. Cockpit ist schweirig im Handling und birgt einige Fehlerquellen bei der Nutzung.

**Describe the solution you'd like**
Cockpit in die Engine integrieren und Spring Boot Login mit OAuth nutzen. (Für normale Cockpit User)
Basic-Auth nicht mehr notwendig, da Cockpit über Gateway geht

Sep. Cockpit nur och für Admin Tätigkeiten nutzen, falls die Engine nicht läuft. Kein Zugang mehr außerhalb vom DigiWF-Team

* Camunda-WebApp an SB-Sec in der Engine anbinden
* Prüfen, ob EE Maven-Build für Engine richtig funktioniert
* Cockpit soll hinter Gateway laufen, ggfs. Routen passend konfigurieren -> Auslagern in eig. Story, aber damit noch nicht auf Processes-* und Prod ausbringen
    * Cockpit Cookie muss durchs Gateway gehen 

**Describe alternatives you've considered**
Cockpit weiterhin extern betreiben -> Keycloak Plugin nicht stabil / Externes Cockpit kann Fehlerquelle sein bei falscher Nutzung

**Additional context**
https://git.muenchen.de/digitalisierung/digitalisierung-cockpit

Internes Ticket: 
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/40
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/318

**Comment by darenegade** [comment]
@zambrovski @dominikhorn93 Grundsätzlich sollte sich das Thema hier doch gut umsetzen lassen, oder gibt es Blocker, die wir vorher angehen müssen?

**Comment by StephanStrehlerCGI** [comment]
Ergebnis aus Planning: 
@dominikhorn93 und @StephanStrehlerCGI setzen sich zusammen und evaluieren den bestehenden Fehler. 
Wenn Fehler leicht zu fixen wird es in diesem Task erledigt, bei größerem Problem wird ein neuer Bug erstellt.

**Comment by darenegade** [comment]
Wartet auf @zambrovski

**Comment by darenegade** [comment]
XSRF Bug wird in #639 weiter verfolgt
