### ISSUE TITLE
Taskimporter schlägt bei fehlerhaften BPMNs fehl

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#407]
Task-Importer schlägt fehl, wenn ein BPMN fehlerhaft ist:

![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/2d8d30c2-25d4-4142-a9d6-68fb8cb82827)

**Comment by dominikhorn93** [comment]
Vorgehen:
- Wir filtern die ProcessDefinitionIds bei denen das auftritt über "initialize Form"
- danach löschen wir die ProcessDefinitions über das Cockpit manuell

**Comment by dominikhorn93** [comment]
Wir haben 2 Optionen.
- Wir betrachten alle Prozessdefinitionen
- Wir betrachten lediglich Prozessdefinitionen zu denen noch Aufgaben existieren

-> Speicher könnte bei > 4K Prozessdefinitionen schwierig werden.

Die Story verhindert meiner Meinung nach kein Release, sondern lediglich dass "alte Aufgaben" in den Testumgebungen nicht in die neue Taskliste importiert werden können. Das tritt jedoch nicht in Produktion auf, da dort keine "kaputten" Prozessdefinitionen existieren.
