### ISSUE TITLE
Task-Backend nutzt keine Consumer-Group auf Kafka

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#408]
Beim Start vom Task-Backend-Service wird nur per ClientID am Topic gebunden. Aus diesem Grund startet jede neue Instanz dieses Services wieder am Anfang vom Topic, da kein Offset vorliegt.

**Comment by darenegade** [comment]
@zambrovski @dominikhorn93 

Das Thema hat sich mit der Info am Freitag über die Axon Funktionsweise ja erübrigt. Vielleicht sollten wir das aber dokumentieren bzw. auf die entsprechende Doku von Axon verweisen

**Comment by zambrovski** [comment]
Hier ist die Doku aus dem Axon-Kafka: https://docs.axoniq.io/reference-guide/extensions/kafka#consuming-events-with-a-streamable-message-source
