### ISSUE TITLE
Polyflow in Camunda Cockpit

### ISSUE THREAD

**Issue by zambrovski** [it-at-m/digiwf-core#439]
Um Fehler durch Camunda Cockpit zu vermeiden muss Camunda Cockpit den Polyflow-Connector verwenden (genau wie Engine) inkl. Verbindung zu Kafka.

#### Mögliche Fehlerquellen

* Operation an Prozessinstanz ohne "Async" Flag führen zur Ausfühung der Operation direkt in der SPB-Applikation des Cockpits in dem z.Z. die Listener fehlen und die Polyflow Intgegration auch fehlt.

**Comment by Sbivvds241** [comment]
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/163
