### ISSUE TITLE
Feld "multiselect" kann nicht als Pflichtfeld eingestellt werden

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#440]
**Describe the bug**
Mulitselect ist kein Pflichtfeld im Formular, auch wenn es im JSON-Form so eingetragen wird

**To Reproduce**

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/301#schritte-um-den-fehler-nachzustellen

**Expected behavior**
Multiselect Pflichtfeld muss richtig validiert werden

**Additional context**
* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/301

**Comment by simonhir** [comment]
Denke das ist kein Bug siehe https://github.com/it-at-m/digiwf-core/issues/442#issuecomment-1590518801

Hier fehlt aber aktuell noch der Input für `minItems` und `maxItems`
