### ISSUE TITLE
Multi-User-Input: Eingabe-Text wird nicht bereinigt nach Auswahl

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#441]
**Describe the bug**
Nach der Auswahl eines Users bleibt der Eingabetext weiterhin bestehen

**To Reproduce**
1. Formular mit MultiUser Input öffnen 
2. Namen eingeben und Person auswählen -> Text bleibt bestehen

**Acceptance Criteria**

- [ ] Eingabetext verschwindet nach Übernahme

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/236

**Comment by darenegade** [comment]
Wenn die Lösung hier zu aufwendig wird wird das ein wont-fix

**Comment by simonhir** [comment]
So wie ich das sehe ist das mittlerweile schon behoben.
@lehju hast du das zufälligerweise mal mitbehoben?

**Comment by simonhir** [comment]
Wurde bereits im Rahmen eines anderen Tickets behoben
