### ISSUE TITLE
Multi-User Input: Required broken

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#442]
**Describe the bug**
Multi-User Input kann nicht als Pflichtfeld definiert werden

**To Reproduce**
1. Multi-User Input in Form und versuchen als Pflichtfeld zu definieren
2. Multi-User ist kein Pflichtfeld

**Expected behavior**
Pflichtfeld kann bei MultiUser Input gesetzt werden und wird im Formular validiert

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/284

**Comment by simonhir** [comment]
Glaube nicht, dass das ein wirklicher Bug ist, da mit required nur auf leere Strings getestet wird und hier der Wert ja wenn `[]` ist. Siehe https://github.com/it-at-m/vuetify-jsonschema-form/blob/master/lib/utils/rules.js#L6

Dafür gibts ja dann eigentlich extra `minItems` und `maxItems`.

Mein Vorschlag wäre hier und bei #440 das required Feld weg zu machen (wenn vorhanden) damit bei beiden nur min und max Items gewählt werden kann.

**Comment by darenegade** [comment]
@simonhir Vorschlag wäre okay und können wir gerne machen.
