### ISSUE TITLE
Gleitkomma-Input: Strings werden nicht korrekt validiert

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#443]
**Describe the bug**
Gleitkommezahlen-Inputs ermöglichen Fehleingabe, z.B. Zahlen mit Tausendertrennzeichen

**To Reproduce**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/98#schritte-um-den-fehler-nachzustellen

**Expected behavior**
Eingabe von Strings verbieten und keine Tausendertrennzeichen
Alternativ: Über vue-mask Eingabe autom. formatieren und resultierenden Wert entsprechend ohne Formatierung speichern

**Acceptance Criteria**

- [ ] Gleitkomma-Input verbietet Trennzeichen oder forciert diese mit validem output

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/98

**Comment by dominikhorn93** [comment]
Ist nicht perfekt... aber mir ist echt nichts besseres eingefallen als das hier: https://github.com/it-at-m/vuetify-jsonschema-form/pull/9/files
