### ISSUE TITLE
SSO-Roles as Candidate-Groups/Process-Create

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#458]
**Is your feature request related to a problem? Please describe.**
Currently, only LDAP groups can be used for candidate group assignments. This makes the assignment strongly dependent on the company structure and cannot be flexibly assigned to individuals.

**Describe the solution you'd like**
In addition to LDAP assignments, we should introduce SSO roles that can also be used as candidate groups

* SSO roles are recognized by prefix `ROLE_`.
* SSO Roles from User-Info
* User tasks:
     * Roles from User-Info are included in the groups of the User-Context
* Processes: 
     * Include SSO roles from User-Info in Auth.
     * Allow technical users anyway (Possibly there is no Auth context -> e.g. Formserver)
* Documentation 

**Describe alternatives you've considered**
Custom LDAP Groups -> Not flexible enough and depends on LDAP

**Acceptance criteria**
* Processdesigner can define own SSO-Roles and use them to Start Processes and to Assign Tasks
* User-Auth-Context is enriched with SSO-Roles
* Documentation is created how SSO-Roles are used

**Additional Context**

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/307
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/145

**Comment by darenegade** [comment]
@dominikhorn93 Wie ist hier der Status?

**Comment by dominikhorn93** [comment]
@darenegade ich hab jetzt einiges recherchiert und ich denke wir müssen einen eigenen JwtAuthenticationProvider Bereitstellen, da wir sonst mit dem Username im Header Umwege gehen müssen. Wenn du heute 10 Minuten für mich hast, fange ich damit an.

**Comment by dominikhorn93** [comment]
Es gibt hier ein paar Hindernisse.
- Wir sollten in Spring Security keinen "User-Switch" machen
- Dadurch, dass wir den User im Header mitgeben vom TaskService aus, kommen wir hier nicht an die Rollen, das ist beim Claim von Aufgaben ein Problem
- Wir vermischen Rollen und Gruppen, wie soll hier das Konzept aus unsere Sicht aussehen?
- Speichern wir Gruppen und Rollen als Authorities im SecurityContext oder trennen wir das voneinander und verbinden das an der richtigen Stelle wieder zusammen?

**Comment by darenegade** [comment]
> Wir sollten in Spring Security keinen "User-Switch" machen

Das sehe ich auch so. Entweder wird der User durch seinen Token transitiv mitgeführt. Oder der Service nutzt einen eigenen Service Account mit eigenen Rollen/Rechten und die User-Auth erfolgt am Edge

 > Dadurch, dass wir den User im Header mitgeben vom TaskService aus, kommen wir hier nicht an die Rollen, das ist beim Claim von Aufgaben ein Problem
 
 Der User im Header war eine Zwischenlösung
 
 > Wir vermischen Rollen und Gruppen, wie soll hier das Konzept aus unsere Sicht aussehen?

Aus meiner Sicht vermischen wir es konzeptionell nicht, nur haben wir unterschiedliche Verständnisse und Begriffe dafür (SSO vs. Camunda) sowie einen Übergang von Neu zu Alt. LDAP-Gruppen sind die alte Lösung und sollen durch SSO-Rollen abgelöst werden. Mit den SSO-Rollen können immernoch ganze Abteilungen oder Teams diese Rolle bekommen, nur lässt es sich dann besser steuern.

> Speichern wir Gruppen und Rollen als Authorities im SecurityContext oder trennen wir das voneinander und verbinden das an der richtigen Stelle wieder zusammen?

Beides soll in den Authorities gespeichert werden unterscheidbar durch den Prefix (Role as Authority)

**Comment by dominikhorn93** [comment]
Entscheidung: Wir senden das Token des Users vom TaskService Backend an das Engine Backend. Außerdem machen wir den Merge von Gruppen und Rollen nicht in der spring-lib, da wir an der Stelle kein LDAP haben möchten. Der Code dafür befindet sich dann in der Engine und im Task Backend.
