### ISSUE TITLE
DigiWF-Formular runtime: Listenfeld (array) verliert Eingabe nach Wechsel des Feldes/Fokus

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#464]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/216

Array- Inputs lose Value on Blur

**Comment by darenegade** [comment]
https://github.com/it-at-m/digiwf-core/pull/86

**Comment by darenegade** [comment]
Thema ist nicht gefixed. Nach Rückmeldung geht es nun für ein Listenelement, aber bei mehreren tritt der Fehler weiterhin auf

@dominikhorn93 Kannst du dir das Thema bitte nochmal anschauen

**Comment by dominikhorn93** [comment]
@darenegade Gibt es dafür ein Beispielformular und eine kurze Beschreibung wie das nachgestellt werden kann?

**Comment by darenegade** [comment]
Hole die Infos ein, bis dahin Blocked

**Comment by darenegade** [comment]
Thema ist wieder da. Das konkrete Problem ist nun, dass die Input-Daten beim Speichern verloren gehen, wenn das Feld vorher nicht den Fokus verliert

Das Problem muss wieder in der vuetify-json-forms Lib gelöst werden

**Comment by simonhir** [comment]
@darenegade nachdem Dominik auch meinte, dass das wahrscheinlich sehr kompliziert wird, wäre es wahrscheinlich die einfachste Lösung das wie in [digiwf-core/#442](https://github.com/it-at-m/digiwf-core/issues/442) [digiwf-core/#440](https://github.com/it-at-m/digiwf-core/issues/440) zu handhaben. Die UI ist dann zwar minimal inkonsistent, weil es kurz so aussieht, wie wenn der Wert akzeptiert werden würde, aber wenn die Form richtig konfiguriert ist mit required und minItems tritt das Problem nicht mehr direkt auf, man muss dann nur zweimal auf den Absenden-Button drücken. (Beim ersten mal validiert und durch Fokus-Verlust Wert gesetzt)

**Comment by simonhir** [comment]
Nach Rücksprache entweder Bug fixen oder einen Hint hinzufügen, dass Eingaben mit Enter bestätigt werden müssen.

Muss wahrscheinlich beides direkt in der Library umgesetzt werden.
