### ISSUE TITLE
Keine Anzeige von offenen und zugewiesenen Vorgängen in Tasklist

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#476]
Aktuell "verschwinden" Gruppenaufgaben in der Task-Liste.

Internes Ticket: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/313

**Comment by darenegade** [comment]
@dominikhorn93 Das ist wieder das Cockpit Problem von Freitag.

**Comment by simonhir** [comment]
Processes-* und Prod auf Cockpit 1.2 zurück gerollt

**Comment by darenegade** [comment]
Ich mache hierfür ein neues Ticket auf

**Comment by darenegade** [comment]
Das Thema ist anscheind nicht gelöst, daher wieder offen
