### ISSUE TITLE
Cockpit mit Polyflow-Connector stört Task-Sync 

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#477]
Wenn man das Cockpit mit dem Polyflow-Connector startet, dann funktioniert der Sync zwischen Engine und Task-Backend nicht mehr.

Siehe auch #476

Internal:

* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/329

**Comment by darenegade** [comment]
Aktuell besteht die Vermutung, dass dies ein Symptom der fehlenden / fehlerhaften Imports ist (#473)

In Demo läuft es aktuell schon zwei Tage stabil mit neuem Cockpit

**Comment by darenegade** [comment]
Für meine Vermutung spricht, dass die Gruppenaufgaben weiterhin nicht funktionieren - Siehe #476

**Comment by zambrovski** [comment]
Ich kann mir auch nicht erklären, wie es eine Rolle spielen sollte

**Comment by darenegade** [comment]
Cockpit wird wieder ausgerollt und dann mal schauen

**Comment by darenegade** [comment]
Hab das Thema auf Prod gerade wieder beobachtet. Nach Rollout war Cockpit in Token-Entry und dann ging Sync nicht mehr. Nachdem ich auf Engine umgestellt habe, ging es wieder

**Comment by darenegade** [comment]
@zambrovski Können wir dem Cockpit temporär bis zur Lösung irgendwie "verbieten" per Config, dass es den Token_Entry übernimmt?

**Comment by zambrovski** [comment]
Fahre es runter. Am Donnerstag bauen wir es ein

**Comment by darenegade** [comment]
https://docs.axoniq.io/reference-guide/axon-framework/events/event-processors/streaming

**Comment by darenegade** [comment]
Cockpit ist auf Prod deaktiviert. Wenn der Fix raus ist, muss das wieder hochgefahren werden

**Comment by darenegade** [comment]
@zambrovski Da es ein Hotfix ist, müssten wir hier vom letzten Release-Tag abzweigen und dann vom Feature-Branch releasen:

https://github.com/it-at-m/digiwf-core/commits/services_0.17.16_hotfix
