### ISSUE TITLE
Robust access handling in ServiceInstanceAuthService  

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#48]
**Describe the bug**
At the moment the hasAccess Method in ServiceInstanceAuthService  expects none or only one entry in the database per user. If there are multiple entries in the database the function throws an exception

[ServiceInstanceAuthService#hasAccess](https://github.com/it-at-m/digiwf-core/blob/cc8175e3ce0eaf5af4035a1bbde654384a200547/digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/digitalwf/service/instance/domain/service/ServiceInstanceAuthService.java#L63)

**To Reproduce**
1. Create multiple entries in database per user and process
2. check if person has access -> error

**Expected behavior**
Method is robust and accepts multiple entries (hasEntry / findFirst / findOne)

**Acceptance Criteria**

- [ ] ServiceInstanceAuthService kann mit mehreren Einträgen umgehen

**Comment by StephanStrehlerCGI** [comment]
Hallo, 
ich habe gerade den Bug versucht zu reproduzieren. hat nicht geklappt. 
Dafür habe ich mir das aber mal angeschaut und frage mich, ob da nicht eher ein unique contraint in der DB auf die Kombination aus User id und process instance id sinn ergibt. 
Rein fachlich (zumindestens laut createAuthorization) sollte das ja eigentlich unique sein. 

Wie siehst du das?

**Comment by lmoesle** [comment]
Ich habe den Fehler behoben, in dem ich den jpa query von find auf exists geändert habe (see #1082). @StephanStrehlerCGI hat aber recht, dass der Fehler in der Praxis nicht auftreten darf. Um den Fehler provozieren, muss man die DB direkt manipulieren, wir checken vor dem erstellen einer ServiceInstanceAuth, ob es sie schon gibt.
