### ISSUE TITLE
Deserialisierung von Dates in DMN klappt nicht mehr

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#483]
Dates mit dem Format "yyyy-mm-dd" können nicht mehr deserialisiert werden, wegen einer Spin-Exception.

Eventuell hängt das mit der Date-Format Anpassung zusammen

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/317

**Comment by darenegade** [comment]
Das verhindert den sauberen Import von Tasks daher Prio hoch

**Comment by darenegade** [comment]
@zambrovski Das wäre vielleicht ein gutes Thema für dich, wenn du heute noch was brauchst. Passt das?

**Comment by zambrovski** [comment]
Gibt es Beispiele für? Fehlermeldungen? Prozesse, bei den ich es nchvollziehen kann?

**Comment by darenegade** [comment]
Ja, im verlinkten internes Issue ;)

**Comment by darenegade** [comment]
Thema muss mit Prozessberater im DMN gelöst werden. Daher aktuell Done solange es kein Plattformthema ist
