### ISSUE TITLE
Unassigned Group-Tasks erscheinen bei "In Bearbeitung"

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#487]
**Describe the bug**
Unassigned Group-Tasks erscheinen bei "In Bearbeitung"

**To Reproduce**

Create Task with Candidate-Users (no Groups)

Aktuell unklar, da Group-Example geht

**Expected behavior**
Nicht zugewiesene Gruppen Aufgaben erscheinen nur bei Offen

**Screenshots**

![3e27cc92-9a58-4307-8d01-412e8001dc97.PNG](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/6990f373-8564-4043-9034-9b7b2725844e)

![bb784b40-8f42-4944-b6f5-b0e85d319969.PNG](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/cbaf9425-c0c6-4c60-b278-40ef5854ceb5)

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/320

**Comment by dominikhorn93** [comment]
Fehler gefunden: im "camunda:assignee" steht ein empty string.
Denke das ist noch ein "Bug" in einer bpmn.io Version, die wir im Modeler verwenden.
Das heben der Version löst aber nicht unser Problem.
Wir sollten damit umgehen können, dass im Assignee nicht nur null, sondern auch leere Strings stehen können.
