### ISSUE TITLE
Default-Werte bei Optionals können nicht gesetzt werden

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#488]
**Describe the bug**
Das Setzen eines Default-Werts für ein Optional Select Items in der CoCreation hat keine Auswirkung.

**To Reproduce**
Siehe internes Ticket

**Expected behavior**
Defaults können für Optional Select Items gesetzt werden

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/319

**Comment by lehju** [comment]
Wurde bereits in [#439](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-project/439) bearbeitet.
