### ISSUE TITLE
Cypress-Pipeline updaten

### ISSUE THREAD

**Issue by AnHo314** [it-at-m/digiwf-core#489]
**ToDo**: 

Proxyeinstellungen in der Gitlab-Pipeline mit Globalen-Envs setzen

**Idee**: 

Verwenden globaler Variablen, wie im GitLab Wiki hinterlegt

**Comment by darenegade** [comment]
@AnHo314 Hier geht es um die interne Pipe in Gitlab, richtig. Kannst du das GitlabWiki noch verlinken.

Ansonsten können wir das Thema gerne regulär einplanen oder du löst es direkt, je nachdem, wie hoch der Schmerz hier ist

**Comment by AnHo314** [comment]
Diese Variablen können in der Pipe gesetzt werden, um immer den aktuellsten Proxy in der Pipe zu haben:
https://git.muenchen.de/gitmuc/gitlab/-/wikis/Globale-Variablen

**Comment by AnHo314** [comment]
Zudem existiert 'image: dockerhub.muenchen.de/cypress/browsers' nicht mehr und muss ersetzt werden:
https://git.muenchen.de/ccse/cicd/sps/-/issues/493#note_628231
Ersetzt werden sollte es durch:
https://git.muenchen.de/ccse/cicd/sps/-/issues/493#note_625371
