### ISSUE TITLE
Write unit tests for digiwf-email integration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#49]
Describe the bug
No unit tests implemented.

To Reproduce
Look at code.

Expected behavior
Unit tests have to be written.

**Comment by darenegade** [comment]
dup https://github.com/it-at-m/digiwf-project/issues/404

**Comment by lmoesle** [comment]
I will create a few tests along with #50

**Comment by darenegade** [comment]
@lmoesle Das Issue hat @lehju übernommen
