### ISSUE TITLE
Custom S3 on Formserver-Integration

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#496]
**Is your feature request related to a problem? Please describe.**
Die [Formserver-Integration](https://git.muenchen.de/digitalisierung/digiwf-formserver-integration) schreibt fix immer in den DigiWF S3. Das führt zu Schwierigkeiten, wenn im Workflow ein eigener S3 verwendet wird

**Describe the solution you'd like**
Form-Server Config (BusniessContext) wird um S3-URL/UN/Pass erweitert, sodass man damit den Default überschreiben kann für spezifische Prozesse. Default bleibt der S3 von DigiWF, wenn keine Config angegeben.

**Describe alternatives you've considered**
Möglichkeit im Prozess anbieten Dateien von einem S3 in den anderen zu kopieren

**Akzeptanzkriterien**
* Custom-Document-Storage kann genutzt werden für spezifische Formulare
* Feature ist dokumentiert
* Ausgebracht auf allen Umgebungen (Ziel für Processes-* - 24.07.)

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/323

**Comment by simonhir** [comment]
Eine alternative S3-Service-URL sollte bereits gesetzt werden können siehe https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/blob/develop/digiwf-formserver-integration-core/src/main/java/de/muenchen/fktemplate/digiwf/processconfig/ProcessConfigProcessor.java#L44 und https://git.muenchen.de/digitalisierung/digiwf-ops/-/blob/dev/apps/digiwf-formserver-integration/service-config.yaml#L19.
Offen ist somit wahrscheinlich nur noch die aktuell fehlende Authentifizierung gegen die S3-Integration.

**Comment by darenegade** [comment]
Da die S3 Config schon in Bezug auf die URL umgesetzt ist, kann dies die Umsetzung etwas entspannen. Ich spreche mit der Anforderungsseite, sodass sie die Funktion aktuell schon auf einem Testsystem nutzen können ohne Auth. 

Auf Prod dann nur mit Auth

**Comment by simonhir** [comment]
Habe das jetzt lokal mal getestet und wie es genau funktioniert ist, dass aus der Engine die Prozess-Config geladen wird und in dieser nach dem S3-Service-URL-Key (`documentStorageServiceUrl`) gesucht wird.
Wenn dieser vorhanden ist wird entsprechend ein anderer S3 verwendet.

**Comment by simonhir** [comment]
TODO: Umsetzung S3 Authentifizierung

**Comment by lmoesle** [comment]
Das Feature ist schon implementiert und funktioniert auch schon. Man muss lediglich eine process config deployen und darin die `app_file_s3_sync_config` setzen. Wie man das einstellt steht auch schon in der Doku https://digiwf.oss.muenchen.de/modeling/processes/config/

Das einzige, was man noch machen müsste ist die config der Formserver Integration anzupassen. Über einen Konfigparameter kann das Feld gesetzt werden, nachdem in der process config gesucht wird. Die Formserver Integration holt sich die Processconfig (http request) von der Engine und sucht nach eben diesem Feld.

```
eogov.integration.digiwf.process-config.configKeyDocumentStorageServiceUrl=app_file_s3_sync_config
```

**Für Prozessmodellierer bedeutet das**

Sobald die Config in den Umgebungen angepasst ist muss für den jeweiligen Prozess eine Process Config deployed werden, in der die S3 Integration konfiguriert werden kann. z.B. (unter Value dann die richtig URL eintragen):

```json
{
  "key": "P10 Parkausweis beantragen",
  "statusDokument": "",
  "statusConfig": [],
  "configs": [
    {
      "key": "app_file_s3_async_config",
      "value": "dwf-s3-local-01"
    },
    {
      "key": "app_file_s3_sync_config",
      "value": "http://127.0.0.1:8086"
    }
  ]
}
```

**Comment by lmoesle** [comment]
**Weitere Todos**

- Version 0.18.0 von digiwf-core (insbesondere S3 Client) releasen
- MRs reviewen und mergen
  - Dev Umgebung einrichten: https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/9
  - S3 Client lifecyceln, refactoring und Configs anpassen https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/10
  - Ich habe ein Beispiel im S3 Client Example hinzugefügt für das synchrone Speichern von Dateien https://github.com/it-at-m/digiwf-core/pull/538
- Neue Version der Formserver Integration releasen und in den Umgebungen ausbringen

**FYI**: Die Authentifizierung zur S3 Integration geht immer noch nicht. Wir haben da schon ein extra Ticket #531, deswegen würde ich das erstmal noch lassen
