### ISSUE TITLE
Handle errors in digiwf-email integration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#50]
**Is your feature request related to a problem? Please describe.**
If an error occurs in the digiwf-email integration an error message should be returned to the process instance.

**Describe the solution you'd like**
The integration needs to distinguish between business errors and technical errors
Business errors needs to be delivered within the normal response
Technical errors needs to be delivered within an special error response

**Describe alternatives you've considered**
The error messages (technical and business) can be delivered within the same message, but the process needs to know if the job was successfull or not. On technical errors the job should stop and wait for retry (admin function)

**Tasks**

- Refactor integration to use the digiwf integration library (see #167)
- Define and document functional errors (in https://digiwf.oss.muenchen.de/integrations/)
- Throw functional errors in the integration
- Create example process

**More Information**

Business Error (BPMN Error): Validation
Technical Error (Incident): No Connection / Error-Code

**Comment by lmoesle** [comment]
Use StreamingTemplate V2 and implement error handling concept

**Comment by darenegade** [comment]
https://digiwf.oss.muenchen.de/integrations/error-handling/#fehlerhandling-der-integration

**Comment by darenegade** [comment]
@lmoesle Das Issue hat @lehju übernommen

**Comment by lmoesle** [comment]
**Fachliche Fehler**

| Error Code | Error Message | Beschreibung | Handlungsempfehlung |  
|---------------------------|------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|  
| `VALIDATION_ERROR` | Fehlermeldung der auftretenden `ValidationException` | Die übergebenen Email Daten sind nicht valide. | Korrigieren Sie die Daten und versuchen es erneut |  
| `MESSAGING_EXCEPTION` | Fehlermeldung der auftretenden `MessagingException` | Die Email konnte mit den übergebenen Daten nicht erstellt werden. | Überprüfen Sie, ob die Daten valide sind und versuchen es erneut. |  
| `MAIL_SENDING_FAILED` | Fehlermeldung der auftretenden `MailException` | Die Email konnte nicht versand werden. Es kann sein, dass die Email Adressen nicht valide sind oder ein technischer Fehler aufgetreten ist | Analysieren Sie die Fehlermeldung, korrigieren invalide Email Adressen und versuchen es erneut. |  
| `LOAD_FILE_FAILED` | An attachment could not be loaded from presigned url: attachment | Die Datei konnte nicht geladen werden | Stellen Sie sicher, dass die presigned Url nicht abgelaufen ist. Stellen Sie sicher, dass die Datei im S3 Bucket vorhanden ist |  
| `FILE_TYPE_NOT_SUPPORTED` | File type not supported of the attachment: attachment | Der Dateityp der Datei wird nicht unterstützt oder wurde nicht erkannt | Die Datei kann nicht als Email Anhang versendet werden. |
