### ISSUE TITLE
AppD Monitoring init

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#508]
**Is your feature request related to a problem? Please describe.**
We should use AppD as a new monitoring solution. 
For this we should configure AppD agent for all Java services in DigiWF-Ops.

**Describe the solution you'd like**

*  Configure AppD Init-Container in Java-Base
*  As AppD needs more Time to Start and more resources, we need to increase 
      *  readiness probe, e.g. 
      *  max RAM to 1500MB
* Dashboard and other Configs in AppD are not Part of this story  

**Describe alternatives you've considered**
Grafana - #493

**acceptance criteria**

* Every Java-Service is available in AppD

**Comment by simonhir** [comment]
Needs to be partly rolled back because the amount of agents exceeds the available AppD licenses.
