### ISSUE TITLE
Angaben zur Aufgabe werden nicht mehr angezeigt in "Description"

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#509]
**Describe the bug**
Description of Tasks missing

**To Reproduce**
Aktuell unbekannt

**Expected behavior**
Beschreibungen aller Tasks vorhanden

**Screenshots**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/327#gew%C3%BCnschter-zustand

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/327

**Comment by zambrovski** [comment]
Ich glaube wir müssen mit aktuellen Änderungen einfach nochmal die Prozedur "enrich" und "import" durchlaufen.

**Comment by darenegade** [comment]
Feature ist fertig und ausgerollt, aber I-Tests schlagen noch fehl

**Comment by lmoesle** [comment]
Ich habe den Hotfix #521 in den dev Branch gemerged und dafür den I-Test auskommentiert. Anschließend habe ich den I-Test wieder aktiviert. In #532 müssen wir jetzt nur noch den I-Test fixen, aber können auch schon zwischenzeitlich releasen
