### ISSUE TITLE
Dateienübergabe (bei mehrfachem Upload) von Onlineformular zu Digiwf klappt nicht

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#510]
**Describe the bug**
Vom Formserver können nicht mehrere Dateien übergeben werden

**To Reproduce**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/332#schritte-um-den-fehler-nachzustellen

**Expected behavior**
Es können mehrere Dateien übergeben werden

**Screenshots**
Siehe internes Ticket

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/332

**Comment by darenegade** [comment]
Thema muss noch verifiziert werden

**Comment by lmoesle** [comment]
MR: https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/11
