### ISSUE TITLE
Release Juli/August

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#511]
Release aus dem Sprint 19.06.-09.07.2023.
1. Anfang KW28 Release auf Demo und Testen
2. Fr 14.07. Release auf Processes-*
3. Fr 21.07. Release auf Prod

**Comment by darenegade** [comment]
Wir müssen die CoCreation ausbringen (Vorranging Formbuilder wegen #488 & #339). Wegen #339 habe ich den Workflow-Entwickler:innen Bescheid gegeben, dass wir es nun umstellen. Manuell kann man ja auf den alten zurück, wenn was nicht passt

**Comment by lmoesle** [comment]
Neue Version der Email Integration, Cosys Integration und S3 Integration releasen

**Comment by lmoesle** [comment]
Ich habe am 27.7 die Version 0.18.0 von digiwf-core released (Siehe: https://github.com/it-at-m/digiwf-core/actions/runs/5679076581).
Code Stand: https://github.com/it-at-m/digiwf-core/releases/tag/services_0.18.0

**Comment by lmoesle** [comment]
> Neue Version der Email Integration, Cosys Integration und S3 Integration releasen

- [ ] Nachdem das Released und die PRs in der Cocreation gemerged wurde (siehe Ticket https://github.com/it-at-m/digiwf-core/issues/338#issuecomment-1652150968), sollten wir auch die Cocreation aktualisieren.
- [ ] Die Formserver Integration sollte auch noch aktualisiert werden, sobald die PRs aus dem Ticket gemerged sind (ggf. auch erst im August): https://github.com/it-at-m/digiwf-core/issues/496#issuecomment-1652148148

**Comment by simonhir** [comment]
**TODOs**: 
- Durch Verschieben und Neu-Formatierung der S3-Flyway-Migration der S3-Integration hat sich die Checksum verändert und muss manuell in der DB von `-1494457576` auf `-1432048495` geändert werden.
- Var-Types Namespace anpassen siehe https://github.com/it-at-m/digiwf-core/issues/576#issuecomment-1672951167

**Comment by lehju** [comment]
Initiierung von AppD [#508](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/508) hat aktuell noch einen offenen MR https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/211
