### ISSUE TITLE
Sortierung konfigurierbar machen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#512]
**Is your feature request related to a problem? Please describe.**
Die Sort-Reihenfolge in den Listen sollten einstellbar sein, da es fachl. unterschiedlich ist, welche Reihenfolge richtig ist.

**Describe the solution you'd like**

* Sort Parameter (+ oder -) kann in dem Listen gesetzt werden
* Einstellung wird gespeichert im Localstorage über VueX
* Sortierung anhand von "Erstellt-Am"
* Sortierung nur über Task-Service (Engine API ignoriert den Parameter)
* Sort-Button sollte gut erkennbar sein als Drop-Down mit explizitem Text oder Icon mit Primary-Color
* Default Sort: Absteigend

**Describe alternatives you've considered**
Feste Sortierung vorgeben -> Ärger bei den SBs

**acceptance criteria**
* Aufsteigende und Absteigende Sortierung anhand des Datums kann in allen Listen (Meine Aufgaben, ~~Aktuelle Vorgänge~~, Offene Gruppenaufgaben, Gruppenaufgaben In Bearbeitung) eingestellt werden
* Eingestellte Sortierreihenfolge bleibt bestehen nach Reload

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/338

**Comment by lmoesle** [comment]
Was genau soll sortiert werden (nur die aktuelle Liste im Frontend oder was aus dem Backend kommt)?

**Comment by darenegade** [comment]
Sortierung erfolgt nur noch Backendseitig. Auf Teilmengen im Frontend zu sortieren macht wenig Sinn.

Um welche Listen geht es: Meine Aufgaben, Aktuelle Vorgänge, Offene Gruppenaufgaben, Gruppenaufgaben In Bearbeitung

**Comment by darenegade** [comment]
Aktuelle Vorgänge ausgeschlossen wegen #535
