### ISSUE TITLE
Changing the display number in "Vorgang Starten" results in an error

### ISSUE THREAD

**Issue by AnHo314** [it-at-m/digiwf-core#533]
**Describe the bug**
  - When increasing the number of displayed elements per page, an error occurs if this page should no longer exist after the change
  - after some time an error message can be seen

**To Reproduce**
  - Click on "Vorgang Starten"
  - Set page size 10 
  - go to the last page
  - change the page size to 20

**Expected behavior**
Number of pages is reduced and you are on an existing page.

**Screenshots**
![grafik.png](https://images.zenhubusercontent.com/647f2e8b4c6c5e291c8c7656/9778d38f-21a6-4666-afba-412863877b75)

**Desktop (please complete the following information):**
 - Start: local Docker
 - Browser [e.g. chrome, safari] Chrome/Firefox

**Comment by darenegade** [comment]
Dup #534
