### ISSUE TITLE
DB-Paging für Aktuelle Vorgänge

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#535]
**Is your feature request related to a problem? Please describe.**
Bei über 1000 aktuellen Vorgängen stößt das Backend auf einen Fehler 
"ORA-01795: maximum number of expressions in a list is 1000"

**Describe the solution you'd like**
* DB Abfrage per JPA (Siehe Kommentar Stephan)
   * Join der Tabellen und Suche per Index
   * unique constrains & Foreign Keys sollen in dieser Story erstmal nicht eingeführt werden (eigene Story)
   * Index anlegen für suchbare Spalten (Siehe [Mapper](https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/process/instance/api/mapper/ProcessInstancePageMapper.java#L53)
*  Tests für neue Abfrage

**Describe alternatives you've considered**
Siehe Kommentar Stephan

**Additional context**
https://github.com/it-at-m/digiwf-core/pull/465#issuecomment-1601523645

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/343

**Comment by darenegade** [comment]
Das Thema müssen wir im Ref. mal tiefer legen, da es nicht einfach ist und ich es techn. noch nicht durchdrungen habe. Siehe: https://github.com/it-at-m/digiwf-core/pull/465#issuecomment-1601523645

**Comment by darenegade** [comment]
Das Thema müssen @StephanStrehlerCGI und @darenegade nochmal gemeinsam besprechen

**Comment by StephanStrehlerCGI** [comment]
Ich habe mir die Sache nochmal in Bezug auf die Prozessinstanzen angeschaut. Aus meiner Sicht gibt es hier 2 Möglichkeiten. 

1. Batching der SQL Abfragen:
Wir nehmen das Ergebnis der processInstanceIds, splitten das in mehrere Arrays und machen getrennte Abfragen. 
Vorteil wäre ein geringer Eingriff in die Anwendung. 
Nachteil wäre ein hoher Arbeitsspeicherbedarf im Backend.

2. Umbau der Datenbankabfrage auf Join:
Wir Joinen die Datenbanktabellen und bauen ein Join. Hier bräuchten wir noch nicht einmal zwingend CriteriaQuery weil wir die Suche über normale Like Statements abbilden können. Insgesamt müsste SQL seitig dann folgendes SQL Statement rauskommen: 
SELECT * FROM DWF_PROCESS_INSTANCE_AUTH dpia LEFT JOIN DWF_PROCESS_INSTANCE_INFO dpii ON dpia.processinstanceid_ = dpii.processinstanceid_  WHERE dpia.userid_ LIKE 'user-1'; (sowie Pagination- und Queryinformationen)
Vorteil wäre hier die Performance. 
Nachteil der höhere Aufwand bis hinzu weiteren Datenbankmigrationen (Einführen von Indexen und Foreign Keys sowie möglichst unique constrains). Wir würden hier also recht viel anfassen wo wieder neue Risiken entstehen. 

Insgesamt ist mir nicht klar warum wir im ServiceDefinitionService in der startProcess Funktion in Camunda die Prozessinstanz Id als Prozessvariable brauchen. 
Würden wir das vermeiden, könnten wir uns viele Probleme sparen was nullable foreign keys angeht. Hier müssten wir noch einmal die Fachlichkeit untersuchen.

Des Weiteren ist mir aufgefallen, dass wir im ProcessInstanceInfoRepository Optional<ServiceInstanceEntity> findByInstanceId(String processInstanceId); definiert haben. Da auf der processInstanceId kein Unique Constraint definiert ist, kann das zu bösartigen Fehlern führen. 
Im RemovaltimeUpdateService rufen wir noch findAll() auf das ProcessInstanceInfoRepository auf. Das kann auch noch zu großen Performanceproblemen führen.

**Comment by StephanStrehlerCGI** [comment]
Ich habe mir die Sache nochmal in Bezug auf die Prozessinstanzen angeschaut. Aus meiner Sicht gibt es hier 2 Möglichkeiten. 

1. Batching der SQL Abfragen:
Wir nehmen das Ergebnis der processInstanceIds, splitten das in mehrere Arrays und machen getrennte Abfragen. 
Vorteil wäre ein geringer Eingriff in die Anwendung. 
Nachteil wäre ein hoher Arbeitsspeicherbedarf im Backend.

2. Umbau der Datenbankabfrage auf Join:
Wir Joinen die Datenbanktabellen und bauen ein Join. Hier bräuchten wir noch nicht einmal zwingend CriteriaQuery weil wir die Suche über normale Like Statements abbilden können. Insgesamt müsste SQL seitig dann folgendes SQL Statement rauskommen: 
SELECT * FROM DWF_PROCESS_INSTANCE_AUTH dpia LEFT JOIN DWF_PROCESS_INSTANCE_INFO dpii ON dpia.processinstanceid_ = dpii.processinstanceid_  WHERE dpia.userid_ LIKE 'user-1'; (sowie Pagination- und Queryinformationen)
Vorteil wäre hier die Performance. 
Nachteil der höhere Aufwand bis hinzu weiteren Datenbankmigrationen (Einführen von Indexen und Foreign Keys sowie möglichst unique constrains). Wir würden hier also recht viel anfassen wo wieder neue Risiken entstehen. 

Insgesamt ist mir nicht klar warum wir im ServiceDefinitionService in der startProcess Funktion in Camunda die Prozessinstanz Id als Prozessvariable brauchen. 
Würden wir das vermeiden, könnten wir uns viele Probleme sparen was nullable foreign keys angeht. Hier müssten wir noch einmal die Fachlichkeit untersuchen.

Des Weiteren ist mir aufgefallen, dass wir im ProcessInstanceInfoRepository Optional<ServiceInstanceEntity> findByInstanceId(String processInstanceId); definiert haben. Da auf der processInstanceId kein Unique Constraint definiert ist, kann das zu bösartigen Fehlern führen. 
Im RemovaltimeUpdateService rufen wir noch findAll() auf das ProcessInstanceInfoRepository auf. Das kann auch noch zu großen Performanceproblemen führen.

**Comment by StephanStrehlerCGI** [comment]
Ich habe mir die Sache nochmal in Bezug auf die Prozessinstanzen angeschaut. Aus meiner Sicht gibt es hier 2 Möglichkeiten. 

1. Batching der SQL Abfragen:
Wir nehmen das Ergebnis der processInstanceIds, splitten das in mehrere Arrays und machen getrennte Abfragen. 
Vorteil wäre ein geringer Eingriff in die Anwendung. 
Nachteil wäre ein hoher Arbeitsspeicherbedarf im Backend.

2. Umbau der Datenbankabfrage auf Join:
Wir Joinen die Datenbanktabellen und bauen ein Join. Hier bräuchten wir noch nicht einmal zwingend CriteriaQuery weil wir die Suche über normale Like Statements abbilden können. Insgesamt müsste SQL seitig dann folgendes SQL Statement rauskommen: 
SELECT * FROM DWF_PROCESS_INSTANCE_AUTH dpia LEFT JOIN DWF_PROCESS_INSTANCE_INFO dpii ON dpia.processinstanceid_ = dpii.processinstanceid_  WHERE dpia.userid_ LIKE 'user-1'; (sowie Pagination- und Queryinformationen)
Vorteil wäre hier die Performance. 
Nachteil der höhere Aufwand bis hinzu weiteren Datenbankmigrationen (Einführen von Indexen und Foreign Keys sowie möglichst unique constrains). Wir würden hier also recht viel anfassen wo wieder neue Risiken entstehen. 

Insgesamt ist mir nicht klar warum wir im ServiceDefinitionService in der startProcess Funktion in Camunda die Prozessinstanz Id als Prozessvariable brauchen. 
Würden wir das vermeiden, könnten wir uns viele Probleme sparen was nullable foreign keys angeht. Hier müssten wir noch einmal die Fachlichkeit untersuchen.

Des Weiteren ist mir aufgefallen, dass wir im ProcessInstanceInfoRepository Optional<ServiceInstanceEntity> findByInstanceId(String processInstanceId); definiert haben. Da auf der processInstanceId kein Unique Constraint definiert ist, kann das zu bösartigen Fehlern führen. 
Im RemovaltimeUpdateService rufen wir noch findAll() auf das ProcessInstanceInfoRepository auf. Das kann auch noch zu großen Performanceproblemen führen.

**Comment by darenegade** [comment]
@StephanStrehlerCGI Ich habe mir das mal angeschaut und ich denke, dass es schon eine einfachere Lösung gibt. Am Ende haben wir zwei Tabellen wobei die eine die Daten hält (`processInstanceInfoRepository`) und die andere die Zuordnung zu den Usern (`processInstanceAuthorizationRepository`). Von der letzteren werden alle IDs zu einem User geholt und dann per `findAllByInstanceIdIn` mit den Daten angereichert. Das erstere ist ein ganz normales `JpaRepository` und auf dem können wir doch ganz regulär das Paging machen und nur die jeweilige Page dann per `processInstanceInfoRepository.findAllByInstanceIdIn` um die Daten anreichern.

Ich verstehe nicht ganz, warum wir das Paging erst nach dem Daten anreichern machen, wo es davor so einfach ist. 😅 

Referenz: https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/process/instance/domain/service/ServiceInstanceService.java#L68

**Comment by darenegade** [comment]
Wir nehmen Lösung 2 von Stephan, da die Query erst auf den ProzessInstanceInfos erfolgt und somit ein Paging auf ProcessAuth nicht ausreicht
