### ISSUE TITLE
Enable renovate

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#537]
**Describe the solution you'd like**

Enable renovate for version updates and disable dependabot. 

**Additional Context**

- Enable Renovate (https://github.com/it-at-m/digiwf-core/pull/513)
- Disable Dependabot (See https://stackoverflow.com/a/71092696)
- Remove dependabot.yml

**Acceptance criteria**

- Dependabot is disabled for digiwf-core
- Renovate opens PRs for version updates

**Comment by darenegade** [comment]
Wir nutzen dependabot
