### ISSUE TITLE
Tag Tasks

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#542]
**Is your feature request related to a problem? Please describe.**

Wenn man für mehrere Prozesse und die zug. Tasks zuständig ist (Assignee oder Candidate), kann man in der UI diese nur schwer filtern/unterscheiden/trennen. 

Aktuell verwenden aus diesem Grund einige User die Speicherung von Suchen, um auf Prozess-/Tasknamen zu filtern.

**Describe the solution you'd like**

Es soll eine neue Prozess-/Taskvariable `app_task_tag` eingeführt werden, die eine Liste an Tags beinhalten kann, nach denen in der UI gefiltert werden kann. (Nicht mehr `app_task_tags`, damit zukünftig Listen nicht migriert werden müssen)

* Task-Backend bietet Filter auf Tag~~s~~ für alle Task-Listen 
* Für die Suche sollen im Backend die Polyflow Task-Filter genutzt werden (aktuell deaktiviert)
   * Abstimmung mit @zambrovski notwendig -> Am 14.08
        * Für Polyflow sollte die Liste aufgetrennt und einzeln in den Filtern gespeichert werden. Aber aktuell kann PLF nur auf einzelnen Variablen Suchen  ([FR bei PLF offen](https://github.com/holunda-io/camunda-bpm-taskpool/issues/854)) -> Daher können wir das Thema erstmal auf einen Tag begrenzen
* UI bietet neben Suche auch einen Filter auf Tag als Texteingabe
* Filter kann per Click auf Tag eines Tasks gesetzt werden
* Tag als Query-Param hinzufügen in der UI
* Tags werden in der UI auf den Aufgaben in der Liste angezeigt
* ~~Gestaltung der Liste aus Prozess-Sicht -> Kommasepariert~~ Keine Liste
    * Pattern für Element-Template hinterlegen, damit die Tag Namen auf "[-\w]*" eingeschränkt werden können
* Vorschlag über vorhandene Tags aus UI Sicht wird hier ausgeklammert, da größeres Thema 

**Describe alternatives you've considered**

Filterung auf Prozess-Typ -> Unflexibel und unspezifisch bei unterschiedlichen Tasks pro Prozess

**acceptance criteria**
* Im Prozess-Design kann am Task per Input-Var die neue Var gesetzt werden
* Tags werden in der UI an den Listen-Elementen angezeigt und User können danach Filtern

**Comment by dominikhorn93** [comment]
Woher weiß der User, welche Tags zur Verfügung stehen?
Ist das eine reine Texteingabe, die ohne Auswahl oder Autocomplete funktioniert?

**Comment by dominikhorn93** [comment]
Woher weiß der User, welche Tags zur Verfügung stehen?
Ist das eine reine Texteingabe, die ohne Auswahl oder Autocomplete funktioniert?

**Comment by LenaB34** [comment]
GitLab: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/282

**Comment by darenegade** [comment]
> Woher weiß der User, welche Tags zur Verfügung stehen?
> Ist das eine reine Texteingabe, die ohne Auswahl oder Autocomplete funktioniert?

Aus UX-Sicht wäre es natürlich gut, wenn die Filter eine Autocomplete auf den Labels hätten. Deswegen auch meine Frage wegen der Gestaltung der Liste. Idealerweise schaffen wir es anhand der User-Tasks und dessen Labels mit einem Distinct an so etwas zu kommen.

Die Labels an sich sollen aber frei wählbar von den Prozessberatern sein, um Aufgaben fachlich zu gruppieren. Das macht die Aufgabe etwas schwierig. Wir können gerne mal darüber ein Brainstorm machen 😊

**Comment by darenegade** [comment]
> GitLab: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/282

Bei dem Ticket geht es um den Prozess-Start (Vorgang starten). Das ist auch wichtig und müssen wir bei der Planung hier mitdenken, damit es eventuell kompatibel ist. Bevor wir jedoch nicht die Engine etwas aufgeräumte haben, würde ich gerne vermeiden noch mehr Features reinzupacken, die nicht dringend benötigt werden. Daher erstmal hier nur in Bezug auf Aufgaben.

**Comment by zambrovski** [comment]
See also https://github.com/holunda-io/camunda-bpm-taskpool/issues/854

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/542?planning-poker) with Zenhub @AnHo314 @darenegade @dominikhorn93 @lehju @simonhir @StephanStrehlerCGI
