### ISSUE TITLE
Support Timer/Message-Start Event

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#545]
**Is your feature request related to a problem? Please describe.**
Aktuell supportet die Plattform nur das Starten von Prozessen über die API oder per Kafka-Event. Timer-Events gehen zar grundsätzlich, aber das erfolgt nur Camunda intern und alle DigiWF-Meta-Daten werden nicht erzeugt (Config, Variablen, usw)

**Describe the solution you'd like**

Refactoring von `startInstance`, sodass für alle Prozess-Start-Logik ein EventListener greift

* Create Process-Instance Listener erstellen
   * Darf nur greifen, wenn der Prozess direkt gestartet wird und nicht als CallActivity/Sub-Prozess 
   * Logik gerne auf mehrere Listener auftrennen, sofern möglich
* Allgemeine Prozess Config aus den Services in den/die Listener auslagern
* Risiko: Eventuell sind Daten noch im Init-Thread nicht vorhanden
    * Wenn es eintritt muss Lösung gefunden werden und Story neu geschätzt 
* Listener Unit-Test schreiben
* Integrationstest mit Test-Prozessen (Mit und ohne Wait-States) und allen Start-Events
* Doku, was alles bei Prozess-Start passiert und wie Start-Events genutzt werden
 

**Describe alternatives you've considered**
Spezifische Listener nur für Timer-Events -> doppelter Code

**accenptance criteria**

- [x] None-/Message-/Timer-Events zum starten von Prozessen lösen gleiche Pre-Config der Prozesse aus
- [x] Spezifische Plattform Config von Prozessen ist dokumentiert (Was fügt DigiWF einem Prozess über Camunda hinaus hinzu)
- [x] Timer/Message Events sind dokumentiert (Wie ist das Format und wie kann man damit einen Prozess starten usw.)
- [ ] Workaround aus #1418 wurde entfernt und Fehler tritt nicht mehr auf

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/344
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/345
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/447

**Comment by darenegade** [comment]
Das Thema muss man vielleicht nochmal tiefer legen. Das ist aber eine gute Chance, um Logik zu Kapseln und besser zu testen

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/545?planning-poker) with Zenhub @darenegade @dominikhorn93 @simonhir @StephanStrehlerCGI

**Comment by darenegade** [comment]
@dominikhorn93 Das wäre eventuell noch ein Thema für dich, wenn dir die Arbeit ausgeht

**Comment by darenegade** [comment]
Hab das Thema von Dominik übernommen

**Comment by simonhir** [comment]
MR #1406 leads to following error when starting processes (i.e. Example-All-Input-Fields, Usertask)

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.camunda.bpm.engine.ScriptEvaluationException: Unable to evaluate script while executing activity 'Event_StatusGestartetUndBeschreibungSetzen' in the process definition with id 'example-all-input-fields:38:f4ecc66b-eb46-11ee-801d-88899d5a525c':java.util.NoSuchElementException: No value present] with root cause
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at de.muenchen.oss.digiwf.process.instance.process.ProcessFunctions.setDescription(ProcessFunctions.java:54)
```
