### ISSUE TITLE
S3-Integration health check not working

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#572]
The health-check called for digiwf-s3-integration-service via OpenShift returns 404 and so the readiness probe failes.
Container:
```
User externer.john.doe executed GET on URI /actuator/health with http status 404
```
OpenShift-Event:
```
Readiness probe failed: HTTP probe failed with statuscode: 404
Container application failed liveness probe, will be restarted
```

**Comment by darenegade** [comment]
Der John Doe kommt von hier:

https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-libs/digiwf-spring-security/digiwf-spring-security-core/src/main/java/de/muenchen/oss/digiwf/spring/security/SpringSecurityProperties.java#L24

Das ist uncool. Der John.Doe sollte nicht zum Default-User aufsteigen, sondern nur lokal relevant sein als Test-User

**Comment by darenegade** [comment]
![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/9b46861b-0416-47dc-8a69-6a1e53d7ac78)

**Comment by darenegade** [comment]
![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/17f4b797-c27e-42c7-ae02-2073c03f4aff)

https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-service/src/main/resources/application.yml#L98

**Comment by darenegade** [comment]
Für einen Fix muss man in DigiWF-Ops `SERVER_PORT` durch `S3_INTEGRATION_SERVER_PORT` austauschen

**Comment by darenegade** [comment]
Hab es im Release MR eingebaut: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/213/diffs?commit_id=90cc6df4ec4d6f788997cbd9e1e2abca39fa7eff

**Comment by darenegade** [comment]
Auf Review verschoben für Prüfung, dass Config richtig greift
