### ISSUE TITLE
Reaktivierung des alten Form-Builders

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#574]
**Is your feature request related to a problem? Please describe.**
Aktuell werden noch die alten Formulare unterstützt. Solange müssen wir auch noch die Möglichkeit unterbreiten diese, wenn auch eingeschränkt, bearbeiten  zu können (z.B. für HotFixes)

**Describe the solution you'd like**
Alten Form-Builder in Processes-* deployn: https://git.muenchen.de/digitalisierung/digitalwf-formbuilder
Hierzu muss das Deployment in DigiWF-Ops eingerichtet werden.

Da die alte Pipeline noch auf Jenkins aufsetzt muss manuell das JAR nach Openshift hochgeladen werden:
https://git.muenchen.de/digitalisierung/digitalwf-formbuilder/-/tree/develop/src/main/openshift

Teilweise müssen Envs angepasst werden und SpringBoot / Cloud braucht ein paar Updates. 

Redirect URLs in Client anlegen lassen (IBS53)

Hoffnung: APIs sind noch kompatibel. -> Abbruch wenn der Change hier zu lange braucht (Max 1Tag)

**Describe alternatives you've considered**
Auf das neue Formular "zwingen" -> Das geht nicht, solange die neue DMS-Int noch fehlt

**Additional context**

**Comment by darenegade** [comment]
@dominikhorn93 FYI

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/574?planning-poker) with Zenhub @StephanStrehlerCGI @dominikhorn93 @simonhir

**Comment by dominikhorn93** [comment]
https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/216

**Comment by michaeljacob77** [comment]
Unter welchen Links sind die FormBuilder in den Umgebungen processestest und -demo erreichbar?

**Comment by darenegade** [comment]
Habs dir per DM geschickt
