### ISSUE TITLE
TaskSchemaType Deserialization defekt

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#576]
Durch die Umbenennung der Namespaces funktioniert die Deserialisierung vom TaskSchemaType bei existierenden Tasks nicht mehr. Problem ist, dass die Ziel-Klasse in Camunda mit `io.muenchendigital.digiwf.task.TaskSchemaType` hinterlegt ist diese aber mittlerweile `de.muenchen.oss.digiwf.task.TaskSchemaType` heißt.

Dies führt sowohl beim Anzeigen als auch beim Enrichment zu Fehlern.

## Reproduktion
- Eigene Aufgaben anzeigen
oder 
- Enrichment ausführen

**Comment by darenegade** [comment]
Lösungsansatz 1:

Enrichment aufbohren, der diesen Change auf allen Tasks übernimmt.

Lösungsansatz 2:

Anzeige und Enrichment resilienter bauen. Dafür müsste man den Fehler genauer verstehen.

`Cannot deserialize object in variable 'app_task_schema_type': SPIN/JACKSON-JSON-01007 Cannot construct java type from string 'io.muenchendigital.digiwf.task.TaskSchemaType'`

Das Task-Backend kann schon mit beidem umgehen, da es hier nur ein String ist. In Bezug auf Camunda ist es vielleicht möglich dem Deserializer eine Hilfe zu geben.

**Comment by darenegade** [comment]
![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/af922b77-db22-4c22-9ee8-8d068182c451)

![image.png](https://images.zenhubusercontent.com/62f38045a2e3a269d82cb8b8/84e2fe21-4632-40bc-a52e-a7397c362e59)

Vielleicht reicht es dem Jackson hier Starthilfe zu geben

**Comment by darenegade** [comment]
Die Exception tritt hier erst auf, wenn versucht wird die Variable zu lesen. Das könnten wir auch robuster machen und die Exception fangen und dann den Wert einfach überschreiben über das Enrich.

https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-task/digiwf-polyflow-connector-starter/src/main/java/de/muenchen/oss/digiwf/task/listener/TaskSchemaTypeCreateTaskListener.java#L23

@simonhir  Kannst du das mal ausprobieren?

**Comment by simonhir** [comment]
Mit @zambrovski abgestimmte Lösung:
Anpassung der Engine DB:
```sql
Update act_ru_variable set text2_ = 'de.muenchen.oss.digiwf.task.TaskSchemaType'
where name_ = 'app_task_schema_type' and text2_ = 'io.muenchendigital.digiwf.task.TaskSchemaType';

Update act_ru_variable set text2_ = 'de.muenchen.oss.digiwf.legacy.user.domain.model.User'
where text2_ = 'io.muenchendigital.digiwf.legacy.user.domain.model.User';

commit;
```

Query zum Auflisten von Class-Variables:
```sql
Select v.name_, v.text_, v.text2_, utl_raw.cast_to_varchar2(dbms_lob.substr(b.bytes_)) from act_ru_variable v
join act_ge_bytearray b on b.id_ = v.bytearray_id_
where text2_ not like 'de.muenchen.oss.%' and text2_ is not null and text2_ not like 'java%' and text2_ not like '!%';
```

**Comment by darenegade** [comment]
Damit man es auf Test/Demo testen kann, stellen wir auf den DBs die Daten von Processes-* wieder her

**Comment by simonhir** [comment]
REQ0537651 für neue Schema und Datenübertragung für digiwf-test und digiwf-demo

**Comment by simonhir** [comment]
@zambrovski für `io.muenchendigital.digiwf.task.TaskSchemaType` und `io.muenchendigital.digiwf.legacy.user.domain.model.User` hat die obige Query perfekt funktioniert.

Jetzt schlägt das Enrichment aber mit folgender Fehlermeldung auf digiwf-demo mit den Daten von digiwf-processesdemo fehl:
```
ENGINE-16004 Exception while closing command context: ENGINE-03051 There was an exception while invoking the TaskListener. Message: 'Cannot deserialize object in variable 'Beschreibung_Korrektur_hinweis': SPIN/JACKSON-JSON-01006 Cannot deserialize '{"classNam...' to java type '[simple type, class jdk.nashorn.internal.runtime.Undefined]''

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "className" (class jdk.nashorn.internal.runtime.Undefined), not marked as ignorable (0 known properties: ])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: jdk.nashorn.internal.runtime.Undefined["className"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
```

Bei digiwf-test und den processestest Daten war das kein Problem, da würde ich mal schätzen ist der Task bereits fertig und wird deswegen nicht für das Enrichtment verwendet.

**Comment by simonhir** [comment]
Lösung für `jdk.nashorn.internal.runtime.Undefined`: Löschen der Prozess-Instanzen auf Processes-Demo
