### ISSUE TITLE
Migrate digiwf-document-storage-service artifact repositories to digiwf-core

### ISSUE THREAD

**Issue by martind260** [it-at-m/digiwf-core#59]
As a software developer I want to integrate the digiwf-document-storage-service into the digiwf-core monorepository to simplify maintenance.

**Tasks**

* Add internal gitlab integration artifact to the `digiwf-integrations/s3-integration` package as `digiwf-s3-integration-service`
* Configure `pom.xml`s to integrated the integration into the build mechanism
* `pom.xml` uses versions of shared packages from the parent (root pom in the digiwf-core)
* Setup Build Pipelines for docker images (append to this file https://github.com/it-at-m/digiwf-core/blob/dev/.github/workflows/release.yaml)
* configure digiwf-ops
* Migrate open issues from the repository to digiwf-core
* Archive old repository

**Criteria**

* Integration artifact is integrated into the digiwf-core monorepo
* Integration artifact is integrated into the build pipeline
* Issues are migrated to digiwf-core
* Old repository is archived
* Repository documentation is updated

**Comment by darenegade** [comment]
https://git.muenchen.de/digitalisierung/digiwf-document-storage-service
