### ISSUE TITLE
DMS-EAI: WSDL has changed

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#595]
**Describe the bug**
The WSDL of the **Test** MUCS-DMS has changed and is breaking so that the integration doesn't work anymore (Update Incoming)

**Expected behavior**
All used API-Endpoints schould work

[New WSDL from Fabasoft](https://github.com/it-at-m/digiwf-project/files/12368686/wsdl.zip)

**Warning**: 
Don't deploy this WSDL to Prod as the change isn't there yet - only Test

But if possible we should Deploy that Fix immediately to processes-* as major release

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/354

**Comment by darenegade** [comment]
https://git.muenchen.de/digitalisierung/digitalisierung-dms-eai/

**Comment by StephanStrehlerCGI** [comment]
EAI anpassen und wenn möglich in EAI Mapper bauen

**Comment by simonhir** [comment]
Interner MR für WSDL: https://git.muenchen.de/digitalisierung/digitalisierung-dms-eai/-/merge_requests/19

**Comment by simonhir** [comment]
Released and will be deployed to Processes-Test to be tested by Michael

**Comment by darenegade** [comment]
Rückmeldung:
Anscheinend geht der direkte Transform in der Camel-Route nicht.  Wir müssen daher wohl ein Mapping einbauen.

Ich schaue mir das Problem gerade noch genauer an

**Comment by darenegade** [comment]
Wir haben aktuell noch ein SOAP 1.1 auf SOAP 1.2 Problem. Stehe im Austausch mit dem DMS-Team

**Comment by simonhir** [comment]
Aktueller stand bis auf alle Processes deployed.
**Noch offen Deploy auf Prod am 17.11**
und evtl. zusammenhängender Fehler https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/400
