### ISSUE TITLE
Oracle to PostgreSQL Migration 

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#598]
**Is your feature request related to a problem? Please describe.**
We need a spike to test the migration from Oracle to Postgres

**Describe the solution you'd like**

* IBS Erfahrungen einholen wegen Migrations-Tool
* KM Erfahrung in der Regel mit Pentaho:
    * https://git.muenchen.de/swh/swh-migration
    * https://git.muenchen.de/bass/bass-migration
* Tools im Web recherchieren
    * z.B. von [Microsoft](https://learn.microsoft.com/en-us/azure/postgresql/migrate/how-to-migrate-from-oracle)
* Auf Test ausprobieren und Konzept für Migration erarbeiten 
* Neues Schema für PostgreSQL auf Test beantragen

Ziel für Processes-* & Prod: Eine PostgreSQL pro Service und Umgebung

**Additional context**
Siehe #581

**Comment by darenegade** [comment]
Spike Timebox: 2PT

**Comment by darenegade** [comment]
Beispiel aus BaSS: https://git.muenchen.de/bass/bass-migration

**Comment by simonhir** [comment]
Interne Anfrage an DB-Teams via ServiceNow: RITM0587452
Update: Keiner Erfahrung, da bis jetzt immer applikationsspezifisch gelöst, aber helfen gerne bei Fragen oder Problemen

**Comment by simonhir** [comment]
Ergebnis: Nachdem mit Pentaho die meiste Erfahrung vorhanden soll dieses für #581 genutzt werden
