### ISSUE TITLE
Aktuelle Vorgänge keine Sortierung

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#601]
Die Vorgänge unter "Aktuelle Vorgänge" scheinen aktuell nicht sinnvoll sortiert zu sein.
Grund dafür ist Vermutlich die neu eingebaute Pagination für diese Seite. Siehe https://github.com/it-at-m/digiwf-core/pull/465

## Akzeptanzkriterien
- Vorgänge werden von Neu nach Alt sortiert angezeigt
- Ausbringung als Hotfix für #511

**Comment by darenegade** [comment]
Die Anfrage ans Backend ist noch das Gleiche (Vergleich Prod mit Processes)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb5639bd82e691bc0fffcc5c0bde7c766678cea3/image.png)


Muss also ein Backend Thema sein. Hat sich hier wieder der Name der Variable geändert? Wurde die polyflow Version geändert?

**Comment by darenegade** [comment]
Irgendwas ist komplett kaputt gegangen

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjhnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--458bc28607b297eda9579302ca0a7057b4f90526/image.png)

**Comment by darenegade** [comment]
Mit `+createTime` ändert sich das Ganze wieder:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1VnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e781c8870a8655c5965ba412e26a8e3db7e4779e/image.png)

Warum hat sich den hier die Richtung geändert🤔

**Comment by darenegade** [comment]
Nach Doku Polyflow bedeutet `-` descending 

https://www.holunda.io/camunda-bpm-taskpool/snapshot/reference-guide/components/view-api.html#filtering-paging-and-sorting

**Comment by darenegade** [comment]
Der Sort war vorher im Frontend und ist deswegen rausgeflogen:

https://github.com/it-at-m/digiwf-core/blob/6e39e84f314579b0f677258d862c0bd8a56750c4/digiwf-apps/packages/apps/digiwf-tasklist/src/store/modules/processInstances.ts#L29

Nun hätte man es im Backend machen müssen 🙈

**Comment by darenegade** [comment]
Lösung 1: QuickFix indem Sort auf dem Branch noch eingebaut wird.

Lösung 2: DB-Paging isoliert reinbringen in den Branch als Hotfix

**Comment by darenegade** [comment]
Ergebnis Diskussion Daily: QuickFix soll umgesetzt werden und wir müssen für die neue Lösung überprüfen, ob diese sortiert werden.
