### ISSUE TITLE
Email attachments not openable

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#616]
Attachments sent via s3 and mail-integration can't be opend with following error i.e. for PDFs:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGc1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc569baffbbf34c81607fa4fb22d48d3a43ba8d8/image.png)
When accessing the file directly via s3 the file can be opened.

A bit suspicious is also that the s3 example process directly writes the cosys document into `/test` instead of `/<proc-id>/test` but could also be a process definition mistake.

## Reproduce
- Run i.e. the s3-integration example process
- Cosys document is generated and placed in s3
- Document is sent via email
- Document can't be opened from the mail but in the s3

## Acceptance criteria
- Mail attachments can be opened as intended

**Comment by lmoesle** [comment]
@simonhir Ich habe den Fehler gefunden und behoben. Beim Anhängen der Dateien an der Email wurden die Datentypen falsch erkannt.

Ich teste meine Lösung gleich noch mit ein paar mehr Dateitypen und schreibe noch einen Test zu dem Bug
