### ISSUE TITLE
Nach Bearbeiter*innen filtern

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#629]
Die Suche nach Bearbeiter*innen unter Gruppenaufgaben in Bearbeitung funktioniert nicht mehr. Es kann nur nach Aufgaben-Titel und Beschreibung gesucht werden.
Wahrscheinlich funktioniert dies seit dem Umstieg auf das neue Tasklist-Backend schon nicht mehr.

## ToDo

* Es soll ein Bearbeiter Filter eingeführt werden (User-Select)
     * Keine Einschränkung auf Personen 
* Damit die Filter übersichtlich bleiben, soll eine neue Filterfunktion eingebaut werden
     * Filter Button mit Öffnung DropDown
     * Tag und Bearbeiter feste Filter im DropDown
     * Beim Zuklappen sollen Filter-Chips angezeigt werden, die gelöscht werden können 
     * Filter analog zur Suche und Tag in der Session gespeichert (RAM)
* Annahme: Polyflow kann bei GroupTasks nach Bearbeiter filtern 

## Akzeptanzkriterien
- Es kann sowohl wie aktuell nach Titel und Beschreibung, aber auch wieder nach Bearbeiter gesucht werden.

**Additional Context**

* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/362
* https://adresssuche-test.muenchen.de
 
## Abgrenzung
- Die Komponente für die Auswahl der Benutzer wird so wie die heute in den Formularen verwendet wird, genutzt. Die Versorgung mit Benutzern (aus LDAP) wird über die Engine realisiert (bestehende legacy User SST). In der Zukunft wird diese Schnittstelle separat von der Engine bereitgestellt. Dazu gibt es später eine neue Story.
-

**Comment by darenegade** [comment]
Hier ein Beispiel für Filter:

https://adresssuche-test.muenchen.de

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/629?planning-poker) with Zenhub @darenegade @lmoesle @simonhir @StephanStrehlerCGI
