### ISSUE TITLE
Lifecycle spring boot autoconfigurations

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#634]
**Describe the solution you'd like**

With Spring-Boot 2.7 the spring auto configuration location moved from `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`.  We should adjust our auto configurations to the new format.

For more information checkout the Spring Boot Release Notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration

**Comment by darenegade** [comment]
We should upgrade to SB3 in a near future. We should discuss this in the refinement

**Comment by lmoesle** [comment]
With Spring Boot 3 the support for `spring.factories` is dropped, so this is preparation we should do before migrating (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files)

**Comment by darenegade** [comment]
I know. But this is not the only thing we should consider when preparing for SB3 and therefore discuss the whole path to SB3 within the refinement.

Additional Infos to SB3 Migration: 

* https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#before-you-start

* https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/wikis/Migrationsguide-Spring-Boot-3-&-Java-17

**Comment by darenegade** [comment]
Wird direkt bei der Hebung auf SB3 mitgemacht in den einzelnen Umstellungen
