### ISSUE TITLE
Remove digiwf-asyncapidocs from digiwf

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#647]
**Is your feature request related to a problem? Please describe.**

We have for some digiwf-services a asyncapi documentation that is automatically created with [digiwf-asyncapi-docs](https://github.com/it-at-m/digiwf-asyncapi-docs).

The project [digiwf-asyncapi-docs](https://github.com/it-at-m/digiwf-asyncapi-docs) is not needed anymore, after springwolf now supports spring cloud functions out of the box (e.g. https://github.com/springwolf/springwolf-core/tree/master/springwolf-examples/springwolf-cloud-stream-example)

**Describe the solution you'd like**

We should remove the [digiwf-asyncapi-docs](https://github.com/it-at-m/digiwf-asyncapi-docs) library from our services and archive the github repository ([digiwf-asyncapi-docs](https://github.com/it-at-m/digiwf-asyncapi-docs))

**Describe alternatives you've considered**

Migrating the library to our monorepo and using it in our services (see https://github.com/it-at-m/digiwf-project/issues/413).

**Additional context**

- The library is used in the digiwf-engine
- Only remove the library from services in our monorepo

**Todos**

- archive [digiwf-asyncapi-docs](https://github.com/it-at-m/digiwf-asyncapi-docs) project
- remove the libary from digiwf-engine (pom.xml, java code (Annotations, Configration), application.ymls)
- make sue other services don't use it (in our monorepo)

**Comment by lmoesle** [comment]
I assume that asyncapi docs is a feature that is not used heavily and therefore we could remove it safely. Should we use it in the future again we could implement [Springwolf](https://www.springwolf.dev/).

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/647?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI

**Comment by lmoesle** [comment]
Repo https://github.com/it-at-m/digiwf-asyncapi-docs habe ich archiviert.
