### ISSUE TITLE
Setup AppD Kafka

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#658]
Configure AppD to detect Kafka communication correctly based on #493 and #508

## References
- https://docs.appdynamics.com/appd/22.x/latest/en/application-monitoring/configure-instrumentation/backend-detection-rules/java-backend-detection/apache-kafka-consumer-backends

**Comment by simonhir** [comment]
AppD-Support-Issue: http://help.appdynamics.com/hc/requests/368377

**Comment by darenegade** [comment]
@simonhir Was ist hier der Stand? Können wir das schließen?

**Comment by simonhir** [comment]
@darenegade bin da aktuell noch an der Klärung ob man das in ein anderes Projekt verlegen kann ohne, dass der bereits investierte Aufwand verloren geht. Würde das derweilen hier liegen lassen.

**Comment by simonhir** [comment]
Der Fokus liegt in nächster Zukunft mehr auf dem Ausbau von Grafana, deshalb wird AppD vorerst ausgebaut und nicht weiter verfolgt.
MR für den Ausbau: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/399
