### ISSUE TITLE
Fab-EGov-Integration: Search Sachakte

### ISSUE THREAD

**Issue by lehju** [it-at-m/digiwf-core#662]
**Is your feature request related to a problem? Please describe.**
Mit der neuen Fabasoft-EGov-Integration (digiwf-dms-integration) soll es möglich sein eine Sachakte zu suchen.

**Describe the solution you'd like**
-	Neue Bean im MessageProcessor definieren
-	Neuen UseCase erstellen
-	FabasoftAdapter erweitern
-	Element-Template für Benutzung in BPMN anlegen
    -	Parameter: Sachakten-Suche, Untergruppe, User
    -   Offen/Zu Prüfen: Was passiert mit dem Output-Mapping der `sachakteCoo`, wenn keine Akte gefunden wird (null Ergebnis aus Integration) 
        - Diskussion Ute/Michael: Leere Liste soll zurück kommen   
-	Funktion dokumentieren
-	Integrationstests

- Wenn keine Sachakte gefunden wird, wird ein BPMN Error geworfen
- Wenn mehrere Sachakten gefunden werden, ~~dann wird in der alten Int. einfach die erste genommen~~
   -  Kurze Abstimmung mit DMS-Team bzw. Ute/Michael, ob das Vorgehen so okay ist
       - Ergebnis: Nein, es soll die Liste durchgereicht werden, sodass entweder in einem User-Task die richtige Akte ausgewählt werden kann oder der Prozess per Logik entscheidet, ob und welcher Fehler geworfen wird bzw. einfach die erste ausgewählt wird  

**Describe alternatives you've considered**
-	Aus einem Prozess kann eine Sachakte gesucht werden
-	Die Funktion und dessen Benutzung ist dokumentiert
-	Fehler werden als Incident oder BPMN Error gemeldet

**Additional context**
Aktuelle Umsetzung in der Engine:
https://github.com/it-at-m/digiwf-core/blob/7a4aba5224b9008e46a7da885104e23c8838eb1d/digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/legacy/dms/muc/process/searchsachakte/SearchSachakteDelegate.java#L40

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/662?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI

**Comment by dominikhorn93** [comment]
public Sachakte createSachakte(final String sachakteTitel, final String aktenplanName, final String userId) throws Exception {
        val username = this.getUsername(userId);
        val aktenPlanCoo = this.searchObjectWithUser(aktenplanName, DMSObjectClass.Aktenplaneintrag, username);
        val sachakte = new NeueSachakte(aktenPlanCoo, sachakteTitel);
        final Sachakte result = this.dmsClient.createSachakteWithUser(sachakte, username);
        log.debug("Sachakte created: {}", result.getCoo());
        return result;
    }

Suche nach Aktenplan muss zusätzlich umgesetzt werden in diesem Ticket.
