### ISSUE TITLE
Fab-EGov-Integration: Cancel Object

### ISSUE THREAD

**Issue by lehju** [it-at-m/digiwf-core#663]
**Is your feature request related to a problem? Please describe.**
Mit der neuen Fabasoft-EGov-Integration (digiwf-dms-integration) soll es möglich sein ein Objekt zu stornieren.

**Describe the solution you'd like**
-	Neue Bean im MessageProcessor definieren
-	Neuen UseCase erstellen
-	FabasoftAdapter erweitern
-	Element-Template für Benutzung in BPMN anlegen
    -	Parameter: (Dokument-, Vorgang-)COO, User
- Testen ob alles oder nur Dokument stornierbar ist
-	Funktion dokumentieren
-	Integrationstests (Mock - mögliche Fehlermeldung überprüfen)

**Describe alternatives you've considered**
-	Aus einem Prozess kann eine Dokument storniert werden
-	Die Funktion und dessen Benutzung ist dokumentiert
-	Fehler werden als Incident oder BPMN Error gemeldet

**Additional context**
Aktuelle Umsetzung in der Enginge:
https://github.com/it-at-m/digiwf-core/blob/7a4aba5224b9008e46a7da885104e23c8838eb1d/digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/legacy/dms/muc/process/canceldokument/CancelDokumentDelegate.java#L40

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/663?planning-poker) with Zenhub @AnHo314 @darenegade @dominikhorn93 @lehju @lmoesle @simonhir @StephanStrehlerCGI @zambrovski
