### ISSUE TITLE
Fab-EGov-Integration: Read Schriftstueck (List of COOs)

### ISSUE THREAD

**Issue by lehju** [it-at-m/digiwf-core#664]
**Is your feature request related to a problem? Please describe.**
Mit der neuen Fabasoft-EGov-Integration (digiwf-dms-integration) soll es möglich sein ein Schriftstück zu lesen.

**Describe the solution you'd like**
-	Neue Bean im MessageProcessor definieren
-	Neuen UseCase erstellen
-	FabasoftAdapter erweitern
-	Element-Template für Benutzung in BPMN anlegen
    -	Parameter: Schriftstück, User
-	Funktion dokumentieren
-	Integrationstests (Mock - mögliche Fehlermeldung überprüfen)

**Describe alternatives you've considered**
-	Aus einem Prozess kann ein Schriftstück gelesen werden (Datei/en wird im S3 abgelegt)
-	Die Funktion und dessen Benutzung ist dokumentiert
-	Fehler werden als Incident oder BPMN Error gemeldet

**Additional context**
Aktuelle Umsetzung in der Enginge:
https://github.com/it-at-m/digiwf-core/blob/7a4aba5224b9008e46a7da885104e23c8838eb1d/digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/legacy/dms/muc/process/readschriftstueck/ReadSchriftstueckeDelegate.java#L43

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/664?planning-poker) with Zenhub @darenegade @AnHo314 @dominikhorn93 @lmoesle @lehju @simonhir @StephanStrehlerCGI @zambrovski

**Comment by dominikhorn93** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjBZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d4b5276cc855a398f71b7294f33618276123e06/Bildschirmfoto%202023-10-09%20um%2016.26.28.png)
