### ISSUE TITLE
Fab-EGov-Integration: Create Dokument (Cosys Erstellung)

### ISSUE THREAD

**Issue by lehju** [it-at-m/digiwf-core#668]
**Is your feature request related to a problem? Please describe.**
Mit der neuen Fabasoft-EGov-Integration (digiwf-dms-integration) soll es möglich sein ein Dokument zu erstellen.

**Describe the solution you'd like**
-	Bean im MessageProcessor erweitern
-	UseCase erweitern
-	FabasoftAdapter erweitern
-  CosysAdater erstellen
-	Template für Benutzung in BPMN anlegen
    - Parameter: Vorgang-COO, Titel, User, Ein-/Ausgehend/Intern, Cosys-GUID
-	Funktion dokumentieren
-	Integrationstests

**Describe alternatives you've considered**
-	Aus einem Prozess kann ein Dokument erstellt werden
-	Die Funktion und dessen Benutzung ist dokumentiert
-	Fehler werden als Incident oder BPMN Error gemeldet

**Additional context**
Aktuelle Umsetzung in der Enginge:
https://github.com/it-at-m/digiwf-core/blob/7a4aba5224b9008e46a7da885104e23c8838eb1d/digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/legacy/dms/muc/process/createdokument/CreateDokumentDelegate.java#L58

**Comment by darenegade** [comment]
Für die DMS soll zukünftig nur noch S3 angeboten werden, damit wir einen einheitlichen Übergabeweg haben. CoSys soll dies auch nutzen. Daher geschlossen
