### ISSUE TITLE
Neue Integration Address-Service

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#672]
**Is your feature request related to a problem? Please describe.**
Im Projekt Parkraummanagement wurden diverse neue Integrationen entwickelt, die nun in die Plattform überführt werden sollen, um sie auch anderen Prozessen bereitstellen zu können. All diese Integrationen waren im Projekt schon in Betrieb und wurden bereits über längere Zeit dort verwendet.

Hier geht es um die Address-Service Integration: https://github.com/it-at-m/digiwf-core/pull/620

**Describe the solution you'd like**

* Review des Codes und der Dokumentation
* Gemeinsam mit dem Contributor offene Punkte und dringend notwendige Refactorings durchführen
   * Error-Handling, Code-Split, DigiWF-Libs auf aktuellem Stand ? 
   * Bei größeren ToDos neue Issues erstellen
* Betrieb von der Address-Service Integration wird von DigiWF Plattform übernommen, daher müssen entsprechende Depl. in digiwf-ops erstellt werden
* Element-Templates über die Plattform bereitstellen
* Auf einheitliche Englische Sprache umstellen

**Additional context**
https://github.com/it-at-m/digiwf-core/pull/620

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/672?planning-poker) with Zenhub @AnHo314 @darenegade @dominikhorn93 @lehju @lmoesle @simonhir @StephanStrehlerCGI @zambrovski

**Comment by lmoesle** [comment]
**Offene Todos**

- Unit und Integrationtests erstellen
- (Optional) Einen API Mockservice erstellen mit Wiremock
- Javadoc erstellen
- Element Templates erstellen und releasen
- Example Prozess erstellen
- Address Integration in CAP deployen

Ich schaue mir die offenen Todos an, wenn ich wieder da bin

**Comment by lmoesle** [comment]
PRs:

- https://github.com/it-at-m/digiwf-core/pull/620
- Element Templates: https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/55
- Ops: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/261
