### ISSUE TITLE
Build all applications with a single command

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#69]
It would be easier to develop the digiwf-core if we could build all application with a single command (e.g. `mvn clean install`). The cicd pipelines would also benefit from the single command usage and reduce the steps needed to build the entire application.

Therefore, we could include the frontends (`digiwf-apps`)  and the docs (`digiwf-docs`) into the maven build cycle with the [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/).

### Tasks

* Include the [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/) into the parent `pom.xml` and trigger `npm install` and `npm run build` in the digiwf-apps and digiwf-docs applications
* Use the single build command in the github actions
    * Setup node and java
    * Trigger the maven command
    * release the node packages and release the java packages
* (Optional) Trigger frontend tests with the [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/) too

**Comment by darenegade** [comment]
Wurde schon erledigt
