### ISSUE TITLE
Multi-User-Input returns objects instead of userid sometimes

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#701]
The multi-user-input sometimes returns a array of user objects instead of userids.

Correct: `["123456789","123123123"]`
Wrong: `[{"forename":"", "surname":"","ou":"","lhmObjectId":"123456789",...}, ...]`

See internal issue https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/369

**Comment by StephanStrehlerCGI** [comment]
Feld in JSON Form: 
           "Gruppenreise_Teilnehmer": {
                                            "fieldType": "multi-user-input",
                                            "title": "Wer nimmt an der Reise teil?",
                                            "x-display": "custom-multi-user-input",
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            },
                                            "key": "Gruppenreise_Teilnehmer",
                                            "default": [],
                                            "x-options": {
                                                "fieldColProps": {
                                                    "cols": 12,
                                                    "sm": 12,
                                                    "messages": {}
                                                }
                                            },
                                            "x-props": {
                                                "outlined": true,
                                                "dense": true
                                            },
                                            "minItems": 1
                                        },
