### ISSUE TITLE
Alternativtext für Buttons

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#715]
**Is your feature request related to a problem? Please describe.**

Um die Barrierefreiheit der App zu steigern sollten Aktionen auch über Screenreader identifizierbar sein.

**Describe the solution you'd like**

* Einschränkung auf Aktionen (Buttons, Inputs) der Taskliste, nicht Forms
* Alle Aktionen (Abschließen, Aktualisieren, usw.) und Menüs (Aktionen, Avatar, Seitennavigation, usw) mit A-Texten versehen

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/371

**Tools**
install SiteImprove chrome extension

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/715?planning-poker) with Zenhub @darenegade @lmoesle @simonhir @StephanStrehlerCGI

**Comment by zambrovski** [comment]
Issues to fix:

- [ ] Search field: Form field is not labeled, aria-label seems to be not identified correctly (the div is a control)
- [ ] Search filed with data: aria-role="combobox", aria-expanded="true", but aria-controls are not set (the div is a control...)
- [ ] Assign group task: Form field is not labeled, aria-label seems to be not identified correctly (the div is a control)

**Comment by StephanStrehlerCGI** [comment]
TODO:  Open Issues in extra Ticket auslagern
