### ISSUE TITLE
MultiFile Input geht nicht f. Prozess-Start

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#719]
**Describe the bug**

MultiFile Input geht nicht f. Prozess-Start. Es wird kein Request abgeschickt und geht direkt auf failed.

**To Reproduce**
1. Go to https://digiwf-demo.muenchen.de/#/process/email-example-V02_3fe75308-ab8c-410d-a09b-2b4b856c15fd

**Expected behavior**
Dateien lassen sich hochladen 

**Additional context**

**Comment by darenegade** [comment]
Hängt eventuell damit zusammen, dass dem Input die API fehlt (Rückbau Feature Toggle?)

https://github.com/it-at-m/digiwf-core/pull/709

**Comment by darenegade** [comment]
Muss als Hotfix auf Processes ausgebracht werden

**Comment by simonhir** [comment]
Wird mit #708 gefixt und läuft auch mit s3-Integration auf no-security
