### ISSUE TITLE
User is not resolved in Cockpit / Admin on stages (dev, test, ...)

### ISSUE THREAD

**Issue by zambrovski** [it-at-m/digiwf-core#724]
Observed:
- LHMObjectId is shown
![image](https://github.com/it-at-m/digiwf-core/assets/14137977/f87e707c-abd1-46c2-8703-936723695c11)

Expected:
- First name, last name, email address

**Comment by zambrovski** [comment]
Probably, this is because of the token on the DEV / TEST stage, since we get defaults (lhmObjectId). This rule applies if the token has no claims for given_name, first_name and email. @lmoesle will verify it in the stages...

**Comment by lmoesle** [comment]
Im ssodev fehlen `given_name`, `family_name` und `email` im Token. Lokal und auch im ssotest stimmen die Tokens überein. Um das Problem zu lösen, müssen wir den Token im ssodev anpassen, falls das möglich ist.

**Comment by simonhir** [comment]
The Problem is that on SSO-Dev for non of us the above mentioned attributes are set.
I set them for me and now it works without a problem.
So not a bug more like misconfiguration on SSO-Dev as on the other SSOs the attributes are filled automatically.
