### ISSUE TITLE
Synchrone Anbindung eines domänen spezifischen S3 Storages für Integrationen

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#734]
**Kontext**

Wenn eine Integration mit dem S3 Storage interagieren muss, dann werden in einem eigenen Prozessschritt zuerst PresignedUrls erzeugt und anschließend an die Integration übergeben.

<img width="151" alt="grafik" src="https://github.com/it-at-m/digiwf-core/assets/37705369/d0821c7d-5ee8-46e7-8c88-5f1d08b9c929">

Hierbei kann in der Prozesskonfiguration eingestellt werden, welche S3 Integration verwendet werden soll:

```json

{
  "key": "MeinProzessKey",
  "statusConfig": [  ],
  "configs": [
    [...]
    {
      "key": "app_file_s3_sync_config",
      "value": "http://my-document-storage-service:8080"
    },
      {
      "key": "app_instance_schema_key",
      "value": "myschemakey"
    },
    [...]
  ]
}
```

Wenn man jetzt in einer Integration synchron (also ohne PresignedUrls) auf den S3 Storage zugreifen möchte, dann muss die Prozessconfig synchron aus der Engine geladen werden. Hierfür haben wir die digiwf-process-api erweitert (see 8f76fe04fb2c563fea1073193fa2546637e99425).

**Problem:**

Das Problem hierbei ist, dass die Integration keine Möglichkeit hat an den ProcessDefinitionKey zu kommen und deswegen die Bibliothek nicht nutzen kann.
Der Hintergrund hierbei ist, dass die Integration über die CallActivity StreamingTemplateV02 aufgerufen wird und dementsprechend vom digiwf-connector die ProcessInstanceId von der CallActivity übergeben wird. Wir benötigen jedoch die ProcessInstance vom aufrufenden Prozess.

Note: Den Connector können wir mit wenig Aufwand anpassen, dass neben ProcessInstanceId auch ProcessDefinitionKey und ProcessDefinitionId weitergegeben werden. Hier besteht aber dasselbe Problem.

**Describe the solution you'd like**

Wir können die ProcessDefinitionId bzw. ProcessDefinitionKey (des aufrufenden Prozesses) als Prozessvariablen an die CallActivity (StreamingTemplateV02) weitergeben und im digiwf-connector auslesen und als Kafka Header an die Integration übergeben.

**Describe alternatives you've considered**

Die Konfigurationen für den domänen spezifischen S3 aus der Prozessconfig könnten wir bei Prozessstart auslesen und als Prozessvariablen global speichern und durch den Prozess schleifen.

- Vorteil: Integration muss nicht noch extra die Prozessconfig laden (1 Rest call weniger)
- Nachteil: Wir müssten das für jede DigiWF Config machen -> In Zukunft könnte das noch mehr Configs betreffen

## Acceptane criteria 

- [ ] Neuer Header mit Root-ProzessDef-Key `digiwf.processdefinition` geht über Connector an die Integrationen

**Comment by dominikhorn93** [comment]
Finde das soweit passend.
Eventuell könnten wir uns aber davor über das Thema "Bundle" Gedanken machen und schauen ob wir das schon damit kompatibel umsetzen können. @darenegade was meinst du?

**Comment by darenegade** [comment]
Ich würde hier gerne nochmal die Alternativen durchgehen. Vielleicht können wir das einfach nach einem Daily mal gemeinsam machen 😊

**Comment by darenegade** [comment]
Hängt auch mit #468 zusammen (Hier als Alternative Lösung)

**Comment by lmoesle** [comment]
Das Ticket ist auf impediment, bis wir das Vorgehen geklärt haben

**Comment by darenegade** [comment]
## Abstimmung zur Lösung 15.01.

Fachliche Definition: Es gilt immer die Konfig. vom obersten Prozess. Dieser Key soll an die Integrationen weitergereicht werden, sodass diese damit z.B. Configs nachladen können. Es erfolgt kein Merge oder Überschreiben von Configs auf Sub-Prozessen

**Comment by darenegade** [comment]
Mögliche Lösung: Der Connector lädt den Key nach

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/734?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI @zambrovski

**Comment by lmoesle** [comment]
PR ist auch #1168
