### ISSUE TITLE
Lifecycle docs to run with nodejs 20

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#754]
Currently the docs do not run with nodejs 20 The error `Error: error:0308010C:digital envelope routines::unsupported` appears if you run `npm run dev` with nodejs 20.

**Todos**

- Fix the error `Error: error:0308010C:digital envelope routines::unsupported`
- Lifecycle vuepress dependencies
- Raise nodejs Version in Github Actions Pipelines (build and release)

**Comment by darenegade** [comment]
We don't have vuepress 0.x

https://github.com/it-at-m/digiwf-core/blob/feat/662-search-sachakte/docs/package.json#L13C1-L14C1

**Comment by darenegade** [comment]
Hier ein Fix für den Übergang

https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e

**Comment by darenegade** [comment]
Geht aktuell wohl nicht mit Node 17+

https://github.com/vuejs/vuepress/issues/3136

Hier wäre auch eher ein größerer LCM Richtung VuePress 2 oder Vitepress notwendig
