### ISSUE TITLE
Remove digiwf-spring-cloudstream-utils

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#757]
Remove deprecated spring cloudstream utils module.

**Todos**

- Use fixed version of spring cloud stream utils in legacy integrations (ok.ewo, verification)
- Remove spring cloud stream utils module

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/757?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI
