### ISSUE TITLE
Migrate digiwf-spring-security to Spring Security 5.8

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#758]
Migrate digiwf-spring-security lib to Spring Security 5.8 to simplify spring boot 3 migration. Also make sure that the security lib is used by every application.

**Todo**

- Migrate to Spring Security 5.8 
- ~~Implement digiwf-spring-security lib in every application~~

**Additional Context**

- Migration Guide: https://docs.spring.io/spring-security/reference/5.8/migration/index.html

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/758?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI

**Comment by darenegade** [comment]
digiwf-spring-security wird schon an den relevanten Stellen genutzt und für Clients wird es eventuell zukünftig eine eigene Lib geben, ist aber nicht Teil der SB Hebung. Daher geschlossen
