### ISSUE TITLE
Split maven parent in multiple modules to simplify SB3 migration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#759]
Before we migrate to spring boot 3 we should split our maven project (aggregation) to migrate each part of the application separately (similar to #346). The change will be temporarily to simplify SB3 migration.

**Todos**

- Use maven aggregation (instead of inheritance) on the top level
  - Modules: connector, engine, gateway, libs, schema-registry, process, task
  - Note: Integrations are not affected, they are split up in another ticket
- Create `digiwf-parent`
  - We will keep the parent for further changes after the SB upgrade

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/759?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI
