### ISSUE TITLE
Use aggregation for digiwf-integrations

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#760]
We should seperate the digiwf-integrations from the digiwf-core parent using maven aggregation to maintain each integration separately. With this approach we could keep legacy integrations on an older version without migrating them to e.g. Spring Boot 3.

**Todo**

- Use maven aggregation for the digiwf-integrations
  - Each integration should be a standalone application
  - We don't have to migrate every integration (especially the legacy ones)
- Build an `digiwf-integration-parent`
  - We will keep the parent for further changes after the SB upgrade

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/760?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI
