### ISSUE TITLE
Migrate digiwf-connector to Spring Boot 3

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#761]
Migrate digiwf-connector to Spring Boot 3 (see [Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)).

**Todo**

- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies

**Additional Context**

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/761?planning-poker) with Zenhub @dominikhorn93 @lehju @lmoesle @StephanStrehlerCGI @darenegade

**Comment by lmoesle** [comment]
FYI Mit Spring Cloud 2022.0.4 hat sich das Funktion Routing geändert (https://github.com/it-at-m/digiwf-core/pull/892#issuecomment-1781268535).
