### ISSUE TITLE
Migrate digiwf-process to Spring Boot 3

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#764]
Migrate digiwf-process to Spring Boot 3 (see [Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)).

**Todo**

- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies

**Additional Context**

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/764?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @StephanStrehlerCGI
