### ISSUE TITLE
Remove digiwf-schema-registry

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#766]
Remove digiwf-schema-registry 

**Todo**

- Delete package

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/766?planning-poker) with Zenhub @dominikhorn93 @lehju @StephanStrehlerCGI @lmoesle

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/766?planning-poker) with Zenhub @darenegade
