### ISSUE TITLE
Migrate digiwf-libs to Spring Boot 3

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#767]
Migrate digiwf-libs to Spring Boot 3 (see [Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)).

**Todo**

- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies

**Additional Context**

- REST Template https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#apache-httpclient-in-resttemplate
- Hibernate https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#hibernate-61

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/767?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/767?planning-poker) with Zenhub @zambrovski

**Comment by lmoesle** [comment]
Ich habe die digiwf-libs auf Spring Boot 3 migriert in #892. Ich bin aber mit dem Ticket noch nicht ganz fertig geworden bzw. konnte nicht alles testen.

**Status**

- **digiwf-spring-security**: Ich habe  die Bibliothek auf Spring Boot 3 umgestellt, weiß aber nicht wie ich das Testen kann. Am besten schaut da nochmal jemand drüber, mir hat jetzt auf die schnelle die Zeit gefehlt mich intensiv in Spring Security einzuarbeiten
- **digiwf-camunda-prometheus**: Ist umgestellt, ich weiß aber nicht wie ich die Bibliothek testen kann bzw. wo die überhaupt verwendet wird
- **digiwf-message**: Die Tests sind fehlgeschlagen (irgendwas passt da mit Mockito nicht). Ich habe die problematischen Stellen rausgenommen und wollte die Tests nochmal überarbeiten. Ich habe für das Tests überarbeiten ein eigenes Ticket aufgemacht, dass ich wenn ich wieder da bin übernehmen kann #903
