### ISSUE TITLE
Ref Arch refactoring

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#769]
In addition to the spring boot 3 migration we should remove/add some RefArch Legacy:

- GracefullShutdown -> SB Probes with proper Openshift Config (Use of Startup Probe) - RefArch MR
    - Alle Service inkl. Integrationen 
- ErrorMapping (Config Map to 500) - RefArch [MR](https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/merge_requests/68)
- Eventuell: [CSRF Fix](https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/merge_requests/110)   --> Löst https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/gh/it-at-m/digiwf-core/1014 
- [Logback](https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/merge_requests/111) für Trace/Span-ID (eventuell schon Done)
    - Alle Service inkl. Integrationen 

\
- Codestyle ist out-of-scope. Hierzu gibt es ein eig. Issues

- ~~Maybe more: https://git.muenchen.de/groups/ccse/refarch-archetype/-/merge_requests?scope=all&state=merged~~

**Acceptance Criteria**

- [x] Graceful-Shutdown Probes updated and old Code removed
- [x] Error-Mapping integrated and configured
- [x] Trace/Span-IDs are printed in the JSON log

**Comment by darenegade** [comment]
> GracefullShutdown -> SB Probes with proper Openshift Config - RefArch MR

The "with proper Openshift Config" is pretty important as SB Probes alone behave differently than GracefullShutdown

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/769?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @StephanStrehlerCGI
