### ISSUE TITLE
Finish Spring Boot 3 Migration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#770]
After successfully migrating to spring boot we should undo the maven aggregation and use inheritance again for
- digiwf-connector
- digiwf-engine
- digiwf-gateway
- digiwf-libs
- digiwf-schema-registry
- digiwf-process
- digiwf-task

**Todo**

- Use maven inheritance for the maven modules

**Comment by darenegade** [comment]
Wir behalten die Aufsplittung für die Zukunft, um eine bessere Trennung der Deps zu erreichen
