### ISSUE TITLE
Formserver Integration not supporting booleans

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#793]
**Describe the bug**

If my formserver form contains boolean fields, they are transfered to the engine as string and therefore checkboxes in my digiwf form are always false.

**To Reproduce**

- Execute **Example Formserver Integration** process manually
- Check the created grouptask and see that all 4 datenschutz checkboxes work as expected
- Trigger the **Example Formserver Integration** process from the formserver integration
- Check the created grouptask and see that all 4 datenschutz checkboxes are false (they are all supposed to be true)

**Expected behavior**

The formserver integration should transfer boolean fields as boolean values and not as strings.

**Screenshots**

**Grouptask created by formserver integration**

![Formserver-start](https://github.com/it-at-m/digiwf-core/assets/37705369/5d702e26-495b-43a3-bd49-9c37d17912bf)

**Grouptask created manually**

![Manuell-gestartet](https://github.com/it-at-m/digiwf-core/assets/37705369/0a25e70b-03b2-4e21-8c03-a33a49b863c5)

**Acceptance Criteria**

- [ ] CIT-Forms can use checkboxes (bools) and transfer the corresponding input to digiwf

**Additional context**

If I check the process variables in camunda cockpit it looks like the formserver-integration is transfering boolean values as strings and not as booleans. Therefore, the form is not showing the correct state for checkboxes.

![Formserver-Cockpit](https://github.com/it-at-m/digiwf-core/assets/37705369/b223f9ce-4e5d-4f8d-b5fd-0787b43dc060)

It supposed to be:

![Cockpit](https://github.com/it-at-m/digiwf-core/assets/37705369/2469a18d-272f-4cfb-8d6a-7c618800d4d6)

**Comment by lmoesle** [comment]
Die Bibliothek `org.json`, die wir für die XML zu Json Konvertierung verwenden kann primitive Datentypen auch zu den richtigen Datentypen konvertieren (boolean, number, ...). Das hat zur Folge, dass in Formularfeldern auch der richtige Datentyp gesetzt werden muss. Ansonsten wird im Formular kein Wert angezeigt.

Ggf. müssen nach dem Bugfix bestehende Json Schemas angepasst werden (Im Schema muss der `type` des jeweiligen Feldes auf z.B. `number` oder `boolean` gesetzt werden.

- Ich habe den Fehler im Formserver behoben: https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/14
- Und den Beispielprozess angepasst: https://github.com/it-at-m/digiwf-core/pull/1224

**Comment by lmoesle** [comment]
Ich habe jetzt einen Custom Mapper für Booleans geschrieben. PR https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/14

**Comment by darenegade** [comment]
Thema wartet auf Feedback von Verantwortlichen der Routing-Komponenten zum Vorgehen bei Booleans und Zahlen

**Comment by darenegade** [comment]
@lmoesle Ich habe hier mal mit Michael gesprochen. Bei Bools wird eigentlich ein `mappertype="boolean"` attribute am  XML-Tag gesetzt. Wenn ich es richtig verstehe, dann sollte es doch genau damit schon autom. auf den richtigen Typ gehen.

<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2b66b5acb0d067a3e2c61ea2b52ddbfb41232c1/image.png" alt="image.png" />


Lass uns das gerne mal gemeinsam anschauen. Eventuell fehlt hier nur Doku🙈

XSD von EOZF: https://git.muenchen.de/einkommensorientierte-zusatzfoerderung/eingangsdatenstrukturen/-/blob/main/src/main/resources/Erstantrag/eozf-erstantrag-example01.xml?ref_type=heads#L94

**Comment by simonhir** [comment]
Testformular ist jetzt vorhanden siehe [Test-Dokumentation](https://confluence.muenchen.de/pages/viewpage.action?pageId=253084394#CypressTestDokumentation-TL-15:Formserver-Integration).
Hier fehlt noch die ganze Geschichte mit XSD und XSLT, was ja dann über das oben genannte Mapping bestimmt, wenn ich es richtig verstanden habe.
