### ISSUE TITLE
Auslesen des OU Trees/Abteilungsbaums aus dem LDAP sorgt immer wieder für Probleme

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#795]
Siehe Referenzticket: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/379

**Comment by darenegade** [comment]
Das Thema muss erstmal genauer angeschaut werden, ob wir hier wirklich was machen müssen. Der Plan geht eigentlich dahin, dass LDAP nicht mehr für Basis-Funktionen genutzt wird (stattdessen SSO) und zukünftig als reguläre Integration bereitgestellt wird
