### ISSUE TITLE
Build pipeline fails with test errors

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#803]
### Description:
In the `digiwf-engine` application, we are occasionally experiencing test failures, especially in the `VorgangZAlegenTemplateTest.shouldExecuteWithVorgangGesperrt` test. The test fails due to a database operation ('create' action) on the schema.

### Error Log:
```plaintext
[ERROR]   VorgangZAlegenTemplateTest.shouldExecuteWithVorgangGesperrt » ProcessEngine ENGINE-03017 Could not perform operation 'create' on database schema for SQL Statement: 'create table ACT_HI_PROCINST ( ... )'.
[INFO] 
[ERROR] Tests run: 70, Failures: 0, Errors: 26, Skipped: 0
[INFO] 
```

### Steps to Reproduce:
1. Run the test suite in `digiwf-engine` - `mvn clean verify` two times in parallel
2. Observe intermittent test failures in  e.g. `VorgangZAlegenTemplateTest`.

### Expected Result:
All tests, including `VorgangZAlegenTemplateTest`, should pass consistently without any errors.

### Actual Result:
The `VorgangZAlegenTemplateTest.shouldExecuteWithVorgangGesperrt` test intermittently fails with an error related to a 'create' database operation.

### Additional Information:
- This might be related to a race condition, database initialization state, or specific test setup prerequisites.
- Ensuring that the database is in a consistent and expected state before running the tests might help address the issue.
- Example pipelines:
  - https://github.com/it-at-m/digiwf-core/actions/runs/7589367547/job/20673856748
  - https://github.com/it-at-m/digiwf-core/actions/runs/7585805607/job/20662503199

**Comment by darenegade** [comment]
@zambrovski Hier ist das Issue zur Pipe

**Comment by darenegade** [comment]
Timebox 1 Tag Fehlersuche - Wenn der Fehler nicht gefunden wird, dann erstmal per Retry umgehen (Flaky-Test Bib)

**Comment by simonhir** [comment]
Issue from camunda library with the same problem: https://github.com/camunda/camunda-bpm-spring-boot-starter/issues/61
In the testing documentation there is mentioned that `ProvidedProcessEngineRule` should be used. See https://github.com/camunda/camunda-bpm-platform/blob/master/TESTING.md
