### ISSUE TITLE
Implement OAuth2 Login for Camunda Optimize 

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#808]
## Story

In order to provide uniform secure access to Camunda Optimize for the process owners (modellers), the access should be secured using LHM OAuth2 security. This is already done for the Camunda Webapps (see #402) of the engine (Cockpit, Admin, Tasklist) also camunda optimize should be behind the gateway and the login should be handled via OAuth2/SSO.

## Original Acceptance criteria
- Camunda Optimize is only reachable via the gateway
- The login and permissions are handled via oAuth like for the Cockpit -> Currently no implementation strategy, see problem description below

## Additional context
https://docs.camunda.io/optimize/self-managed/optimize-deployment/plugins/single-sign-on/

## Problem description

Optimize ist in Camunda 7 Modus so umgesetzt, dass es vollkommen auf der Engine als Identity-Provider aufbaut. Per Plugin kann man nur Authentication und Authorization getrennt integrieren und Authorization fragt anonym (also ohne Information über den aktuellen Benutzer) bei der Engine nach den Gruppenzugehörigkeiten und Rechten der Person. Diese Information steht uns nicht zur Verfügung.

## Lösungsmöglichkeit (kurz)

1. Optimize wird per Plugin für die Authentication per OAuth-Token erweitert, sodass Optimize hinter dem Gateway laufen kann
2. Auf der Engine werden weiterhin Rollen und Rechte gepflegt, aber keine Passwörter mehr (Aktuell sind die Rechte häufig direkt auf den Personen und muss daher aufgeräumt werden)
3. Die Rollen/Rechte werden auf einem Admin-Cockpit (integriert in der Engine-Rest) durch das DigiWF-Team gepflegt

## Extended solution architecture

<img width="1062" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5cd0fd305b3f387a5f4ecb7f81c3a3d113934f8/optimize-integration-architecture.drawio.png" alt="optimize-integration-architecture.drawio.png" />

The sketch above depicts the solution architecture regarding the access to different components: Engine, Camunda Webapps and Optimize by the process owner and platform admin.

#### Access to Camunda Webapps for the process owner

The process owners need access to Camunda Webapps of the Engine (especially Cockpit) to be able to monitor running processes. This access is secured by OAuth2 login initiated by the Gateway as implemented in #402. (request A) By doing so, we replaced the Camunda Identity Provider by a read-only token-based provider, which extracts the information about the user identity (preferred user name, first name, last name and email address) and user groups from the supplied JWT (request A1). In order to have a fine grained control of the visibility of process definitions inside the cockpit (request A2), we use Camunda Authorization service to create Authorizations based on process owner groups by allowing access to members of groups to specific resources.

#### Data collection by Camunda Optimize

In order to collect data about process executions, Camunda Optimize needs a connection to process engine. Instead of the engine itself (especially because of high DB load), we install a second engine installation in a homogeneous cluster mode (connected to the same DB as the engine). The connection requests are executed via REST (requests CB1 and CB2) and by default use shared secrets (HTTP Basic Authentication) used only for this connection. Using an additional `EngineRest` plugin we can inject a OAuth2 service token to this HTTP requests. Engine REST supplies a specific Spring Security configuration providing client credentials OAuth2 protection of the REST endpoints and the Camunda webapps.

#### Access to Camunda Optimize for the process owner

The process owners need access to Camunda Optimize to evaluate the executions of process instances. This access is secured by OAuth2 login initiated by the Gateway (request C). The identity of the user is passed to the Optimize user identification service (using for example the X-Forwarded-Preferred-Username HTTP header), which can be extracted by the Camunda Optimize `AuthenticationExtractor` plugin setting the logged in identity (request C1). 

The implementation of Camunda Optimize user permission checker allows the user to login to Optimize and executes permissions checks by calling the Camunda Identity service of the connected engine via REST. Instead of the deployed Camunda engine, we configure a second deployment that is connected to the database of the engine and exposing the REST endpoint (Engine REST). The request CB1 is responsible for the permission check and consists of the following parts:

1. call to `/identity/authorization` for `userIdIn=<preferredUserName>`
2. call to `/identity/group` for `userIdIn=<preferredUserName>`
3. (if call 2 returned a non-empty list) call to `/identity/authorization` for `groupIn=<listOfGroups>` for groups returned in 2.

The request CB1 is a separate request with currently no technical connection to the request C1 - so currently we don't see  any possibility to pass the JWT from the request C into request CB1. 

The intended mapping of permissions to process definitions of the engine should follow the same principles as for Camunda Webapps and should be based on the group permissions. Therefore, the resolution of the users's groups (asked in call 2) needs to be performed. We decided not to integrate this resolution to the call to Keycloak (technically possible, but high effort and not required in Camunda 8 scenario). Instead, the Engine REST service should maintain this information using standard DB-based Camunda Identity Service, storing the list of all users and their membership in the Camunda DB. In order to simplify this administration operation, we include a second Camunda Webapp (especially Camunda Admin) which is NOT integrated into OAuth2, but still runs behind the gateway (OAuth2 login first, second login on the webapps).

#### Access to Camunda Admin for the platform admin

The platform admins need to access the Camunda Admin of the DB-Based identity service in order to manage process permissions for groups and user group memberships in a Camunda database (request B). This access is secured twice: by OAuth2 login to pass the gateway and then by a login into DB-based identity service of Camunda using platform admin user. Only the password of the admin users are stored in the Camunda DB-based identity service (all process owners access different Camunda webapps using token-based identity provider - request A).

##### Alternative to Admin WebApps

Instead of the additional Admin WebApps the users, groups and correlations could be automatically created via the Camunda API. 
I.e. this should be possible by getting all users from a AD group which allows Optimize access i.e. `lhm-ab-digitalwf-optimize-user` or existing `lhm-ab-digitalwf-webapp-user`. For all of this users get there groups and filter to `lhm-ab-digitalwf-.*-admin`. For each entry the group and a correlation between the group and the user needs to be created (if not already existing) via API.

**Comment by darenegade** [comment]
@zambrovski @dominikhorn93 Könnt ihr das Thema bitte mal diskutieren und fürs Ref. vorbereiten

**Comment by darenegade** [comment]
Problem: Optimize ist in auf Camunda 7 schwierig umgesetzt, indem es vollkommen auf der Engine als Ident.-Provider aufbaut. Per Plugin kann man nur Authentication und Authorization getrennt integrieren und Authorization fragt anonym bei der Engine nach den Rechten der Person.

Folgende Lösungsmöglichkeit:

1. Optimize wird per Plugin für die Authentication per OAuth-Token erweitert, sodass Optimize hinter dem Gateway laufen kann
2. Auf der Engine werden weiterhin Rollen und Rechte gepflegt, aber keine Passwörter mehr (Aktuell sind die Rechte häufig direkt auf den Personen und muss daher aufgeräumt werden)
3. Die Rollen/Rechte werden auf einem Admin-Cockpit (integriert in der Engine-Rest) durch das DigiWF-Team gepflegt

**Comment by darenegade** [comment]
Eventuell passt der

`GET /{realm}/users/{id}/role-mappings/clients/{client}`

https://www.keycloak.org/docs-api/21.1.1/rest-api/#_client_role_mappings_resource

**Comment by simonhir** [comment]
Abklärung zwecks Auflösung der Rollen für einen User läuft.

**Comment by simonhir** [comment]
Nach Rücksprache mit @darenegade und IBS53:

- Verifizierung des eingehenden Tokens in Optimize soll umgesetzt werden
- Separates ezLDAP mit LDAP-AD-Anbindung wenig sinnvoll -> Auflösung von User zu Gruppen wird direkt in der Engine mit der bereits vorhandenen LDAP-Library, einer Anbindung an die LDAP-AD-Schnittstelle und einer eigenen Query umgesetzt

**Comment by simonhir** [comment]
Ops-MR: https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/432

**Comment by simonhir** [comment]
After discussion because of too large jar for openshift ConfigMap:
Decision:  build custom private optimize image for future usage
