### ISSUE TITLE
Switch to JDK17

### ISSUE THREAD

**Issue by zambrovski** [it-at-m/digiwf-core#824]
Before even trying to switch to Spring Boot 3, we need to make sure the library is switched to JDK17. There are several steps to do:

- [x] JDK17 is not including JS Scripting library Nashorn anymore, but needs to be patched with GraalVM JS Engine.
- [x] The minimum version in pom.xml should adjusted
- [x] The GitHub actions need to be adjusted

https://forum.camunda.io/t/script-expression-error-switching-from-jdk11-to-jdk17/48043

**Comment by zambrovski** [comment]
## Breaking

`task.execution.getVariable()` and `task.execution.setVariable()` should be replaced by `task.getVariable()` and `task.setVariable()` in script tasks.

This change is backwards compatible and works with JDK 11 too

**Comment by darenegade** [comment]
> task.execution.getVariable() and task.execution.setVariable() should be replaced by task.getVariable() and task.setVariable() in script tasks.

Shouldn't it be "task.getExecution().getVariable()"? Otherwise the behavior changes because the scope is different.

**Comment by darenegade** [comment]
## Breaking


https://www.graalvm.org/latest/reference-manual/js/NashornMigrationGuide/

**Comment by darenegade** [comment]
Feedback from Processdesign-Community: We should activate Nashorn-Compat Mode (Env Config)

**Comment by simonhir** [comment]
Pipeline currently doesn't work see https://github.com/it-at-m/digiwf-core/actions/runs/6623058116
