### ISSUE TITLE
Fixen von Alternativ-Textfehlern in vuetify

### ISSUE THREAD

**Issue by StephanStrehlerCGI** [it-at-m/digiwf-core#839]
# Ist Situation

Es gibt noch Alternativ Text Fehler in einigen Komponenten. 

# Ziel Situation

Alternativ Text Fehler wurden behoben 

# Akzeptanzkriterien 

 * Fehler behoben: Search field: Form field is not labeled, aria-label seems to be not identified correctly (the div is a control)
 * Fehler behoben: Search field with data: aria-role="combobox", aria-expanded="true", but aria-controls are not set (the div is a control...)
 * Fehler behoben: Assign group task: Form field is not labeled, aria-label seems to be not identified correctly (the div is a control)
 

https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/371

**Comment by darenegade** [comment]
Das Thema wartet auf Feedback von den Fachbereichen und der eig. Einschätzung von eingeschränkten Personen. Wir wissen beispielsweise aktuell nicht, welche Technologie sie bei der Bedienung nutzen

**Comment by darenegade** [comment]
Beim ersten Feedback kam zu den hier genannten Punkten keine negativ-Meldung. Daher erstmal geschlossen. 

Es wird behoben, wenn das Thema auftaucht
