### ISSUE TITLE
Hebung BPMN-Server (CoCreation)

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#901]
**Is your feature request related to a problem? Please describe.**

Alle Services müssen auf SB3 gehoben werden, damit wir auch die Kafka Hebung durchführen können.
Aus diesem Grund muss auch der BPMN-Server gehoben werden.

Da die CoCreation umgebaut wird, ist hier nur das nötigste für die Kafka-Hebung zu tun

**Describe the solution you'd like**

- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies
- Prüfung, ob BPMN-Server & Repo unter eigenem Repo in Github veröffentlicht werden kann und wenn dies ohne großen Aufwand möglich ist durchführen

**Describe alternatives you've considered**

**Acceptance Criteria**

- [x] BPMN-Server ist vollständig auf SB3 gehoben
- [x] BPMN-Repo ist in BPMN-Server integriert und ggfs. nach Github portiert
- [ ] BPMN-Repo / BPMN-Server deployed

**Additional context**

https://git.muenchen.de/digitalisierung/bpm-server

https://git.muenchen.de/openshift/kafka/-/issues/147 (Kafka Hebung)

**Comment by lmoesle** [comment]
Der bpm-server nutzt als Dependency [Miragon/bpm-repo](https://github.com/Miragon/bpm-repo). Das bpm-repo wurde schon länger nicht mehr aktualisiert und müsste dann auch aktualisiert werden.

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/901?planning-poker) with Zenhub @darenegade @lehju @lmoesle @simonhir @zambrovski

**Comment by lmoesle** [comment]
Ich habe den bpm-server (digiwf-cocreation) auf Spring Boot 3 gehoben.

1. Der PR für die Spring Boot 3 Hebung muss noch reviewed werden https://github.com/it-at-m/digiwf-cocreation/pull/3
2. PR für die local config Anpassung der Engine https://github.com/it-at-m/digiwf-core/pull/1029
2. Sobald der PR gemerged ist, muss noch digiwf-cocreation in Version 0.3.0 released werden
3. Der Ops MR kann dann reviewed/gemerged und die neue Version des bpm-servers kann ausgebracht werden https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/291
