### ISSUE TITLE
KVR-DMS-EAI: WSDL has changed

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#912]
**Is your feature request related to a problem? Please describe.**

Analog zu #595 wird auch bei der KVR-DMS die WSDL angepasst. Die WSDL ist exakt die gleiche, wie bei der
MUCS-DMS.

Zusätzlich benutzen wir noch alte Routen auf die EAI. Diese sollen ersetzt werden. 
(Siehe internes Issue in DigiWF-Support)

Auf Test ist die neue WSDL schon ausgespielt. **Auf Prod soll sie am 02. Feb. 2024 live gehen.**

**Describe the solution you'd like**

Umstellung der WSDL analog zu #595

* Umstellung erfolgt rein in der EAI

**Describe alternatives you've considered**

**Acceptance Criteria**

* WSDL wurde in der EAI umgestellt (Outgoing) und entsprechend gemappt auf die interne
* EAI wurde auf allen K-Umgebungen deployed zum Test des Asyl-Workflows

**Additional context**

* https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/396

**Comment by darenegade** [comment]
Thema hat sich auf Feb. verschoben

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/912?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @markostreich @simonhir @StephanStrehlerCGI

**Comment by markostreich** [comment]
Bitte das Review durchführen.

https://git.muenchen.de/digitalisierung/digitalisierung-eai-dmskvr/-/merge_requests/18

**Comment by markostreich** [comment]
WSDL auf Version 1.5.4 gehoben. Der lokale Entwicklertest war erfolgreich.

**Comment by darenegade** [comment]
@simonhir Kannst du hier noch kurz schreiben, warum es auf Imp. steht

**Comment by simonhir** [comment]
Rollout auf P am 02.02.2024 noch ausstehend.

**Comment by darenegade** [comment]
@simonhir @markostreich Haben wir auf Tests schon erfolgreich testen können?

**Comment by markostreich** [comment]
Also über die neuen Adressen auf ALWDMS-Seite, die uns genannt wurden, kriege ich gerade keine Verbindung aufgebaut. Ich muss das morgen mit dem Kollegen zusammen versuchen.

**Comment by markostreich** [comment]
Also über die neuen Adressen ALWDMS-Seite, die uns genannt wurden, kriege ich gerade keine Verbindung aufgebaut. Ich muss das morgen mit dem Kollegen zusammen versuchen.

**Comment by markostreich** [comment]
@darenegade @simonhir Konnte die Schnittstelle nun erfolgreich auf digiwf-dev und -test testen.

@simonhir Die service-configs sind vorbereitet. Bitte Review: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/346

**Comment by markostreich** [comment]
Die Umstellung auf Prod ist nun auch erledigt.
