### ISSUE TITLE
Error Messages werden nicht angezeigt

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#942]
**Describe the bug**
In der CoCreation angegebene Error-Messages werden im Formular nicht angezeigt

**To Reproduce**
Steps to reproduce the behavior: Sie internal Ticket

**Acceptance Criteria**

- [ ] Error-Messages werden angezeigt 

**Additional context**
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/401

**Comment by lmoesle** [comment]
Form: [bugfix-942-error-msg.json](https://github.com/it-at-m/digiwf-core/files/13424747/bugfix-942-error-msg.json)

**Comment by lmoesle** [comment]
Ich habe den Bug jetzt ein wenig analysiert und habe festgestellt, dass der Fehler in der vjsf Bibliothekt (https://github.com/koumoul-dev/vuetify-jsonschema-form) ist.  D.h. wir müssen den Fix in unserem Fork machen (https://github.com/it-at-m/vuetify-jsonschema-form).

**Comment by lmoesle** [comment]
Die Formbuilder Settings waren falsch gesetzt. Dadurch wurde die `message` Konfiguration für das Textfeld an der falschen Stelle eingefügt.

Bei schon bestehenden Formularen muss händisch das Json Schema angepasst werden, indem die Message Konfiguration gesetzt werden.
Sobald wir eine neue Version des Formbuilders veröffentlicht haben, wird die Konfiguration automatisch richtig gesetzt.

**Richtig**

```
"aktenzeichen": {
  "fieldType": "text",
  "title": "WM-Wohnungsnummer",
  "type": "string",
  "key": "aktenzeichen",
  "description": "Format S12-123456",
  "x-options": {
    "fieldColProps": {
      "cols": 12,
      "sm": 12
    },
    "messages": {
      "pattern": "Das Muster S12-123456 wird nicht eingehalten",
      "minLength": "Die Nummer ist kürzer als {minLength} Zeichen, bitte überprüfen Sie diese."
    }
  },
  "x-props": {
    "outlined": true,
    "dense": true
  },
  "x-rules": [],
  "pattern": "S\\d{2}-\\d+",
  "minLength": 4
}
}
```
Die `message` Konfiguration sollte nicht in den `fieldColProps` definiert werden.

**Falsch**
```
"properties": {
  "aktenzeichen": {
    "fieldType": "text",
    "title": "WM-Wohnungsnummer",
    "type": "string",
    "key": "aktenzeichen",
    "description": "Format S12-123456",
    "x-options": {
      "fieldColProps": {
        "cols": 12,
        "sm": 12,
        "messages": {
          "pattern": "Das Muster S12-123456 wird nicht eingehalten",
          "minLength": "Die Nummer ist kürzer als {minLength} Zeichen, bitte überprüfen Sie diese."
        }
      }
    },
    "x-props": {
      "outlined": true,
      "dense": true
    },
    "x-rules": [],
    "pattern": "S\\d{2}-\\d+",
    "minLength": 4
  }
}
```

**Comment by darenegade** [comment]
Dass das erst jetzt auffällt 🙈🤣

**Comment by simonhir** [comment]
Funktioniert aktuell noch nicht für komplexe Objekte. Mindestens `array`, `arrayObject` und wahrscheinlich auch `multi-user-input`

**Comment by lmoesle** [comment]
> Funktioniert aktuell noch nicht für komplexe Objekte. Mindestens `array`, `arrayObject` und wahrscheinlich auch `multi-user-input`

In dem Fall heißen die Configs `minItems` und `maxItems`. Ich passe das im Formbuilder auch noch an
