### ISSUE TITLE
Lokal-Save für Anträge/Tasks

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#947]
**Is your feature request related to a problem? Please describe.**

Aktuell gibt es die Zwischenspeicherfunktion für Aufgaben. Diese funktioniert aber nur über das Backend und es erfolgt eine Validierung (IT-Sec). Dadurch wird die Funktion selten genutzt.

**Describe the solution you'd like**

Anträge und Aufgaben sollten autom. im LocalStorage zwischengespeichert werden. Durch die Verschiebeung auf den Client muss keine Validierung erfolgen und jede Art von Draft kann gespeichert werden. Gleichzeitig kann die Speicherung autom. bei Eingabe erfolgen, sodass nicht explizit gespeichert werden muss.

**Describe alternatives you've considered**

Speicherung im Backend -> Für Aufgaben muss dann selektiv validiert werden (hoher Aufwand) und Anträge lassen sich nur schwer zwischenspeichern, vor allem in Hinblick auf Multi-Engine-Support

**Acceptance Criteria**

- [ ] Aufgaben und Anträge werden autom. Zwischegespeichert

**Additional context**

**Comment by markostreich** [comment]
@darenegade vermutlich Duplikat von #1022

**Comment by darenegade** [comment]
@markostreich Ja stimmt
