### ISSUE TITLE
(Kafka-)Truststore Updates live-update

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#980]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/235

Bei langen Laufzeiten von Pods kann es dazu kommen, dass die Trustores einen alten Stand haben, weil diese nicht live geupdatet werden, sondern erst nach redeploy.

Mögliche Lösung:

https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-configuration-watcher

* Watcher deployn
* Secrets & Config-Maps entsprechend mit Labels versehen
* Refresh-Endpoint Verfügbar machen, falls nicht verfügbar

Alternative:

Deployment auslösen per Config-Change -> Für Secret wohl nicht möglich

## Referenz
- https://git.muenchen.de/openshift/kafka/-/issues/99

**Comment by darenegade** [comment]
Die technische Lösung kann hier auch nochmal diskutiert werden. Nachdem wir nun im Schnitt jeden Monat einen neuen Release rausbringen und damit alles updaten, hat sich das Thema vielleicht auch erledigt.

**Comment by LenaB34** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/980?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @lmoesle @simonhir @StephanStrehlerCGI @zambrovski

**Comment by simonhir** [comment]
Tritt aktuell bei jedem hinzufügen eines Benutzers auf, was auf der neuen Platform öfter passieren kann.
Interne Vorschläge auch bereits vorhanden siehe obiges Issue.
Weitere Abstimmung nötig.

**Comment by darenegade** [comment]
Nicht mehr relevant

**Comment by simonhir** [comment]
Kann nur passieren, dass uns das noch einmal beim Abbau der Umgebungen betrifft.

**Comment by darenegade** [comment]
Ja, da können wir drauf achten. Der Scope vom Ticket hier war aber es zu automatisieren. Das brauchen wir nicht mehr
