### ISSUE TITLE
E-Mails mit spezifischen Logos

### ISSUE THREAD

**Issue by Sbivvds241** [it-at-m/digiwf-core#981]
Ausgegliedert aus: https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/188

* Env: Umgebungsname (+ Farbe)
* Farbschema im Logo wird übernommen in Mail. D.h. IT@M Logo wird durch DigiWF Logo ausgetauscht und erhält Farb-schema, wie Applikation 
   * Bilder müssten in Openshift als Env oder andere Ressource eingebunden werden, damit digiWF-Core unabhängig bleibt
* Template für alle Mails (Incident, Aufgaben Zuweisung, usw.) anpassen: Text

**Comment by darenegade** [comment]
Wird mit #1277 erledigt
