### ISSUE TITLE
Write and link Documentation

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-core#994]
## TODO
- Create documentation in [project_repo]/docs (see https://digiwf.muenchendigital.io/de/ecosystem/contribution/contribution)
- Link documentation to https://digiwf.muenchendigital.io

## Criteria
- There is a card for this integration artifact on https://digiwf.muenchendigital.io/de/resources/modules/modules
- There is a documentation page on https://digiwf.muenchendigital.io
- You can reach this page via click on the card or left link in the "integration artifacts" section
- The project readme has a short description and links to the documentation in /docs

**Comment by darenegade** [comment]
Erledigt mit #1382
