### ISSUE TITLE
Plug & Play integration of Integration Artifacts

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-core#997]
We need a plug & play mechanism, to connect integration artifacts to the platform without deploying anything on the core system. 

A szenario with element templates could look like this:
![Integrationskonzept für Services _ Feature Requests _ Ablaufdatum S3 (3)](https://user-images.githubusercontent.com/712911/155279344-4676557b-96fe-4616-8ee6-199a13d5ddbf.png)

We create a Spring Boot starter, that pushes all Element Templates to a specific topic, if the component connects to the event bus. All interested services can grab the templates from the bus and register them (e.g. the co creation).

Advantages:

- Every integration artifact holds his own and suitable element templates. 
- You can define the suitable topics inside the integration artifact (or the container) and deliver them with the element templates.
- If the integration artifact pops up, it is instantly usable.

Disadvantages:

-   We need a kind of synchronize mechanism, if a potentially receiver comes later on the platform, than some of the integration artifacts (what can always happen on a container environment like kubernetes).

Here a possible solution for re registering a template:
![re_register_element_templates](https://user-images.githubusercontent.com/712911/155288708-d266cd7b-4328-441e-b294-00892c9f5005.png)

@dominikhorn93 / @boal what do you think?

**Comment by xdoo** [comment]
@der-alex-k

**Comment by xdoo** [comment]
This is not only for integration artifacts, but for all components, that potentially provide element templates.

**Comment by boal** [comment]
The co creation artefact must therefore have three logics for  re registering the element templates.

1. After start up, the integration artefact for the elemet templates has to register all element templates at the co creation artefact.

2. After start up, the integration artefact for co creation has to request all element templates from all integration artefacts for element templates via the kafka event bus. This kafka event triggers the logic in the first point.

3. If a new element template is added to an integration artefact for element templates, this artefact registers this single element template at the co creation artefacts.

**Comment by xdoo** [comment]
@boal yes, exactly. I think we only need one topic for the whole exchange. This should not make to much effort, or?

**Comment by xdoo** [comment]
I think we have to issues:

We need a Spring Boot Starter that can be used in every Service (Integration Artifacts & other Services) that provides an API for the processes and therefore Element Templates. This Starter can:

- Push all Element Templates from a specified place to a specified topic on startup.
- Receives "requests for Element Templates" over a specified topic.
- Push all Element Templates from a specified place to a specified topic when requested.

I don't think that we need a Spring Boot Starter on the receiving service, because today this is only co-creation. So Co-Creation need to:

- Handle all incoming (over a specified topic) Element Templates.
- Request Element Templates after startup (again via specified topic).

Does this make sense @boal & @dominikhorn93 ?

**Comment by dominikhorn93** [comment]
I would do it manually in the first step and automate it only after we have thought more about co-creation
Element templates are only needed at design time, so we could easily create a project per integration artifact in the co creation platform and share it with all upcoming projects.

If we switch to a GIT approach:
I would check in the element templates in separate GIT repositories (for each integration artifact) and specify the dependency in the respective project. Then on-the-fly the Git repos of the artifacts are checked out for modeling.

**Comment by xdoo** [comment]
I see your point, but I think we need this anyway - even if we use git. If we have in the future a kind of "integration marketplace" we have a bunch of ready to use integration artifacts (provided by anyone), that can be used out of the box - create a Spring Boot (or take a ready to use docker image) project, add the starter for the integration artifact and you are ready to go. I think a step where you have to put Element Templates by hand on another git repo is error prone and not really smart. 

Btw. the actual internal process is very time consuming. We should provide as soon as possible a solution for this.

**Comment by dominikhorn93** [comment]
We have to differentiate here between element templates of the own project, which are changed on-the-fly and element templates from a library.

I think of it this way: I configure a workspace and say which integration modules in which version (possibly also latest) I want to use. Then the workspace.json file will automatically specify which repositories need to be checked out. We can also think about wrapping element templates in npm packages and downloading them when initializing the workspace.

Element templates that belong to the own project can be customized and used directly.
At the moment the Co-Creation platform can be extended by the element template artifact and the Modeler can load and use it automatically. I think that is totally enough for the first step. We can also share element templates with other Projects.

If we switch to a GIT / VS-Code approach a workspace.json file and a git / npm functionality would be more suitable in my Opinion. Element templates from other projects should be stable and versioned. An on-the-fly change seems to be a bit too much magic for me.

**Comment by darenegade** [comment]
No longer required with new CoCreation
