### ISSUE TITLE
Testumgebung klarer von Demoumgebung namentlich trennen

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#999]
https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/108

Aktuell wird dies aus der DB gezogen und ist nicht für alle Umgebungen gesetzt.

* Props im Gateway für Umgebung
   * Umgebungsname
   * Farbe in Hex 
* Wird über Actuator-Info Endpoint bereitgestellt
* Frontend holt dies bei Init und zeigt es im Header an mit Farblicher Unterscheidung (Farbschema überlegen) 
   * Farbe wird am Logo gesetzt beim WF von DigiWF
   * Umgebungsname neben / unter Logo (Vorschlag machen, was gut aussieht)
   * Prod zeigt kein Umg. Name an
   * Farben:
       * Prod: LHM-Gelb, wie aktuell (Default ohne Envs)
       * Processes-Demo: Grün
       * Processes-Test: Blau
       * Demo/Test/Dev: Rot
       
**Acceptance Criteria**

- [ ] Die Tasklist-UI zeigt offen, welche Umgebung aktuell dargestellt wird

**Comment by lmoesle** [comment]
<img width="700" alt="grafik" src="https://github.com/it-at-m/digiwf-core/assets/37705369/5a7b6af6-9a33-45a8-ad12-262e58eb8a44">

**Comment by darenegade** [comment]
@lmoesle Schaut gut aus👍
